using System.Globalization;
using System.Text;
using Serilog;
using ZScheme.Compiler.Diagnostics;
using ZScheme.Compiler.Ir;
using ZScheme.Compiler.Types;

namespace ZScheme.Compiler.Codegen;

public sealed partial class CSharpEmitter
{
    public string Emit(IrNode node)
    {
        Log.Debug("CSharpEmitter: emitting class {ClassName} in namespace {Namespace}", className, ns);
        Log.Debug("CSharpEmitter: funcMap={FuncMapCount} entries, typeMap={TypeMapCount} entries, importedModules={ImportedModuleCount}, precompiledMap={PrecompiledMapCount}",
            _funcToModuleClass.Count, _typeToModuleClass.Count, importedModules?.Count ?? 0, precompiledModuleMap?.Count ?? 0);
        _sb.Clear();
        var mainStatements = new List<IrNode>();

        if (!suppressVersionPreamble)
            EmitLine($"// <auto-generated by ZScheme compiler {CompilerInfo.VersionString}>");
        EmitLine("#nullable enable");
        EmitLine();
        if (clrUsings is { Count: > 0 })
        {
            foreach (var usingNs in clrUsings)
                EmitLine($"using {usingNs};");
            EmitLine();
        }

        EmitLine($"namespace {ns};");
        EmitLine();
        EmitTypeDeclarationsInline(node);
        EmitLine();

        if (HasProgramContent(node))
        {
            CollectModuleNames(node);

            EmitLine($"public static class {className}");
            EmitLine("{");
            _indent++;

            if (node is IrNode.Seq seq)
                foreach (var child in seq.Nodes)
                    EmitTopLevel(child, mainStatements);
            else
                EmitTopLevel(node, mainStatements);

            if (mainStatements.Count > 0)
            {
                EmitLine();
                EmitLine($"static {className}()");
                EmitLine("{");
                _indent++;
                foreach (var stmt in mainStatements)
                    EmitLine($"{EmitExpr(stmt)};");
                _indent--;
                EmitLine("}");
            }

            if (_userMainFunc is not null)
            {
                EmitLine();
                EmitLine("public static int Main(string[] args)");
                EmitLine("{");
                _indent++;
                if (_userMainFunc.Params.Count > 0)
                    EmitLine($"return {Sanitize("main")}(System.Collections.Immutable.ImmutableList.Create(args));");
                else
                    EmitLine($"return {Sanitize("main")}();");
                _indent--;
                EmitLine("}");
            }

            // Emit nested classes for object expressions
            if (_objectClasses.Count > 0)
            {
                EmitLine();
                EmitObjectClasses();
            }

            _indent--;
            EmitLine("}");
        }

        Log.Debug("CSharpEmitter: emit complete, {OutputLength} chars", _sb.Length);

        // Emit imported module classes (type declarations nested inside, plus functions/values)
        if (importedModules is { Count: > 0 })
            foreach (var (moduleClassName, defs) in importedModules)
            {
                Log.Debug("CSharpEmitter: processing imported module {ModuleClassName}, {DefCount} definitions",
                    moduleClassName, defs.Count);
                var hasContent = defs.Any(d =>
                    d is IrNode.FuncDef or IrNode.Let or IrNode.ClrCall or IrNode.Call or IrNode.Throw
                        or IrNode.Await or IrNode.RecordDecl or IrNode.UnionDecl or IrNode.ClassDecl
                        or IrNode.InterfaceDecl);
                if (!hasContent) continue;

                EmitLine();
                EmitLine($"public static class {moduleClassName}");
                EmitLine("{");
                _indent++;

                // Emit type declarations inside the module class
                foreach (var def in defs)
                    switch (def)
                    {
                        case IrNode.RecordDecl rec:
                            EmitLine(EmitRecordDecl(rec));
                            EmitLine();
                            break;
                        case IrNode.UnionDecl union:
                            EmitLine(EmitUnionDecl(union));
                            EmitLine();
                            break;
                        case IrNode.ClassDecl classDecl:
                            EmitClassDecl(classDecl);
                            EmitLine();
                            break;
                        case IrNode.InterfaceDecl ifaceDecl:
                            EmitInterfaceDecl(ifaceDecl);
                            EmitLine();
                            break;
                    }

                var moduleInitStatements = new List<IrNode>();
                foreach (var def in defs)
                    switch (def)
                    {
                        case IrNode.FuncDef func:
                            EmitFuncDef(func);
                            break;
                        case IrNode.Let let:
                            EmitLine(
                                $"public static {TypeToCs(LetVarType(let))} {Sanitize(let.VarName)} = {EmitExpr(let.Value)};");
                            if (let.Body is not IrNode.UnitConst)
                                moduleInitStatements.Add(let.Body);
                            break;
                        case IrNode.ClrCall:
                        case IrNode.Call:
                        case IrNode.Throw:
                        case IrNode.Await:
                            moduleInitStatements.Add(def);
                            break;
                    }

                if (moduleInitStatements.Count > 0)
                {
                    EmitLine();
                    EmitLine($"static {moduleClassName}()");
                    EmitLine("{");
                    _indent++;
                    foreach (var stmt in moduleInitStatements)
                        EmitLine($"{EmitExpr(stmt)};");
                    _indent--;
                    EmitLine("}");
                }

                _indent--;
                EmitLine("}");
            }

        return _sb.ToString();
    }

    private void EmitTopLevel(IrNode node, List<IrNode> mainStatements)
    {
        switch (node)
        {
            case IrNode.FuncDef func:
                if (func.Name == "main")
                    _userMainFunc = func;
                EmitFuncDef(func);
                break;
            case IrNode.RecordDecl rec:
                Log.Debug("CSharpEmitter: emitting record {RecordName} inside module class", rec.Name);
                EmitLine(EmitRecordDecl(rec));
                EmitLine();
                break;
            case IrNode.UnionDecl union:
                Log.Debug("CSharpEmitter: emitting union {UnionName} inside module class", union.Name);
                EmitLine(EmitUnionDecl(union));
                EmitLine();
                break;
            case IrNode.ClassDecl classDecl:
                EmitClassDecl(classDecl);
                EmitLine();
                break;
            case IrNode.InterfaceDecl ifaceDecl:
                EmitInterfaceDecl(ifaceDecl);
                EmitLine();
                break;
            case IrNode.Let let:
                EmitLine($"public static {TypeToCs(LetVarType(let))} {Sanitize(let.VarName)} = {EmitExpr(let.Value)};");
                if (let.Body is not IrNode.UnitConst)
                    EmitTopLevel(let.Body, mainStatements);
                break;
            case IrNode.ClrCall:
            case IrNode.Call:
            case IrNode.Throw:
            case IrNode.Await:
                mainStatements.Add(node);
                break;
        }
    }

    private void EmitFuncDef(IrNode.FuncDef func)
    {
        Log.Debug("CSharpEmitter: emitting function {FuncName}, IsAsync={IsAsync}, TypeParams={TypeParamCount}",
            func.Name, func.IsAsync, func.TypeParams?.Count ?? 0);
        var bodyStrategy = func.IsSelfRecursive && IsTailRecursive(func.Body, func.Name) ? "TCO"
            : func.IsAsync && ContainsAwait(func.Body) ? "async-statements"
            : func.Body is IrNode.Throw ? "throw"
            : func.Body is IrNode.Let && !HasLetSpineShadowing(func.Body, func.Params) ? "let-statements"
            : "expression";
        Log.Debug("CSharpEmitter: function {FuncName} body strategy: {Strategy}", func.Name, bodyStrategy);
        var prevTypeParams = _currentTypeParams;
        var prevFuncTypeVarMap = _currentFuncTypeVarMap;

        if (func.TypeParams is { Count: > 0 })
        {
            _currentFuncTypeVarMap = BuildTypeVarMap(func);
            _currentTypeParams = new HashSet<string>(func.TypeParams);
        }

        EmitAttributes(func.Attributes);
        var asyncPrefix = func.IsAsync ? "async " : "";
        var retTypeStr = func.IsAsync
            ? func.ReturnType == ZType.Unit
                ? "System.Threading.Tasks.Task"
                : $"System.Threading.Tasks.Task<{TypeToCs(func.ReturnType)}>"
            : ReturnTypeToCs(func.ReturnType);
        var parms = string.Join(", ",
            func.Params.Select(FormatParam));
        var typeParamStr = func.TypeParams is { Count: > 0 }
            ? $"<{string.Join(", ", func.TypeParams)}>"
            : "";

        var whereClause = FormatWhereConstraints(func.TypeParamConstraints);
        EmitLine($"public static {asyncPrefix}{retTypeStr} {Sanitize(func.Name)}{typeParamStr}({parms}){whereClause}");
        EmitLine("{");
        _indent++;
        _localBindings.Clear();

        if (func.IsSelfRecursive && IsTailRecursive(func.Body, func.Name))
            EmitTailRecursiveLoop(func);
        else if (func.IsAsync && ContainsAwait(func.Body))
            EmitAsyncStatementsBody(func.Body, func.ReturnType == ZType.Unit);
        else if (func.Body is IrNode.Throw || (func.IsAsync && func.ReturnType == ZType.Unit) ||
                 func.ReturnType == ZType.Unit)
            EmitLine($"{EmitExpr(func.Body)};");
        else if (func.Body is IrNode.Let && !HasLetSpineShadowing(func.Body, func.Params))
            EmitStatementsBody(func.Body, func.ReturnType);
        else
            EmitLine($"return {EmitExpr(func.Body)};");

        _indent--;
        EmitLine("}");
        EmitLine();

        _currentTypeParams = prevTypeParams;
        _currentFuncTypeVarMap = prevFuncTypeVarMap;
    }

    private void EmitTailRecursiveLoop(IrNode.FuncDef func)
    {
        EmitLine("while (true)");
        EmitLine("{");
        _indent++;

        EmitTcoBody(func.Body, func.Name, func.Params, func.ReturnType);

        _indent--;
        EmitLine("}");
    }

    private void EmitTcoBody(IrNode body, string funcName, IReadOnlyList<IrParam> parms, ZType returnType)
    {
        switch (body)
        {
            case IrNode.If @if:
                EmitLine($"if ({EmitExpr(@if.Condition)})");
                EmitLine("{");
                _indent++;
                EmitTcoBody(@if.Then, funcName, parms, returnType);
                _indent--;
                EmitLine("}");
                EmitLine("else");
                EmitLine("{");
                _indent++;
                EmitTcoBody(@if.Else, funcName, parms, returnType);
                _indent--;
                EmitLine("}");
                break;

            case IrNode.Let let:
                EmitLetStmt(let);
                EmitTcoBody(let.Body, funcName, parms, returnType);
                break;

            case IrNode.Call { Function: IrNode.Var v } call when v.Name == funcName:
                // Tail recursive call — compute new args, then reassign params, then continue
                for (var i = 0; i < call.Args.Count && i < parms.Count; i++)
                    EmitLine($"var __tmp_{i} = {EmitExpr(call.Args[i])};");
                for (var i = 0; i < call.Args.Count && i < parms.Count; i++)
                    EmitLine($"{SanitizeParam(parms[i].Name)} = __tmp_{i};");
                EmitLine("continue;");
                break;

            case IrNode.Throw:
                EmitLine($"{EmitExpr(body)};");
                break;

            case IrNode.Await:
                if (returnType == ZType.Unit)
                    EmitLine($"{EmitExpr(body)};");
                else
                    EmitLine($"return {EmitExpr(body)};");
                break;

            default:
                if (returnType == ZType.Unit)
                    EmitLine($"{EmitExpr(body)};");
                else
                    EmitLine($"return {EmitExpr(body)};");
                break;
        }
    }

    private string EmitExpr(IrNode node)
    {
        return node switch
        {
            IrNode.IntConst n => FormatIntLiteral(n.Value),
            IrNode.FloatConst n => $"{n.Value.ToString(CultureInfo.InvariantCulture)}f",
            IrNode.BoolConst n => n.Value ? "true" : "false",
            IrNode.StringConst n => $"\"{EscapeString(n.Value)}\"",
            IrNode.UnitConst => "default(System.ValueTuple)",
            IrNode.NullConst => "null",
            IrNode.Var n => EmitVar(n),
            IrNode.Let n => EmitLetExpr(n),
            IrNode.If n => EmitIfExpr(n),
            IrNode.BinOp n => EmitBinOp(n),
            IrNode.UnaryOp n => EmitUnaryOp(n),
            IrNode.Call n => EmitCall(n),
            IrNode.ClrCall n => EmitClrCall(n),
            IrNode.FuncDef n => EmitLambdaExpr(n),
            IrNode.TupleNew n => $"({string.Join(", ", n.Elements.Select(EmitExpr))})",
            IrNode.RecordNew n => EmitRecordNew(n),
            IrNode.RecordWith n => EmitRecordWith(n),
            IrNode.FieldGet n => $"{ParenthesizeReceiver(n.Record, EmitExpr(n.Record))}.{Sanitize(n.FieldName)}",
            IrNode.UnionCaseNew n => EmitUnionCaseNew(n),
            IrNode.Match n => EmitMatch(n),
            IrNode.MutableArrayNew n => EmitMutableArrayNew(n),
            IrNode.TcoJump j => EmitTcoJump(j),
            IrNode.MethodCall n => EmitMethodCall(n),
            IrNode.ObjectExpr n => EmitObjectExpr(n),
            IrNode.ClrNew n => EmitClrNew(n),
            IrNode.Throw n => EmitThrow(n),
            IrNode.WithHandlers n => EmitWithHandlers(n),
            IrNode.Await n => $"await {EmitExpr(n.Expr)}",
            IrNode.SuperMethodCall n => EmitSuperMethodCall(n),
            // No outer parens: `(this.X = expr);` is rejected as a statement
            // by C# (CS0201 — only assignment, call, increment, decrement,
            // await, and new-object expressions can be used as statements),
            // and `set!` is Unit-typed so it commonly lands in statement
            // position (e.g. inside `(begin (set! ...) ...)`). The bare
            // assignment is valid both as a statement and as an expression in
            // the contexts where SetField can appear (function args, ternary
            // arms, lambda bodies — all permit unparenthesized assignment).
            IrNode.SetField n => $"this.{Sanitize(n.FieldName)} = {EmitExpr(n.Value)}",
            _ => ErrorAndReturn($"C# emission not implemented for {node.GetType().Name}", "default", node.Span)
        };
    }

    private string EmitLetExpr(IrNode.Let n)
    {
        var valExpr = EmitExpr(n.Value);
        var bodyExpr = EmitExpr(n.Body);
        var varType = TypeToCs(LetVarType(n));
        var bodyType = TypeToCs(n.Body.Type);

        // When the value is Unit-typed (e.g. a void CLR call like Console.WriteLine),
        // emit as a block lambda since void expressions can't be passed as arguments
        if (LetVarType(n) is ZType.ZPrimitiveType { Kind: PrimitiveKind.Unit })
        {
            // When body is also Unit (e.g. chained void calls in begin), both are statements
            if (n.Body.Type is ZType.ZPrimitiveType { Kind: PrimitiveKind.Unit })
                return $"((System.Func<{bodyType}>)(() => {{ {valExpr}; {bodyExpr}; return default(System.ValueTuple); }}))()";
            return $"((System.Func<{bodyType}>)(() => {{ {valExpr}; return {bodyExpr}; }}))()";
        }

        // Use an immediately invoked lambda for let-in-expression, wrapped in Func<> delegate cast
        return
            $"((System.Func<{varType}, {bodyType}>)(({varType} {SanitizeParam(n.VarName)}) => {bodyExpr}))({valExpr})";
    }

    private string EmitIfExpr(IrNode.If n)
    {
        var cond = EmitExpr(n.Condition);
        var then = EmitExpr(n.Then);
        var @else = EmitExpr(n.Else);
        return $"({cond} ? {then} : {@else})";
    }

    private string EmitBinOp(IrNode.BinOp n)
    {
        var left = EmitExpr(n.Left);
        var right = EmitExpr(n.Right);
        var op = n.Op switch
        {
            "=" => "==",
            "!=" => "!=",
            "and" => "&&",
            "or" => "||",
            _ => n.Op
        };
        // Arithmetic on a pair of constant subexpressions is folded by Roslyn
        // at compile time; overflow there becomes CS0220 in the default
        // checked context. ZScheme's semantics are unchecked (matches the IL
        // backend's `add/sub/mul/div/rem` opcodes), so wrap constant-only
        // arithmetic in `unchecked(...)` to preserve wrap-around and avoid
        // the compile error without polluting general arithmetic with
        // redundant wrappers.
        if (n.Op is "+" or "-" or "*" or "/" or "%"
            && IsConstantExpr(n.Left) && IsConstantExpr(n.Right))
            return $"unchecked({left} {op} {right})";
        return $"({left} {op} {right})";
    }

    private static bool IsConstantExpr(IrNode node) => node switch
    {
        IrNode.IntConst or IrNode.FloatConst or IrNode.BoolConst
            or IrNode.StringConst or IrNode.UnitConst or IrNode.NullConst => true,
        IrNode.UnaryOp u => IsConstantExpr(u.Operand),
        IrNode.BinOp b => IsConstantExpr(b.Left) && IsConstantExpr(b.Right),
        // A C# ternary `c ? a : b` is a constant expression when all three
        // parts are constants — Roslyn will then fold it and apply CS0220 to
        // any overflowing arithmetic that reaches it.
        IrNode.If i => IsConstantExpr(i.Condition) && IsConstantExpr(i.Then) && IsConstantExpr(i.Else),
        _ => false,
    };

    private string EmitUnaryOp(IrNode.UnaryOp n)
    {
        var operand = EmitExpr(n.Operand);
        var op = n.Op switch
        {
            "not" => "!",
            _ => n.Op
        };
        return $"({op}({operand}))";
    }

    private string EmitCall(IrNode.Call n)
    {
        var args = string.Join(", ", n.Args.Select(EmitExpr));
        if (n.Function is IrNode.FuncDef lambda)
        {
            // An immediately-invoked lambda has no target type for C# to infer
            // against, so `(() => expr)(...)` fails with CS0149. Cast to a
            // Func<>/Action<> delegate so the invocation type-checks.
            var delegateType = LambdaDelegateType(lambda);
            return $"(({delegateType})({EmitLambdaExpr(lambda)}))({args})";
        }
        var func = EmitExpr(n.Function);
        return $"{func}({args})";
    }

    private string LambdaDelegateType(IrNode.FuncDef lambda)
    {
        var paramTypes = lambda.Params.Select(p => TypeToCs(p.Type)).ToList();
        if (lambda.ReturnType is ZType.ZPrimitiveType { Kind: PrimitiveKind.Unit })
            return paramTypes.Count == 0
                ? "System.Action"
                : $"System.Action<{string.Join(", ", paramTypes)}>";
        paramTypes.Add(TypeToCs(lambda.ReturnType));
        return $"System.Func<{string.Join(", ", paramTypes)}>";
    }

    private string EmitVar(IrNode.Var n)
    {
        if (_currentObjectCapturedFields is not null &&
            _currentObjectCapturedFields.TryGetValue(n.Name, out var fieldAccess))
            return fieldAccess;

        if (_currentClassFields is not null && _currentClassFields.Contains(n.Name))
            return $"this.{Sanitize(n.Name)}";

        if (_funcToModuleClass.TryGetValue(n.Name, out var modClass))
            return $"{modClass}.{Sanitize(n.Name)}";

        if (_currentModuleNames.Contains(n.Name))
            return _currentClassFields is not null
                ? $"{className}.{Sanitize(n.Name)}"
                : Sanitize(n.Name);

        if (_localBindings.Contains(n.Name))
            return SanitizeParam(n.Name);

        return SanitizeParam(n.Name);
    }

    private string EmitClrCall(IrNode.ClrCall n)
    {
        Log.Debug("CSharpEmitter: CLR call {TypeName}.{MethodName}, {ArgCount} args, hasOutParams={HasOut}",
            n.QualifiedTypeName, n.MethodName, n.Args.Count, n.OutParams is { Count: > 0 });
        if (n.OutParams is { Count: > 0 })
            return EmitOutParamStaticCall($"{n.QualifiedTypeName}.{n.MethodName}", n.Args, n.OutParams, n.Type);

        var args = string.Join(", ", n.Args.Select(EmitExpr));
        return $"{n.QualifiedTypeName}.{n.MethodName}({args})";
    }

    private string EmitClrNew(IrNode.ClrNew n)
    {
        var args = string.Join(", ", n.Args.Select(EmitExpr));
        var typeName = n.QualifiedTypeName;
        if (n.TypeArgs.Count > 0)
            typeName = $"{typeName}<{string.Join(", ", n.TypeArgs.Select(TypeToCs))}>";
        return $"new {typeName}({args})";
    }

    private string EmitOutParamMethodCall(string receiver, string methodName, IReadOnlyList<IrNode> visibleArgs,
        IReadOnlyList<ClrInterop.OutParamInfo> outParams, ZType returnType)
    {
        // Generate: ((System.Func<ReturnType>)(() => {
        //     var __out0 = default(T0); var __out1 = default(T1);
        //     var __ret = receiver.Method(arg0, out __out0, arg1, out __out1);
        //     return (__ret, __out0, __out1);
        // }))()
        var sb = new StringBuilder();
        sb.Append($"((System.Func<{TypeToCs(returnType)}>)(() => {{ ");

        // Declare out-param locals
        for (var i = 0; i < outParams.Count; i++)
            sb.Append($"{TypeToCs(outParams[i].ElementType)} __out{i} = default; ");

        // Build the argument list interleaving visible args and out params
        var fullArgs = BuildOutParamArgList(visibleArgs, outParams);
        sb.Append($"var __ret = {receiver}.{methodName}({fullArgs}); ");
        sb.Append("return (__ret");
        for (var i = 0; i < outParams.Count; i++)
            sb.Append($", __out{i}");
        sb.Append("); }))()");
        return sb.ToString();
    }

    private string EmitOutParamStaticCall(string qualifiedCall, IReadOnlyList<IrNode> visibleArgs,
        IReadOnlyList<ClrInterop.OutParamInfo> outParams, ZType returnType)
    {
        var sb = new StringBuilder();
        sb.Append($"((System.Func<{TypeToCs(returnType)}>)(() => {{ ");

        for (var i = 0; i < outParams.Count; i++)
            sb.Append($"{TypeToCs(outParams[i].ElementType)} __out{i} = default; ");

        var fullArgs = BuildOutParamArgList(visibleArgs, outParams);
        sb.Append($"var __ret = {qualifiedCall}({fullArgs}); ");
        sb.Append("return (__ret");
        for (var i = 0; i < outParams.Count; i++)
            sb.Append($", __out{i}");
        sb.Append("); }))()");
        return sb.ToString();
    }

    private string EmitThrow(IrNode.Throw n)
    {
        return $"throw {EmitExpr(n.Expr)}";
    }

    private string EmitLambdaExpr(IrNode.FuncDef n)
    {
        Log.Debug("CSharpEmitter: lambda expression, {ParamCount} params, returnType={ReturnType}",
            n.Params.Count, n.ReturnType);
        var parms = string.Join(", ",
            n.Params.Select(p => $"{TypeToCs(p.Type)} {SanitizeParam(p.Name)}"));
        var body = EmitExpr(n.Body);
        return n.ReturnType is ZType.ZPrimitiveType { Kind: PrimitiveKind.Unit }
            ? $"(({parms}) => {{ {body}; }})"
            : $"(({parms}) => {body})";
    }

    private string EmitRecordNew(IrNode.RecordNew n)
    {
        var args = string.Join(", ", n.Fields.Select(f => $"{Sanitize(f.FieldName)}: {EmitExpr(f.Value)}"));
        // For generic records/structs, emit the closed type args so C# does not require
        // ctor-inference (which our named-args form blocks anyway).
        var typeName = n.Type is ZType.ZNamedType { TypeArgs.Count: > 0 } nt
            ? TypeToCs(nt)
            : QualifyType(n.TypeName);
        return $"new {typeName}({args})";
    }

    private string EmitRecordWith(IrNode.RecordWith n)
    {
        // `(p) with { ... }` does not parse in C# because `(p)` looks like a cast operator.
        // Emit the record expression without wrapping parens and wrap the whole `with`
        // expression so the result composes safely inside larger expressions.
        var setters = string.Join(", ",
            n.Updates.Select(u => $"{Sanitize(u.FieldName)} = {EmitExpr(u.Value)}"));
        return $"({EmitExpr(n.Record)} with {{ {setters} }})";
    }

    private string EmitUnionCaseNew(IrNode.UnionCaseNew n)
    {
        // Extract type args from the node's type (the union's named type with type arguments)
        var typeArgStr = "";
        if (n.Type is ZType.ZNamedType { TypeArgs.Count: > 0 } nt)
            typeArgStr = $"<{string.Join(", ", nt.TypeArgs.Select(TypeToCs))}>";

        var args = string.Join(", ", n.Args.Select(EmitExpr));
        return n.Args.Count == 0
            ? $"new {QualifyType(n.CaseName)}{typeArgStr}()"
            : $"new {QualifyType(n.CaseName)}{typeArgStr}({args})";
    }

    private string EmitMatch(IrNode.Match n)
    {
        Log.Debug("CSharpEmitter: emitting match, {ArmCount} arms, scrutinee type={ScrutineeType}",
            n.Arms.Count, n.Scrutinee.Type);
        var scrutinee = EmitExpr(n.Scrutinee);
        var scrutineeType = n.Scrutinee.Type;

        // If the scrutinee expression is a union-case constructor call (e.g.
        // `new Some<int>(...)`), its C# expression type is the concrete case, not
        // the union base. Sibling case patterns (e.g. `None<int>`) are then
        // rejected by Roslyn as CS8121 — a `Some<int>` can never be a `None<int>`.
        // The scrutinee's IR type IS the union base, so cast the emitted expression
        // back up to that declared type whenever the scrutinee narrows below its
        // declared type (only happens today for `UnionCaseNew`). Variables and most
        // other expressions already carry the declared type in C#, so skipping the
        // cast there keeps the emitted source clean and matches prior test
        // expectations.
        if (scrutineeType is ZType.ZNamedType named
            && ScrutineeNarrowsBelowIrType(n.Scrutinee)
            && n.Arms.Any(a => ArmReferencesSiblingCase(a.Pattern)))
        {
            scrutinee = $"(({TypeToCs(named)}){scrutinee})";
        }

        // Drop unreachable trailing arms so Roslyn doesn't warn:
        //  - arms after any irrefutable pattern (wildcard/variable)
        //  - arms after bool exhaustiveness (both true and false literal patterns seen)
        var usefulArms = PruneUnreachableArms(n.Arms, scrutineeType);

        var sb = new StringBuilder();
        sb.Append($"{scrutinee} switch {{ ");

        foreach (var arm in usefulArms)
        {
            var pattern = EmitPattern(arm.Pattern, scrutineeType);
            var body = EmitExpr(arm.Body);
            sb.Append($"{pattern} => {body}, ");
        }

        // Only add fallback if the last arm isn't already a catch-all
        // and the arms aren't known to be exhaustive (e.g. bool with both true/false covered).
        var lastPattern = usefulArms[^1].Pattern;
        if (lastPattern is not IrPattern.Wildcard and not IrPattern.Variable
            && !IsIrrefutablePattern(lastPattern)
            && !ArmsAreExhaustive(usefulArms, scrutineeType))
            sb.Append("_ => throw new System.InvalidOperationException(\"Non-exhaustive match\"), ");
        sb.Append('}');
        return sb.ToString();
    }

    private static List<IrMatchArm> PruneUnreachableArms(
        IReadOnlyList<IrMatchArm> arms, ZType? scrutineeType)
    {
        var isBool = scrutineeType is ZType.ZPrimitiveType { Kind: PrimitiveKind.Bool };
        var sawTrue = false;
        var sawFalse = false;
        // Float literal patterns are compared by IEEE 754 equality, so -0.0 and
        // 0.0 are the *same* pattern. Emitting both to a C# switch expression
        // trips CS8510 ("pattern is unreachable") — see fuzzer seed 0xf0ab7e8f.
        // Drop any float-literal arm whose value equals a prior one under `==`.
        var seenFloats = new List<float>();
        var result = new List<IrMatchArm>(arms.Count);
        foreach (var arm in arms)
        {
            if (arm.Pattern is IrPattern.Literal { Value: float f })
            {
                if (seenFloats.Any(s => s == f))
                    continue;
                seenFloats.Add(f);
            }

            result.Add(arm);
            if (IsIrrefutablePattern(arm.Pattern))
                break;
            if (isBool && arm.Pattern is IrPattern.Literal { Value: bool b })
            {
                if (b) sawTrue = true;
                else sawFalse = true;
                if (sawTrue && sawFalse)
                    break;
            }
        }
        return result;
    }

    private static bool ArmsAreExhaustive(IReadOnlyList<IrMatchArm> arms, ZType? scrutineeType)
    {
        if (scrutineeType is ZType.ZPrimitiveType { Kind: PrimitiveKind.Bool })
        {
            var sawTrue = false;
            var sawFalse = false;
            foreach (var arm in arms)
            {
                if (arm.Pattern is IrPattern.Literal { Value: bool b })
                {
                    if (b) sawTrue = true;
                    else sawFalse = true;
                }
            }
            return sawTrue && sawFalse;
        }
        return false;
    }

    private static bool IsIrrefutablePattern(IrPattern p) => p switch
    {
        IrPattern.Wildcard => true,
        IrPattern.Variable => true,
        IrPattern.Tuple t => t.Elements.All(IsIrrefutablePattern),
        _ => false
    };

    /// <summary>
    /// True if the pattern contains a constructor pattern — meaning the match
    /// tests against a union case (or record type) rather than a primitive value.
    /// When this is true, we need to widen the scrutinee's emitted C# expression
    /// to its declared IR type so Roslyn's exhaustiveness/reachability analysis
    /// doesn't reject sibling case patterns as impossible.
    /// </summary>
    private static bool ArmReferencesSiblingCase(IrPattern p) => p switch
    {
        IrPattern.Constructor => true,
        IrPattern.Tuple t => t.Elements.Any(ArmReferencesSiblingCase),
        _ => false
    };

    /// <summary>
    /// True if the scrutinee's emitted C# expression has a narrower C# type than
    /// its IR `Type`. Today this happens only for <c>UnionCaseNew</c>: the IR type
    /// is the union base, but the emitted `new CaseName&lt;...&gt;(...)` expression
    /// types at the case subtype. Variable references, let bindings, calls, and
    /// other expressions carry the declared IR type in C# already, so no cast is
    /// needed for them.
    /// </summary>
    private static bool ScrutineeNarrowsBelowIrType(IrNode scrutinee) => scrutinee switch
    {
        IrNode.UnionCaseNew => true,
        _ => false
    };

    private string EmitPattern(IrPattern p, ZType? scrutineeType)
    {
        return p switch
        {
            IrPattern.Wildcard => "_",
            IrPattern.Variable v => $"var {SanitizeParam(v.Name)}",
            IrPattern.Literal { Value: int i } => FormatIntLiteral(i),
            IrPattern.Literal { Value: float f } =>
                $"{f.ToString(CultureInfo.InvariantCulture)}f",
            IrPattern.Literal { Value: bool b } => b ? "true" : "false",
            IrPattern.Literal { Value: string s } => $"\"{EscapeString(s)}\"",
            IrPattern.Tuple t => $"({string.Join(", ", t.Elements.Select(e => EmitPattern(e, null)))})",
            IrPattern.Constructor c => EmitConstructorPattern(c, scrutineeType),
            _ => WarnAndReturn($"Unsupported pattern type for C# emission: {p.GetType().Name}", "_")
        };
    }

    private string EmitConstructorPattern(IrPattern.Constructor c, ZType? scrutineeType)
    {
        var qualifiedName = ResolveConstructorName(c.Name, scrutineeType);

        if (c.Fields.Count == 0)
            return qualifiedName;

        var fields = string.Join(", ",
            c.Fields.Select((f, i) => EmitPattern(f, ComputeFieldScrutineeType(scrutineeType, c.Name, i))));
        return $"{qualifiedName}({fields})";
    }

    // Given the scrutinee ZType a constructor pattern is matching against, return
    // the ZType each field pattern will see. The outer pattern's scrutinee carries
    // the concrete type arguments (e.g., Option<Result<Int, String>>); we look up
    // the union case's field templates (e.g., Some<T0> has field of type T0) and
    // substitute the outer type args to produce the field's concrete type
    // (Result<Int, String>), which nested constructor patterns then use to emit
    // their own generic type arguments.
    private ZType? ComputeFieldScrutineeType(ZType? scrutineeType, string caseName, int fieldIdx)
    {
        // Resolve the case's owning union, preferring the scrutinee's type name.
        string? unionName = scrutineeType is ZType.ZNamedType named ? named.Name : null;
        IReadOnlyList<ZType> typeArgs = scrutineeType is ZType.ZNamedType nt ? nt.TypeArgs : [];

        if (unionName is null || !_unionCaseFieldTypes.ContainsKey($"{unionName}.{caseName}"))
            if (_caseToUnion.TryGetValue(caseName, out var foundUnion))
                unionName = foundUnion;

        if (unionName is null) return null;
        if (!_unionCaseFieldTypes.TryGetValue($"{unionName}.{caseName}", out var entry)) return null;
        if (fieldIdx >= entry.FieldTypes.Count) return null;

        var fieldTemplate = entry.FieldTypes[fieldIdx];
        if (entry.TypeParams.Count == 0 || typeArgs.Count == 0) return fieldTemplate;

        var subst = new Dictionary<string, ZType>();
        for (var i = 0; i < entry.TypeParams.Count && i < typeArgs.Count; i++)
            subst[entry.TypeParams[i]] = typeArgs[i];
        return SubstituteTypeParams(fieldTemplate, subst);
    }

    private static ZType SubstituteTypeParams(ZType type, IReadOnlyDictionary<string, ZType> map)
    {
        return type switch
        {
            ZType.ZNamedType { TypeArgs.Count: 0 } nt when map.TryGetValue(nt.Name, out var mapped) => mapped,
            ZType.ZNamedType nt => new ZType.ZNamedType(nt.Name,
                nt.TypeArgs.Select(a => SubstituteTypeParams(a, map)).ToList()),
            ZType.ZFuncType ft => new ZType.ZFuncType(
                ft.Params.Select(p => SubstituteTypeParams(p, map)).ToList(),
                SubstituteTypeParams(ft.Return, map),
                ft.IsVariadic),
            ZType.ZNullableType nn => new ZType.ZNullableType(SubstituteTypeParams(nn.Inner, map)),
            _ => type
        };
    }

    private string EmitMutableArrayNew(IrNode.MutableArrayNew n)
    {
        var csType = TypeToCs(n.ElementType);
        if (n.Elements.Count == 0)
            return $"System.Array.Empty<{csType}>()";
        var elems = string.Join(", ", n.Elements.Select(EmitExpr));
        return $"new {csType}[] {{ {elems} }}";
    }

    private string EmitTcoJump(IrNode.TcoJump j)
    {
        // This is used in the tail-recursive loop rewrite
        var sb = new StringBuilder();
        sb.Append("{ ");
        for (var i = 0; i < j.NewArgs.Count; i++)
        {
            var tmpName = $"__tmp_{i}";
            sb.Append($"var {tmpName} = {EmitExpr(j.NewArgs[i])}; ");
        }

        for (var i = 0; i < j.NewArgs.Count; i++) sb.Append($"__{SanitizeParam(j.ParamNames[i])} = __tmp_{i}; ");
        sb.Append("continue; }");
        return sb.ToString();
    }

    private string EmitMethodCall(IrNode.MethodCall n)
    {
        Log.Debug("CSharpEmitter: method call .{MethodName}, {ArgCount} args, isProperty={IsProperty}, isIndexer={IsIndexer}",
            n.MethodName, n.Args.Count, n.IsProperty, n.IsIndexer);
        var receiver = ParenthesizeReceiver(n.Receiver, EmitExpr(n.Receiver));
        var methodName = Sanitize(n.MethodName);
        if (n.IsPropertySet) return $"{receiver}.{n.MethodName} = {EmitExpr(n.Args[0])}";
        if (n.IsProperty) return $"{receiver}.{methodName}";
        if (n.IsIndexerSet) return $"{receiver}[{EmitExpr(n.Args[0])}] = {EmitExpr(n.Args[1])}";
        if (n.IsIndexer) return $"{receiver}[{EmitExpr(n.Args[0])}]";

        if (n.OutParams is { Count: > 0 })
            return EmitOutParamMethodCall(receiver, methodName, n.Args, n.OutParams, n.Type);

        var args = string.Join(", ", n.Args.Select(EmitExpr));
        return $"{receiver}.{methodName}({args})";
    }

    private string EmitWithHandlers(IrNode.WithHandlers n)
    {
        var resultType = TypeToCs(n.Type);
        var needsAsync = ContainsAwait(n.Body) || n.Handlers.Any(h => ContainsAwait(h.HandlerBody));
        var sb = new StringBuilder();
        if (needsAsync)
        {
            // The body or a handler uses `await`. Emitting a sync `Func<T>` lambda
            // would put `await` inside a non-async lambda (CS4034). Emit an
            // `async () => Task<T>` lambda and await it so the awaits run inside
            // the enclosing async method.
            sb.Append(
                $"(await ((System.Func<System.Threading.Tasks.Task<{resultType}>>)(async () => {{ try {{ return {EmitExpr(n.Body)}; }}");
            foreach (var h in n.Handlers)
                if (h.BindingVarName == "_")
                    sb.Append($" catch ({h.ExceptionTypeName}) {{ return {EmitExpr(h.HandlerBody)}; }}");
                else
                    sb.Append(
                        $" catch ({h.ExceptionTypeName} {SanitizeParam(h.BindingVarName)}) {{ return {EmitExpr(h.HandlerBody)}; }}");

            sb.Append(" }))())");
            return sb.ToString();
        }

        sb.Append($"((System.Func<{resultType}>)(() => {{ try {{ return {EmitExpr(n.Body)}; }}");
        foreach (var h in n.Handlers)
            if (h.BindingVarName == "_")
                sb.Append($" catch ({h.ExceptionTypeName}) {{ return {EmitExpr(h.HandlerBody)}; }}");
            else
                sb.Append(
                    $" catch ({h.ExceptionTypeName} {SanitizeParam(h.BindingVarName)}) {{ return {EmitExpr(h.HandlerBody)}; }}");

        sb.Append(" }))()");
        return sb.ToString();
    }

    private void EmitAsyncStatementsBody(IrNode body, bool isVoidReturn)
    {
        switch (body)
        {
            case IrNode.Let let:
            {
                EmitLetStmt(let);
                EmitAsyncStatementsBody(let.Body, isVoidReturn);
                break;
            }
            case IrNode.If @if:
                EmitLine($"if ({EmitExpr(@if.Condition)})");
                EmitLine("{");
                _indent++;
                EmitAsyncStatementsBody(@if.Then, isVoidReturn);
                _indent--;
                EmitLine("}");
                EmitLine("else");
                EmitLine("{");
                _indent++;
                EmitAsyncStatementsBody(@if.Else, isVoidReturn);
                _indent--;
                EmitLine("}");
                break;
            case IrNode.Throw:
                EmitLine($"{EmitExpr(body)};");
                break;
            default:
                if (isVoidReturn)
                    EmitLine($"{EmitExpr(body)};");
                else
                    EmitLine($"return {EmitExpr(body)};");
                break;
        }
    }

    private void EmitLetStmt(IrNode.Let let)
    {
        var valExpr = EmitExpr(let.Value);
        // `_` is the desugared binding name for `begin` side-effect positions
        // (see AstBuilder.BuildBegin). Multiple nested `var _ = ...;` statements
        // would collide with CS0128 ("_ already defined"). Emit a discard
        // assignment instead, which is legal to repeat and carries the same
        // "evaluate and throw away" meaning.
        if (let.VarName == "_")
            EmitLine($"_ = {valExpr};");
        else
        {
            var decl = let.VarType is not null ? TypeToCs(let.VarType) : "var";
            EmitLine($"{decl} {SanitizeParam(let.VarName)} = {valExpr};");
        }
    }

    private void EmitStatementsBody(IrNode body, ZType funcReturnType)
    {
        switch (body)
        {
            case IrNode.Let let:
            {
                EmitLetStmt(let);
                if (let.VarName != "_") _localBindings.Add(let.VarName);
                EmitStatementsBody(let.Body, funcReturnType);
                break;
            }
            case IrNode.Throw:
                EmitLine($"{EmitExpr(body)};");
                break;
            default:
                if (funcReturnType == ZType.Unit)
                    EmitLine($"{EmitExpr(body)};");
                else
                    EmitLine($"return {EmitExpr(body)};");
                break;
        }
    }

    private void EmitTypeDeclarationsInline(IrNode node)
    {
        // When in a module context, type declarations are emitted inside the module class
        if (isModule) return;

        if (node is not IrNode.Seq seq) return;
        foreach (var child in seq.Nodes)
            switch (child)
            {
                case IrNode.RecordDecl rec:
                    Log.Debug("CSharpEmitter: emitting record {RecordName}", rec.Name);
                    EmitLine(EmitRecordDecl(rec));
                    EmitLine();
                    break;
                case IrNode.UnionDecl union:
                    Log.Debug("CSharpEmitter: emitting union {UnionName} with {CaseCount} cases",
                        union.Name, union.Cases.Count);
                    EmitLine(EmitUnionDecl(union));
                    EmitLine();
                    break;
                case IrNode.ClassDecl classDecl:
                    EmitClassDecl(classDecl);
                    EmitLine();
                    break;
                case IrNode.InterfaceDecl ifaceDecl:
                    EmitInterfaceDecl(ifaceDecl);
                    EmitLine();
                    break;
            }
    }

    private string EmitRecordDecl(IrNode.RecordDecl rec)
    {
        var sb = new StringBuilder();
        if (rec.Attributes is { Count: > 0 })
            foreach (var attr in rec.Attributes)
                sb.AppendLine(FormatAttribute(attr));
        var typeParams = rec.TypeParams.Count > 0
            ? $"<{string.Join(", ", rec.TypeParams)}>"
            : "";
        var fields = string.Join(", ",
            rec.Fields.Select(f =>
            {
                var fieldAttrs = FormatFieldAttributes(f.Attributes);
                return $"{fieldAttrs}{TypeToCs(f.Type)} {Sanitize(f.Name)}";
            }));
        var whereClause = FormatWhereConstraints(rec.TypeParamConstraints);
        var header = rec.IsValueType
            ? $"public readonly record struct {Sanitize(rec.Name)}{typeParams}({fields}){whereClause};"
            : $"public sealed record {Sanitize(rec.Name)}{typeParams}({fields}){whereClause};";
        sb.Append(header);
        return sb.ToString();
    }

    private string EmitUnionDecl(IrNode.UnionDecl union)
    {
        var typeParams = union.TypeParams.Count > 0
            ? $"<{string.Join(", ", union.TypeParams)}>"
            : "";
        var sb = new StringBuilder();
        if (union.Attributes is { Count: > 0 })
            foreach (var attr in union.Attributes)
                sb.AppendLine(FormatAttribute(attr));
        var whereClause = FormatWhereConstraints(union.TypeParamConstraints);
        sb.AppendLine($"public abstract record {Sanitize(union.Name)}{typeParams}{whereClause};");
        foreach (var c in union.Cases)
        {
            var fields = c.Fields.Count > 0
                ? $"({string.Join(", ", c.Fields.Select(f => $"{TypeToCs(f.Type)} {Sanitize(f.Name)}"))})"
                : "()";
            sb.AppendLine(
                $"public sealed record {Sanitize(c.Name)}{typeParams}{fields} : {Sanitize(union.Name)}{typeParams}{whereClause};");
            _unionCaseFieldTypes[$"{union.Name}.{c.Name}"] =
                (union.TypeParams, c.Fields.Select(f => f.Type).ToList());
            _caseToUnion[c.Name] = union.Name;
        }

        return sb.ToString();
    }

    private string EmitObjectExpr(IrNode.ObjectExpr n)
    {
        Log.Debug("CSharpEmitter: object expression, {InterfaceCount} interfaces, {MethodCount} methods",
            n.InterfaceNames.Count, n.Methods.Count);
        var objectClassName = $"__Object_{_objectCounter++}";

        // Find captured variables: vars referenced in method bodies AND the
        // explicit constructor's super args / body / field sets that aren't
        // declared locally. Super args and body exprs run inside the anonymous
        // class's constructor, so references to outer-scope names must be
        // captured or else the emitted C# refers to names that don't exist
        // in scope.
        var captured = new List<CapturedVar>();
        foreach (var method in n.Methods)
        {
            var paramNames = new HashSet<string>(method.Params.Select(p => p.Name));
            CollectCapturedVars(method.Body, paramNames, captured);
        }

        if (n.Constructor is { } ctor)
        {
            var ctorScope = new HashSet<string>(ctor.Params.Select(p => p.Name));
            if (ctor.SuperArgs is not null)
                foreach (var arg in ctor.SuperArgs)
                    CollectCapturedVars(arg, ctorScope, captured);
            foreach (var expr in ctor.BodyExprs)
                CollectCapturedVars(expr, ctorScope, captured);
            foreach (var (_, value) in ctor.FieldSets)
                CollectCapturedVars(value, ctorScope, captured);
        }

        // Dedupe by name, keeping the first occurrence's type. A single captured
        // name will consistently have the same type across all reference sites
        // since type inference runs before IR lowering.
        captured = captured
            .GroupBy(c => c.Name)
            .Select(g => g.First())
            .ToList();

        _objectClasses.Add((objectClassName, n, captured));

        if (captured.Count == 0)
            return $"new {objectClassName}()";

        // Route each capture through EmitVar so the outer scope's renames are
        // applied. When this ObjectExpr is nested in another object's ctor,
        // the outer ctor rebinds captured names to `<name>_param`; when it is
        // nested in a class method, a captured field name resolves to
        // `this.<Field>`. Emitting the bare sanitized name would bypass both
        // and produce references to identifiers that don't exist at the call
        // site (Roslyn CS0103).
        var args = string.Join(", ",
            captured.Select(c => EmitExpr(new IrNode.Var(c.Name) { Type = c.Type })));
        return $"new {objectClassName}({args})";
    }

    private void EmitClassDecl(IrNode.ClassDecl classDecl)
    {
        Log.Debug("CSharpEmitter: emitting class declaration {ClassName}", classDecl.Name);
        _currentTypeParams = classDecl.TypeParams.Count > 0
            ? [..classDecl.TypeParams]
            : null;

        if (classDecl.Attributes is { Count: > 0 })
            foreach (var attr in classDecl.Attributes)
                EmitLine(FormatAttribute(attr));

        var typeParams = classDecl.TypeParams.Count > 0
            ? $"<{string.Join(", ", classDecl.TypeParams)}>"
            : "";

        // Build inheritance list: base class first (if any), then interfaces
        var baseList = new List<string>();
        if (classDecl.BaseClassName is not null)
            baseList.Add(Sanitize(classDecl.BaseClassName));
        baseList.AddRange(classDecl.InterfaceNames);
        var inheritance = baseList.Count > 0 ? $" : {string.Join(", ", baseList)}" : "";

        var sealedModifier = classDecl.IsOpen ? "" : "sealed ";
        var whereClause = FormatWhereConstraints(classDecl.TypeParamConstraints);
        EmitLine($"public {sealedModifier}class {Sanitize(classDecl.Name)}{typeParams}{inheritance}{whereClause}");
        EmitLine("{");
        _indent++;

        // Collect inherited fields and method names for override detection
        var inheritedFields = GetEmittedInheritedFields(classDecl.BaseClassName);
        var inheritedMethodNames = GetEmittedInheritedMethodNames(classDecl.BaseClassName);

        // Properties — only own fields, not inherited
        foreach (var field in classDecl.Fields)
        {
            var accessors = field.IsMutable ? "{ get; set; }" : field.IsInit ? "{ get; init; }" : "{ get; }";
            EmitLine($"public {TypeToCs(field.Type)} {Sanitize(field.Name)} {accessors}");
        }

        EmitLine();

        // Constructor
        if (classDecl.Constructor is { } ctor)
        {
            // Explicit constructor
            var ctorParams = string.Join(", ",
                ctor.Params.Select(p => $"{TypeToCs(p.Type)} {SanitizeParam(p.Name)}"));
            var baseCall = ctor.SuperArgs is not null
                ? $" : base({string.Join(", ", ctor.SuperArgs.Select(EmitExpr))})"
                : "";
            EmitLine($"public {Sanitize(classDecl.Name)}({ctorParams}){baseCall}");
            EmitLine("{");
            _indent++;
            foreach (var expr in ctor.BodyExprs)
                EmitLine($"{EmitExpr(expr)};");
            foreach (var (fieldName, value) in ctor.FieldSets)
                EmitLine($"this.{Sanitize(fieldName)} = {EmitExpr(value)};");
            _indent--;
            EmitLine("}");
        }
        else
        {
            // Auto-generated constructor
            var allParams = inheritedFields.Select(f => $"{TypeToCs(f.Type)} {Sanitize(f.Name)}").ToList();
            allParams.AddRange(classDecl.Fields.Select(f => $"{TypeToCs(f.Type)} {Sanitize(f.Name)}"));
            var ctorParams = string.Join(", ", allParams);

            var baseCall = inheritedFields.Count > 0
                ? $" : base({string.Join(", ", inheritedFields.Select(f => Sanitize(f.Name)))})"
                : "";
            EmitLine($"public {Sanitize(classDecl.Name)}({ctorParams}){baseCall}");
            EmitLine("{");
            _indent++;
            foreach (var field in classDecl.Fields)
                EmitLine($"this.{Sanitize(field.Name)} = {Sanitize(field.Name)};");
            _indent--;
            EmitLine("}");
        }

        // Methods
        _currentClassFields = new HashSet<string>(classDecl.Fields.Select(f => f.Name));
        // Include inherited fields so they resolve to this.FieldName
        foreach (var f in inheritedFields)
            _currentClassFields.Add(f.Name);

        foreach (var method in classDecl.Methods)
        {
            EmitLine();
            if (method.Attributes is { Count: > 0 })
                foreach (var attr in method.Attributes)
                    EmitLine(FormatAttribute(attr));
            var retTypeStr = ReturnTypeToCs(method.ReturnType);
            var parms = string.Join(", ",
                method.Params.Select(p => $"{TypeToCs(p.Type)} {SanitizeParam(p.Name)}"));

            // Determine virtual/override modifiers
            var isOverride = inheritedMethodNames.Contains(method.Name);
            var methodModifier = isOverride ? "override " : classDecl.IsOpen ? "virtual " : "";
            var asyncModifier = method.IsAsync ? "async " : "";

            EmitLine($"public {asyncModifier}{methodModifier}{retTypeStr} {Sanitize(method.Name)}({parms})");
            EmitLine("{");
            _indent++;
            if (method.IsAsync && ContainsAwait(method.Body))
                EmitAsyncStatementsBody(method.Body, method.ReturnType == ZType.Unit);
            else if (method.ReturnType == ZType.Unit)
                EmitLine($"{EmitExpr(method.Body)};");
            else
                EmitLine($"return {EmitExpr(method.Body)};");
            _indent--;
            EmitLine("}");
        }

        _currentClassFields = null;

        _indent--;
        EmitLine("}");
        _currentTypeParams = null;

        // Store class info for future subclasses
        _emittedClassInfos[classDecl.Name] = new EmittedClassInfo(
            classDecl.IsOpen,
            classDecl.BaseClassName,
            classDecl.Fields,
            classDecl.Methods.Select(m => m.Name).ToList());
    }

    private string EmitSuperMethodCall(IrNode.SuperMethodCall n)
    {
        var args = string.Join(", ", n.Args.Select(EmitExpr));
        return n.Args.Count > 0
            ? $"base.{Sanitize(n.MethodName)}({args})"
            : $"base.{Sanitize(n.MethodName)}()";
    }

    private void EmitInterfaceDecl(IrNode.InterfaceDecl ifaceDecl)
    {
        Log.Debug("CSharpEmitter: emitting interface {InterfaceName}", ifaceDecl.Name);
        _currentTypeParams = ifaceDecl.TypeParams.Count > 0
            ? new HashSet<string>(ifaceDecl.TypeParams)
            : null;

        if (ifaceDecl.Attributes is { Count: > 0 })
            foreach (var attr in ifaceDecl.Attributes)
                EmitLine(FormatAttribute(attr));

        var typeParams = ifaceDecl.TypeParams.Count > 0
            ? $"<{string.Join(", ", ifaceDecl.TypeParams)}>"
            : "";
        var baseInterfaces = ifaceDecl.BaseInterfaceNames.Count > 0
            ? $" : {string.Join(", ", ifaceDecl.BaseInterfaceNames)}"
            : "";
        var whereClause = FormatWhereConstraints(ifaceDecl.TypeParamConstraints);
        EmitLine($"public interface {Sanitize(ifaceDecl.Name)}{typeParams}{baseInterfaces}{whereClause}");
        EmitLine("{");
        _indent++;

        foreach (var method in ifaceDecl.Methods)
        {
            var retTypeStr = ReturnTypeToCs(method.ReturnType);
            var parms = string.Join(", ",
                method.Params.Select(p => $"{TypeToCs(p.Type)} {SanitizeParam(p.Name)}"));
            EmitLine($"{retTypeStr} {Sanitize(method.Name)}({parms});");
        }

        _indent--;
        EmitLine("}");
        _currentTypeParams = null;
    }

    private void EmitObjectClasses()
    {
        Log.Debug("CSharpEmitter: emitting {ObjectClassCount} object classes", _objectClasses.Count);
        // Index-based iteration: emitting a method body may encounter a nested
        // object-expression, which calls EmitObjectExpr and appends to
        // _objectClasses. Using an index lets the loop pick up those newly
        // added classes in subsequent iterations rather than throwing
        // InvalidOperationException ("Collection was modified") from a
        // foreach enumerator.
        for (var idx = 0; idx < _objectClasses.Count; idx++)
        {
            var (objectClassName, expr, captured) = _objectClasses[idx];
            // Build inheritance list: base class first, then interfaces
            var baseList = new List<string>();
            if (expr.BaseClassName is not null)
                baseList.Add(Sanitize(expr.BaseClassName));
            baseList.AddRange(expr.InterfaceNames);
            var inheritance = string.Join(", ", baseList);
            EmitLine($"private sealed class {objectClassName} : {inheritance}");
            EmitLine("{");
            _indent++;

            // Fields for captured variables
            foreach (var cap in captured)
                EmitLine($"private readonly {TypeToCs(cap.Type)} {Sanitize(cap.Name)}_field;");

            // Determine inherited method names for override detection
            var inheritedMethodNames = GetEmittedInheritedMethodNames(expr.BaseClassName);

            // Constructor
            if (captured.Count > 0 || expr.Constructor is not null)
            {
                var ctorParams = string.Join(", ",
                    captured.Select(c => $"{TypeToCs(c.Type)} {SanitizeParam(c.Name)}_param"));

                // While emitting the constructor, resolve captured names to
                // their ctor parameters — the _field backing has not been
                // assigned until after super(...) and the init statements
                // below, and the parameters are in scope for the whole
                // constructor body.
                var savedObjectCaps = _currentObjectCapturedFields;
                _currentObjectCapturedFields = new Dictionary<string, string>();
                foreach (var cap in captured)
                    _currentObjectCapturedFields[cap.Name] = $"{SanitizeParam(cap.Name)}_param";

                // Build base call from explicit constructor super args or default parameterless
                var baseCall = "";
                if (expr.Constructor?.SuperArgs is { Count: > 0 } superArgs)
                {
                    var superArgsStr = string.Join(", ", superArgs.Select(EmitExpr));
                    baseCall = $" : base({superArgsStr})";
                }
                else if (expr.BaseClassName is not null)
                {
                    baseCall = " : base()";
                }

                EmitLine($"public {objectClassName}({ctorParams}){baseCall}");
                EmitLine("{");
                _indent++;
                foreach (var cap in captured)
                    EmitLine($"this.{Sanitize(cap.Name)}_field = {SanitizeParam(cap.Name)}_param;");
                if (expr.Constructor is { BodyExprs: { Count: > 0 } bodyExprs })
                    foreach (var bodyExpr in bodyExprs)
                        EmitLine($"{EmitExpr(bodyExpr)};");
                _indent--;
                EmitLine("}");

                _currentObjectCapturedFields = savedObjectCaps;
            }
            else if (expr.BaseClassName is not null)
            {
                // No captured vars and no explicit constructor, but has base class — emit parameterless ctor with base()
                EmitLine($"public {objectClassName}() : base()");
                EmitLine("{");
                EmitLine("}");
            }

            // Methods
            _currentObjectCapturedFields = new Dictionary<string, string>();
            foreach (var cap in captured)
                _currentObjectCapturedFields[cap.Name] = $"this.{Sanitize(cap.Name)}_field";

            foreach (var method in expr.Methods)
            {
                var retTypeStr = TypeToCs(method.ReturnType);
                var parms = string.Join(", ",
                    method.Params.Select(p => $"{TypeToCs(p.Type)} {SanitizeParam(p.Name)}"));
                var isOverride = inheritedMethodNames.Contains(method.Name);
                var modifier = isOverride ? "override " : "";
                EmitLine($"public {modifier}{retTypeStr} {Sanitize(method.Name)}({parms})");
                EmitLine("{");
                _indent++;
                EmitLine(method.ReturnType == ZType.Unit
                    ? $"{EmitExpr(method.Body)};"
                    : $"return {EmitExpr(method.Body)};");
                _indent--;
                EmitLine("}");
            }

            _currentObjectCapturedFields = null;

            _indent--;
            EmitLine("}");
            EmitLine();
        }
    }

    private void EmitAttributes(IReadOnlyList<IrAttribute>? attrs)
    {
        if (attrs is null) return;
        foreach (var attr in attrs)
            EmitLine(FormatAttribute(attr));
    }

    private void EmitLine(string line = "")
    {
        if (string.IsNullOrEmpty(line))
        {
            _sb.AppendLine();
        }
        else
        {
            // Handle multiline strings by indenting each line
            var lines = line.Split('\n');
            foreach (var l in lines)
            {
                var trimmed = l.TrimEnd('\r');
                if (string.IsNullOrEmpty(trimmed))
                {
                    _sb.AppendLine();
                }
                else
                {
                    _sb.Append(new string(' ', _indent * 4));
                    _sb.AppendLine(trimmed);
                }
            }
        }
    }
}
