using System.Globalization;
using System.Text;
using ZScheme.Compiler.Ir;
using ZScheme.Compiler.Types;

namespace ZScheme.Compiler.Codegen;

public sealed partial class CSharpEmitter
{
    public string Emit(IrNode node)
    {
        Log.Debug(
            "CSharpEmitter: emitting class {ClassName} in namespace {Namespace}",
            className,
            ns
        );
        Log.Debug(
            "CSharpEmitter: funcMap={FuncMapCount} entries, typeMap={TypeMapCount} entries, importedModules={ImportedModuleCount}, precompiledMap={PrecompiledMapCount}",
            _funcToModuleClass.Count,
            _typeToModuleClass.Count,
            importedModules?.Count ?? 0,
            precompiledModuleMap?.Count ?? 0
        );
        _sb.Clear();
        // Register the current module's collision-renamed type names before any emission so
        // declarations and references (which may forward-reference a type) resolve alike.
        RegisterCurrentTypeEmitNames(node);
        var mainStatements = new List<IrNode>();

        if (!suppressVersionPreamble)
            EmitLine($"// <auto-generated by ZScheme compiler {CompilerInfo.VersionString}>");
        EmitLine("#nullable enable");
        EmitLine();
        if (clrUsings is { Count: > 0 })
        {
            foreach (var usingNs in clrUsings)
                EmitLine($"using {usingNs};");
            EmitLine();
        }

        EmitLine($"namespace {ns};");
        EmitLine();
        EmitTypeDeclarationsInline(node);
        EmitLine();

        if (HasProgramContent(node))
        {
            CollectModuleNames(node);

            EmitLine($"public static class {className}");
            EmitLine("{");
            _indent++;

            if (node is IrNode.Seq seq)
                foreach (var child in seq.Nodes)
                    EmitTopLevel(child, mainStatements);
            else
                EmitTopLevel(node, mainStatements);

            if (mainStatements.Count > 0)
            {
                EmitLine();
                EmitLine($"static {className}()");
                EmitLine("{");
                _indent++;
                foreach (var stmt in mainStatements)
                    EmitLine($"{EmitExpr(stmt)};");
                _indent--;
                EmitLine("}");
            }

            // No entry-point wrapper: the user's `main` is emitted as a normal `public static`
            // method named `Main` (Int -> int, Unit -> void, async -> Task/Task<int>, param
            // -> string[]), which Roslyn discovers as the entry point directly. The signature is
            // guaranteed valid by EntryPointValidator. HasEntryPoint is set during EmitTopLevel.

            _indent--;
            EmitLine("}");
        }

        Log.Debug("CSharpEmitter: emit complete, {OutputLength} chars", _sb.Length);

        // Emit imported module classes (type declarations nested inside, plus functions/values)
        if (importedModules is { Count: > 0 })
            foreach (var (moduleClassName, defs) in importedModules)
            {
                Log.Debug(
                    "CSharpEmitter: processing imported module {ModuleClassName}, {DefCount} definitions",
                    moduleClassName,
                    defs.Count
                );
                var hasContent = defs.Any(d =>
                    d
                        is IrNode.FuncDef
                            or IrNode.Let
                            or IrNode.ClrCall
                            or IrNode.Call
                            or IrNode.Throw
                            or IrNode.Await
                            or IrNode.RecordDecl
                            or IrNode.UnionDecl
                            or IrNode.ClassDecl
                            or IrNode.InterfaceDecl
                );
                if (!hasContent)
                    continue;

                EmitLine();
                EmitLine($"public static class {moduleClassName}");
                EmitLine("{");
                _indent++;

                // Emit type declarations inside the module class
                foreach (var def in defs)
                    switch (def)
                    {
                        case IrNode.RecordDecl rec:
                            EmitLine(EmitRecordDecl(rec));
                            EmitLine();
                            break;
                        case IrNode.UnionDecl union:
                            EmitLine(EmitUnionDecl(union));
                            EmitLine();
                            break;
                        case IrNode.ClassDecl classDecl:
                            EmitClassDecl(classDecl);
                            EmitLine();
                            break;
                        case IrNode.InterfaceDecl ifaceDecl:
                            EmitInterfaceDecl(ifaceDecl);
                            EmitLine();
                            break;
                    }

                var moduleInitStatements = new List<IrNode>();
                foreach (var def in defs)
                    switch (def)
                    {
                        case IrNode.FuncDef func:
                            EmitFuncDef(func);
                            break;
                        case IrNode.Let let:
                            EmitLine(
                                $"public static {TypeToCs(LetVarType(let))} {SanitizeFunc(let.EmitName, let.VarName)} = {EmitExpr(let.Value)};"
                            );
                            if (let.Body is not IrNode.UnitConst)
                                moduleInitStatements.Add(let.Body);
                            break;
                        case IrNode.ClrCall:
                        case IrNode.Call:
                        case IrNode.Throw:
                        case IrNode.Await:
                            moduleInitStatements.Add(def);
                            break;
                    }

                if (moduleInitStatements.Count > 0)
                {
                    EmitLine();
                    EmitLine($"static {moduleClassName}()");
                    EmitLine("{");
                    _indent++;
                    foreach (var stmt in moduleInitStatements)
                        EmitLine($"{EmitExpr(stmt)};");
                    _indent--;
                    EmitLine("}");
                }

                _indent--;
                EmitLine("}");
            }

        return _sb.ToString();
    }

    private void EmitTopLevel(IrNode node, List<IrNode> mainStatements)
    {
        switch (node)
        {
            case IrNode.FuncDef func:
                if (func.Name == "main")
                    HasEntryPoint = true;
                EmitFuncDef(func);
                break;
            case IrNode.RecordDecl rec:
                Log.Debug(
                    "CSharpEmitter: emitting record {RecordName} inside module class",
                    rec.Name
                );
                EmitLine(EmitRecordDecl(rec));
                EmitLine();
                break;
            case IrNode.UnionDecl union:
                Log.Debug(
                    "CSharpEmitter: emitting union {UnionName} inside module class",
                    union.Name
                );
                EmitLine(EmitUnionDecl(union));
                EmitLine();
                break;
            case IrNode.ClassDecl classDecl:
                EmitClassDecl(classDecl);
                EmitLine();
                break;
            case IrNode.InterfaceDecl ifaceDecl:
                EmitInterfaceDecl(ifaceDecl);
                EmitLine();
                break;
            case IrNode.Let let:
                EmitLine(
                    $"public static {TypeToCs(LetVarType(let))} {SanitizeFunc(let.EmitName, let.VarName)} = {EmitExpr(let.Value)};"
                );
                if (let.Body is not IrNode.UnitConst)
                    EmitTopLevel(let.Body, mainStatements);
                break;
            case IrNode.ClrCall:
            case IrNode.Call:
            case IrNode.Throw:
            case IrNode.Await:
                mainStatements.Add(node);
                break;
        }
    }

    private void EmitFuncDef(IrNode.FuncDef func)
    {
        Log.Debug(
            "CSharpEmitter: emitting function {FuncName}, IsAsync={IsAsync}, TypeParams={TypeParamCount}",
            func.Name,
            func.IsAsync,
            func.TypeParams?.Count ?? 0
        );
        var bodyStrategy =
            func.IsSelfRecursive && IsTailRecursive(func.Body, func.Name) ? "TCO"
            : func.IsAsync && ContainsAwait(func.Body) ? "async-statements"
            : !func.IsAsync && WantsStatementForm(func.Body) ? "statements"
            : func.Body is IrNode.Throw ? "throw"
            : "expression";
        Log.Debug(
            "CSharpEmitter: function {FuncName} body strategy: {Strategy}",
            func.Name,
            bodyStrategy
        );
        var prevTypeParams = _currentTypeParams;
        var prevFuncTypeVarMap = _currentFuncTypeVarMap;

        if (func.TypeParams is { Count: > 0 })
        {
            _currentFuncTypeVarMap = BuildTypeVarMap(func);
            _currentTypeParams = new HashSet<string>(func.TypeParams);
        }

        EmitAttributes(func.Attributes);
        var asyncPrefix = func.IsAsync ? "async " : "";
        var retTypeStr = func.IsAsync
            ? func.ReturnType == ZType.Unit
                ? "System.Threading.Tasks.Task"
                : $"System.Threading.Tasks.Task<{TypeToCs(func.ReturnType)}>"
            : ReturnTypeToCs(func.ReturnType);
        var parms = string.Join(", ", func.Params.Select(FormatParam));
        var typeParamStr = func.TypeParams is { Count: > 0 }
            ? $"<{string.Join(", ", func.TypeParams)}>"
            : "";

        var whereClause = FormatWhereConstraints(func.TypeParamConstraints);
        EmitLine(
            $"public static {asyncPrefix}{retTypeStr} {SanitizeFunc(func.EmitName, func.Name)}{typeParamStr}({parms}){whereClause}"
        );
        EmitLine("{");
        _indent++;
        _localBindings.Clear();
        // Parameters are local bindings: they must shadow same-named imported
        // module functions during reference resolution (EmitVarRef), otherwise a
        // parameter like `length` would resolve to an unrelated module export
        // (e.g. concurrent/bag's `length`) that happens to be in scope.
        foreach (var p in func.Params)
            _localBindings.Add(p.Name);
        _localRenames.Clear();
        BeginDeclarationSpace(func.Params);

        if (func.IsSelfRecursive && IsTailRecursive(func.Body, func.Name))
            EmitTailRecursiveLoop(func);
        else if (func.IsAsync && ContainsAwait(func.Body))
            EmitAsyncStatementsBody(func.Body, func.ReturnType == ZType.Unit);
        else if (!func.IsAsync && WantsStatementForm(func.Body))
            // Flatten let-spines and if-with-let-branch bodies into plain locals /
            // if-else blocks instead of emitting an immediately-invoked lambda.
            EmitStatementsBody(func.Body, func.ReturnType);
        else if (
            func.Body is IrNode.Throw
            || (func.IsAsync && func.ReturnType == ZType.Unit)
            || func.ReturnType == ZType.Unit
        )
            EmitUnitStatement(func.Body);
        else
            EmitLine($"return {EmitExpr(func.Body)};");

        _indent--;
        EmitLine("}");
        EmitLine();

        _currentTypeParams = prevTypeParams;
        _currentFuncTypeVarMap = prevFuncTypeVarMap;
    }

    /// True when <paramref name="node"/> in C# statement position must be elided.
    /// The Unit literal `()` lowers to `default(System.ValueTuple)`, a
    /// value-producing expression that is not a legal C# statement (CS0201: "Only
    /// assignment, call, increment, decrement, await, and new object expressions
    /// can be used as a statement"). Evaluating the Unit literal has no side
    /// effects, so it is dropped. Other Unit-typed expressions (e.g. void CLR
    /// calls, `set!`) remain valid statements and are emitted unchanged.
    private static bool IsElidableUnitStatement(IrNode node) => node is IrNode.UnitConst;

    /// True when <paramref name="node"/> emits a C# expression that is itself a
    /// legal statement. CS0201 permits only assignment, call, increment,
    /// decrement, await, and new-object expressions as statements, so a node of
    /// one of these kinds can be emitted bare in statement position even when its
    /// value is discarded. Any other value-producing expression (a literal, var
    /// ref, operator, ternary (`if`), switch (`match`), etc.) must instead be
    /// discarded via `_ = expr;`.
    ///
    /// `Let`/`WithHandlers` lower to an immediately-invoked-lambda form
    /// (`((Func&lt;T&gt;)(…))()`, or `(await (…)())` for the async handler case) — an
    /// invocation/await, hence a legal statement. Conservative in the other
    /// direction: any node not listed falls to the always-valid `_ =` form, which
    /// is sound because every node that emits a genuinely *void*-typed C#
    /// expression (a void call/await/throw, where `_ = …` would itself be illegal)
    /// is listed here and so never reaches the `_ =` branch.
    private static bool IsValidStatementExpr(IrNode node) =>
        node switch
        {
            // A MethodCall is a legal bare statement only when it emits an
            // invocation or an assignment. The property/indexer *get* variants
            // (`IsProperty`/`IsIndexer` with no corresponding `…Set`) emit a bare
            // member- or element-access expression (`receiver.X`, `receiver[i]`),
            // which CS0201 forbids in statement position; those must fall through
            // to the always-legal `_ = …` form in DiscardStatement. The *set*
            // variants emit an assignment and stay valid.
            IrNode.MethodCall mc => !(mc.IsProperty || mc.IsIndexer)
                || mc.IsPropertySet
                || mc.IsIndexerSet,
            IrNode.Call
            or IrNode.ClrCall
            or IrNode.SuperMethodCall
            or IrNode.Await
            or IrNode.SetField
            or IrNode.Throw
            or IrNode.Let
            or IrNode.Use
            or IrNode.WithHandlers => true,
            _ => false,
        };

    private void EmitUnitStatement(IrNode body)
    {
        if (IsElidableUnitStatement(body))
            return;
        // A discarded Unit-typed `if` must be emitted as a statement-form
        // if/else, not the ternary `EmitExpr` produces: a taken branch may be a
        // genuinely void-typed C# expression (a void CLR call wrapped as Unit,
        // e.g. `vector-set!`), which is illegal as a ternary operand (CS0173) and
        // illegal to assign through `_ =` (CS0201). Recursing into
        // EmitUnitStatement discards each branch for effect, the same way the
        // other statement-context emitters (EmitStatementsBody, EmitTcoBody,
        // EmitAsyncStatementsBody) already render `if`. This is the path taken by
        // the `when`/`unless` macros, which desugar to
        // `(if test (begin <side effects>) ())`.
        if (body is IrNode.If @if)
        {
            EmitLine($"if ({EmitExpr(@if.Condition)})");
            EmitLine("{");
            _indent++;
            EmitUnitStatement(@if.Then);
            _indent--;
            EmitLine("}");
            EmitLine("else");
            EmitLine("{");
            _indent++;
            EmitUnitStatement(@if.Else);
            _indent--;
            EmitLine("}");
            return;
        }
        EmitLine(DiscardStatement(body, EmitExpr(body)));
    }

    /// Renders <paramref name="body"/> as a statement to splice inline into a
    /// block lambda body (e.g. `() => { stmt return ...; }`). Returns the empty
    /// string for elidable Unit statements. See <see cref="IsElidableUnitStatement"/>.
    private static string InlineUnitStatement(IrNode body, string emitted) =>
        IsElidableUnitStatement(body) ? "" : $"{emitted}; ";

    /// Renders <paramref name="body"/> as a statement whose value is discarded —
    /// used both for Unit-returning function bodies and for the block body of a
    /// Unit-returning lambda (`(args) => {{ ... }}`). <paramref name="emitted"/> is
    /// the already-rendered C# for <paramref name="body"/>. Returns the empty
    /// string for an elidable Unit literal (the caller omits it).
    ///
    /// CS0201 permits only assignment, call, increment, decrement, await, and
    /// new-object expressions as statements. A node that emits one of those forms
    /// (<see cref="IsValidStatementExpr"/>) is emitted bare; every other
    /// value-producing expression — a literal, var ref, operator, ternary (`if`),
    /// switch (`match`), … — is discarded via `_ = expr;`. This holds even for
    /// Unit-typed expressions: `()` lowers to the *value* `default(System.ValueTuple)`
    /// and `(if c () ())` to a ternary over it, neither of which is a legal bare
    /// statement. Genuinely void-typed emissions (void CLR calls, `await`, `throw`,
    /// `set!`) are all themselves valid statement expressions, so they never reach
    /// the `_ =` branch where assigning void would itself be illegal.
    private static string DiscardStatement(IrNode body, string emitted)
    {
        if (IsElidableUnitStatement(body))
            return "";
        return IsValidStatementExpr(body) ? $"{emitted};" : $"_ = {emitted};";
    }

    private void EmitTailRecursiveLoop(IrNode.FuncDef func)
    {
        EmitLine("while (true)");
        EmitLine("{");
        _indent++;

        EmitTcoBody(func.Body, func.Name, func.Params, func.ReturnType);

        _indent--;
        EmitLine("}");
    }

    private void EmitTcoBody(
        IrNode body,
        string funcName,
        IReadOnlyList<IrParam> parms,
        ZType returnType
    )
    {
        switch (body)
        {
            case IrNode.If @if:
                EmitLine($"if ({EmitExpr(@if.Condition)})");
                EmitLine("{");
                _indent++;
                EmitTcoBody(@if.Then, funcName, parms, returnType);
                _indent--;
                EmitLine("}");
                EmitLine("else");
                EmitLine("{");
                _indent++;
                EmitTcoBody(@if.Else, funcName, parms, returnType);
                _indent--;
                EmitLine("}");
                break;

            case IrNode.Let let:
            {
                var binding = EmitLetStmt(let);
                EmitTcoBody(let.Body, funcName, parms, returnType);
                if (binding is not null)
                    PopLocal(binding.Value);
                break;
            }

            case IrNode.Call { Function: IrNode.Var v } call when v.Name == funcName:
                // Tail recursive call — compute new args, then reassign params, then continue
                for (var i = 0; i < call.Args.Count && i < parms.Count; i++)
                    EmitLine($"var __tmp_{i} = {EmitExpr(call.Args[i])};");
                for (var i = 0; i < call.Args.Count && i < parms.Count; i++)
                    EmitLine($"{SanitizeParam(parms[i].Name)} = __tmp_{i};");
                EmitLine("continue;");
                break;

            case IrNode.Throw:
                EmitLine($"{EmitExpr(body)};");
                break;

            case IrNode.Await:
                if (returnType == ZType.Unit)
                {
                    // Base case of a Unit-returning tail loop: emit the side
                    // effect (if any) then `return;` to exit `while (true)`.
                    // Without the return, control falls through and loops forever.
                    EmitUnitStatement(body);
                    EmitLine("return;");
                }
                else
                    EmitLine($"return {EmitExpr(body)};");
                break;

            default:
                if (returnType == ZType.Unit)
                {
                    EmitUnitStatement(body);
                    EmitLine("return;");
                }
                else
                    EmitLine($"return {EmitExpr(body)};");
                break;
        }
    }

    private string EmitExpr(IrNode node)
    {
        return node switch
        {
            IrNode.IntConst n => FormatIntLiteral(n.Value),
            IrNode.FloatConst n => $"{n.Value.ToString(CultureInfo.InvariantCulture)}f",
            IrNode.BoolConst n => n.Value ? "true" : "false",
            IrNode.StringConst n => $"\"{EscapeString(n.Value)}\"",
            // Intern (not construct) so eq?/reference equality matches the IL backend. Reuse the
            // exact StringConst escaper so the interned name can't diverge between backends.
            IrNode.SymbolConst n => $"ZScheme.Runtime.ZSymbol.Intern(\"{EscapeString(n.Name)}\")",
            IrNode.UnitConst => "default(System.ValueTuple)",
            IrNode.NullConst => "null",
            IrNode.Var n => EmitVar(n),
            IrNode.Let n => EmitLetExpr(n),
            IrNode.Use n => EmitUseExpr(n),
            IrNode.If n => EmitIfExpr(n),
            IrNode.BinOp n => EmitBinOp(n),
            IrNode.UnaryOp n => EmitUnaryOp(n),
            IrNode.Call n => EmitCall(n),
            IrNode.ClrCall n => EmitClrCall(n),
            IrNode.FuncDef n => EmitLambdaExpr(n),
            IrNode.TupleNew n => $"({string.Join(", ", n.Elements.Select(EmitExpr))})",
            IrNode.RecordNew n => EmitRecordNew(n),
            IrNode.RecordWith n => EmitRecordWith(n),
            IrNode.FieldGet n =>
                $"{ParenthesizeReceiver(n.Record, EmitExpr(n.Record))}.{Sanitize(n.FieldName)}",
            IrNode.UnionCaseNew n => EmitUnionCaseNew(n),
            IrNode.Match n => EmitMatch(n),
            IrNode.MutableArrayNew n => EmitMutableArrayNew(n),
            IrNode.TcoJump j => EmitTcoJump(j),
            IrNode.MethodCall n => EmitMethodCall(n),
            IrNode.ClrNew n => EmitClrNew(n),
            IrNode.TypeOf n => $"typeof({TypeToCs(n.TypeArg)})",
            IrNode.Throw n => EmitThrow(n),
            IrNode.WithHandlers n => EmitWithHandlers(n),
            IrNode.Await n => $"await {EmitExpr(n.Expr)}",
            IrNode.SuperMethodCall n => EmitSuperMethodCall(n),
            // No outer parens: `(this.X = expr);` is rejected as a statement
            // by C# (CS0201 — only assignment, call, increment, decrement,
            // await, and new-object expressions can be used as statements),
            // and `set!` is Unit-typed so it commonly lands in statement
            // position (e.g. inside `(begin (set! ...) ...)`). The bare
            // assignment is valid both as a statement and as an expression in
            // the contexts where SetField can appear (function args, ternary
            // arms, lambda bodies — all permit unparenthesized assignment).
            IrNode.SetField n => $"this.{Sanitize(n.FieldName)} = {EmitExpr(n.Value)}",
            _ => ErrorAndReturn(
                $"C# emission not implemented for {node.GetType().Name}",
                "default",
                node.Span
            ),
        };
    }

    private string EmitLetExpr(IrNode.Let n)
    {
        // The value belongs to the enclosing scope, so emit it before the binder is pushed.
        var valExpr = EmitExpr(n.Value);
        var varType = TypeToCs(LetVarType(n));

        // When the value is Unit-typed (e.g. a void CLR call like Console.WriteLine),
        // emit as a block lambda since void expressions can't be passed as arguments.
        // The binder is not declared at all in this shape (the value is a statement),
        // so no local is pushed.
        if (LetVarType(n) is ZType.ZPrimitiveType { Kind: PrimitiveKind.Unit })
        {
            var savedUnitSpace = BeginDeclarationSpace([]);
            var unitBodyExpr = EmitExpr(n.Body);
            EndDeclarationSpace(savedUnitSpace);
            var unitBodyType = TypeToCs(n.Body.Type);

            // When body is also Unit (e.g. chained void calls in begin), both are statements
            if (n.Body.Type is ZType.ZPrimitiveType { Kind: PrimitiveKind.Unit })
                return $"((System.Func<{unitBodyType}>)(() => {{ {InlineUnitStatement(n.Value, valExpr)}{InlineUnitStatement(n.Body, unitBodyExpr)}return default(System.ValueTuple); }}))()";
            return $"((System.Func<{unitBodyType}>)(() => {{ {InlineUnitStatement(n.Value, valExpr)}return {unitBodyExpr}; }}))()";
        }

        // The binding is carried by a lambda parameter, which opens a fresh declaration
        // space: it may legally shadow an enclosing local, so it never needs renaming —
        // but binders inside the body must not redeclare it.
        var savedSpace = BeginDeclarationSpace([]);
        var binding = PushLocal(n.VarName);
        var bodyExpr = EmitExpr(n.Body);
        var bodyType = TypeToCs(n.Body.Type);
        PopLocal(binding);
        EndDeclarationSpace(savedSpace);

        // When body is Unit-typed but the bound variable is not, emit as a block lambda
        // since void expressions can't be used directly as Func<> return values.
        if (n.Body.Type is ZType.ZPrimitiveType { Kind: PrimitiveKind.Unit })
            return $"((System.Func<{varType}, {bodyType}>)(({varType} {binding.EmittedName}) => {{ {InlineUnitStatement(n.Body, bodyExpr)}return default({bodyType}); }}))({valExpr})";

        // Use an immediately invoked lambda for let-in-expression, wrapped in Func<> delegate cast
        return $"((System.Func<{varType}, {bodyType}>)(({varType} {binding.EmittedName}) => {bodyExpr}))({valExpr})";
    }

    /// Emits a `use` in expression position as an immediately-invoked lambda whose
    /// body is a C# `using` block: `((Func<R>)(() => { using (var x = val) { return
    /// body; } }))()`. The native `using` lowers to try/finally that disposes the
    /// resource on every exit path. Mirrors <see cref="EmitWithHandlers"/>, including
    /// the async-lambda variant when the body awaits.
    private string EmitUseExpr(IrNode.Use n)
    {
        var resultType = TypeToCs(n.Type);
        var decl = n.VarType is not null ? TypeToCs(n.VarType) : "var";
        // Emit the resource value before registering the binding — it is not yet in scope.
        var valExpr = EmitExpr(n.Value);

        // The `using` sits inside an IIFE, so its variable lives in that lambda's fresh
        // declaration space and may legally shadow an enclosing local.
        var savedSpace = BeginDeclarationSpace([]);
        var binding = PushLocal(n.VarName);
        var bodyExpr = EmitExpr(n.Body);
        PopLocal(binding);
        EndDeclarationSpace(savedSpace);

        // A Unit-typed body can't be `return`ed (void expressions) — emit it as a
        // statement and return the unit value, matching EmitLetExpr's Unit handling.
        var bodyStmts = n.Body.Type is ZType.ZPrimitiveType { Kind: PrimitiveKind.Unit }
            ? $"{InlineUnitStatement(n.Body, bodyExpr)}return default(System.ValueTuple);"
            : $"return {bodyExpr};";

        var usingBlock = $"using ({decl} {binding.EmittedName} = {valExpr}) {{ {bodyStmts} }}";

        if (ContainsAwait(n.Body))
            return $"(await ((System.Func<System.Threading.Tasks.Task<{resultType}>>)(async () => {{ {usingBlock} }}))())";

        return $"((System.Func<{resultType}>)(() => {{ {usingBlock} }}))()";
    }

    /// Emits a `use` in statement position as a block-scoped C# `using` statement,
    /// recursing the body through <paramref name="emitBody"/> so a nested let/use/if
    /// spine flattens. The bound resource name is registered in <see cref="_localBindings"/>
    /// while the body is emitted so references resolve to it rather than a same-named
    /// module export.
    private void EmitUseStmt(IrNode.Use use, Action<IrNode> emitBody)
    {
        var decl = use.VarType is not null ? TypeToCs(use.VarType) : "var";
        var valExpr = EmitExpr(use.Value);
        var binding = PushLocal(use.VarName);
        EmitLine($"using ({decl} {binding.EmittedName} = {valExpr})");
        EmitLine("{");
        _indent++;
        emitBody(use.Body);
        _indent--;
        EmitLine("}");
        PopLocal(binding);
    }

    private string EmitIfExpr(IrNode.If n)
    {
        var cond = EmitExpr(n.Condition);
        // A Unit-typed `if` in expression position cannot be a C# ternary when a
        // branch is a genuinely void-typed expression (a void CLR call wrapped as
        // Unit, e.g. `vector-set!`): `void` is not a legal ternary operand
        // (CS0173) and the ternary itself is not a legal discarded statement
        // (CS0201). Emit a ValueTuple-returning block lambda that runs the
        // branches in statement form, yielding a real value usable anywhere an
        // expression is expected (a discarded `_ =`, an inline lambda body, a
        // nested ternary, …). Statement contexts emit `if` directly (see
        // EmitUnitStatement / EmitStatementsBody) and never reach this path. This
        // is what makes the `when`/`unless` macros — `(if test (begin …) ())` —
        // compile on the C# backend when the body is a single void call.
        if (n.Type is ZType.ZPrimitiveType { Kind: PrimitiveKind.Unit })
        {
            var thenStmt = InlineUnitStatement(n.Then, EmitExpr(n.Then));
            var elseStmt = InlineUnitStatement(n.Else, EmitExpr(n.Else));
            return $"((System.Func<System.ValueTuple>)(() => {{ if ({cond}) {{ {thenStmt}}} else {{ {elseStmt}}} return default(System.ValueTuple); }}))()";
        }
        var then = EmitExpr(n.Then);
        var @else = EmitExpr(n.Else);
        return $"({cond} ? {then} : {@else})";
    }

    private string EmitBinOp(IrNode.BinOp n)
    {
        var left = EmitExpr(n.Left);
        var right = EmitExpr(n.Right);
        var op = n.Op switch
        {
            "=" => "==",
            "!=" => "!=",
            "and" => "&&",
            "or" => "||",
            _ => n.Op,
        };
        // Integer `/` and `%` of two constant operands cannot be const-folded the
        // way the IL backend's `div`/`rem` opcodes evaluate them: Roslyn folds
        // `int.MinValue / -1` to `int.MinValue`, `int.MinValue % -1` to `0`, and
        // rejects `x / 0` outright as CS0020 — whereas the IL `div`/`rem` opcodes
        // throw OverflowException / DivideByZeroException at runtime. Force a
        // runtime evaluation by making the left operand opaque to the constant
        // folder (`Math.Max(x, x)` is an identity Roslyn won't fold through) so
        // both backends observe the same exception/value.
        if (n.Op is "/" or "%" && IsIntConstExpr(n.Left) && IsIntConstExpr(n.Right))
            return $"(System.Math.Max({left}, {left}) {op} {right})";
        // Other constant arithmetic (`+ - *`, plus float `/` and `%`) is folded by
        // Roslyn at compile time; overflow there becomes CS0220 in the default
        // checked context. ZScheme's semantics are unchecked (matches the IL
        // backend's `add/sub/mul` opcodes and IEEE float div/rem), so wrap
        // constant-only arithmetic in `unchecked(...)` to preserve wrap-around and
        // avoid the compile error without polluting general arithmetic with
        // redundant wrappers.
        if (
            n.Op is "+" or "-" or "*" or "/" or "%"
            && IsConstantExpr(n.Left)
            && IsConstantExpr(n.Right)
        )
            return $"unchecked({left} {op} {right})";
        return $"({left} {op} {right})";
    }

    private static bool IsConstantExpr(IrNode node)
    {
        return node switch
        {
            IrNode.IntConst
            or IrNode.FloatConst
            or IrNode.BoolConst
            or IrNode.StringConst
            or IrNode.SymbolConst
            or IrNode.UnitConst
            or IrNode.NullConst => true,
            IrNode.UnaryOp u => IsConstantExpr(u.Operand),
            IrNode.BinOp b => IsConstantExpr(b.Left) && IsConstantExpr(b.Right),
            // A C# ternary `c ? a : b` is a constant expression when all three
            // parts are constants — Roslyn will then fold it and apply CS0220 to
            // any overflowing arithmetic that reaches it.
            IrNode.If i => IsConstantExpr(i.Condition)
                && IsConstantExpr(i.Then)
                && IsConstantExpr(i.Else),
            _ => false,
        };
    }

    // True when the node is a compile-time-constant expression of integer type —
    // i.e. one whose Roslyn-folded `/` or `%` could diverge from the IL backend's
    // runtime `div`/`rem` opcodes. Mirrors IsConstantExpr but bottoms out only at
    // integer literals so float `/` and `%` (which fold identically to IEEE
    // semantics in both backends) keep the cheaper `unchecked(...)` path.
    private static bool IsIntConstExpr(IrNode node)
    {
        return node switch
        {
            IrNode.IntConst => true,
            IrNode.UnaryOp u when u.Op == "-" => IsIntConstExpr(u.Operand),
            IrNode.BinOp b when b.Op is "+" or "-" or "*" or "/" or "%" => IsIntConstExpr(b.Left)
                && IsIntConstExpr(b.Right),
            IrNode.If i => IsConstantExpr(i.Condition)
                && IsIntConstExpr(i.Then)
                && IsIntConstExpr(i.Else),
            _ => false,
        };
    }

    private string EmitUnaryOp(IrNode.UnaryOp n)
    {
        var operand = EmitExpr(n.Operand);
        var op = n.Op switch
        {
            "not" => "!",
            _ => n.Op,
        };
        // Negation of a constant int can fold at compile time and overflow
        // (`-int.MinValue`); wrap to match the unchecked semantics that the IL
        // backend's `neg` opcode produces.
        if (n.Op == "-" && IsConstantExpr(n.Operand))
            return $"unchecked(-({operand}))";
        return $"({op}({operand}))";
    }

    private string EmitCall(IrNode.Call n)
    {
        var args = string.Join(", ", n.Args.Select(EmitExpr));
        if (n.Function is IrNode.FuncDef lambda)
        {
            // An immediately-invoked lambda has no target type for C# to infer
            // against, so `(() => expr)(...)` fails with CS0149. Cast to a
            // Func<>/Action<> delegate so the invocation type-checks.
            var delegateType = LambdaDelegateType(lambda);
            return $"(({delegateType})({EmitLambdaExpr(lambda)}))({args})";
        }

        var func = EmitExpr(n.Function);

        // Direct calls to a known generic function need explicit type arguments
        // when emission contexts (immediately-invoked lambda casts, ternary arms,
        // etc.) hide the inference targets that Roslyn would otherwise use. The
        // simplest robust fix is to always instantiate generic calls explicitly.
        //
        // A local binding (parameter or let-bound name) shadows a module-scope
        // function of the same name — mirroring EmitVarRef — so an unqualified
        // call to such a binding invokes a delegate value, not the generic
        // function. Emitting `<...>` on a delegate invocation is invalid (CS0307),
        // so skip the generic-instantiation path for shadowed local bindings.
        if (
            n.Function is IrNode.Var v
            && !(v.ModuleName is null && _localBindings.Contains(v.Name))
            && TryLookupGenericFunc(v, out var info)
        )
        {
            var typeArgs = InferCallTypeArgs(info.FuncType, n);
            if (typeArgs is not null)
                return $"{func}<{typeArgs}>({args})";
        }

        return $"{func}({args})";
    }

    private string? InferCallTypeArgs(ZType.ZFuncType funcType, IrNode.Call call)
    {
        var freeVars = Substitution.FreeVars(funcType).OrderBy(id => id).ToList();
        if (freeVars.Count == 0)
            return null;
        var resolved = new ZType?[freeVars.Count];

        for (var i = 0; i < funcType.Params.Count && i < call.Args.Count; i++)
        {
            var actual = call.Args[i].Type;
            // Variadic: the formal final param is the element type T but the
            // actual arg has been packed into Clr-Array<T> by lowering.
            if (
                funcType.IsVariadic
                && i == funcType.Params.Count - 1
                && actual is ZType.ZNamedType { TypeArgs: [var elemType] } named
                && _typeAliases.IsArrayName(named.Name)
            )
                actual = elemType;
            MatchTypeVars(funcType.Params[i], actual, freeVars, resolved);
        }

        // Return type may carry vars not present in any parameter (e.g. zero-arg
        // generic constructors like `concurrent-dictionary/new`).
        MatchTypeVars(funcType.Return, call.Type, freeVars, resolved);

        var rendered = new List<string>(freeVars.Count);
        for (var i = 0; i < freeVars.Count; i++)
        {
            var t = resolved[i];
            if (t is null || IsFreeTypeVar(t))
                rendered.Add("int");
            else
                rendered.Add(TypeToCs(t));
        }

        return string.Join(", ", rendered);
    }

    private static void MatchTypeVars(
        ZType formal,
        ZType actual,
        List<int> freeVarIds,
        ZType?[] result
    )
    {
        switch (formal)
        {
            case ZType.ZTypeVar tv:
            {
                var idx = freeVarIds.IndexOf(tv.Id);
                if (idx >= 0 && result[idx] is null)
                    result[idx] = actual;
                return;
            }
            case ZType.ZConstrainedVar cv:
            {
                var idx = freeVarIds.IndexOf(cv.Id);
                if (idx >= 0 && result[idx] is null)
                    result[idx] = actual;
                return;
            }
            case ZType.ZNamedType fn when actual is ZType.ZNamedType an && fn.Name == an.Name:
            {
                for (var i = 0; i < fn.TypeArgs.Count && i < an.TypeArgs.Count; i++)
                    MatchTypeVars(fn.TypeArgs[i], an.TypeArgs[i], freeVarIds, result);
                return;
            }
            case ZType.ZFuncType ff when actual is ZType.ZFuncType af:
            {
                for (var i = 0; i < ff.Params.Count && i < af.Params.Count; i++)
                    MatchTypeVars(ff.Params[i], af.Params[i], freeVarIds, result);
                MatchTypeVars(ff.Return, af.Return, freeVarIds, result);
                return;
            }
            case ZType.ZNullableType fnn when actual is ZType.ZNullableType ann:
            {
                MatchTypeVars(fnn.Inner, ann.Inner, freeVarIds, result);
                return;
            }
        }
    }

    private string LambdaDelegateType(IrNode.FuncDef lambda)
    {
        if (lambda.ClrDelegateTypeName is not null)
            return lambda.ClrDelegateTypeName;
        var paramTypes = lambda.Params.Select(p => TypeToCs(p.Type)).ToList();
        if (lambda.ReturnType is ZType.ZPrimitiveType { Kind: PrimitiveKind.Unit })
            return paramTypes.Count == 0
                ? "System.Action"
                : $"System.Action<{string.Join(", ", paramTypes)}>";
        paramTypes.Add(TypeToCs(lambda.ReturnType));
        return $"System.Func<{string.Join(", ", paramTypes)}>";
    }

    /// <summary>
    ///     Parses a delegate type name (e.g. "System.Func&lt;int,int&gt;" or "System.Action")
    ///     and returns the parameter types that the delegate's Invoke method expects.
    /// </summary>
    private IReadOnlyList<string> ParseDelegateParameters(string delegateTypeName)
    {
        var genericOpen = delegateTypeName.IndexOf('<');
        if (genericOpen < 0)
            return []; // e.g. "System.Action" or custom non-generic delegate

        var genericClose = delegateTypeName.LastIndexOf('>');
        if (genericClose <= genericOpen)
            return [];

        var inner = delegateTypeName.Substring(genericOpen + 1, genericClose - genericOpen - 1);
        var args = SplitTypeArguments(inner);

        if (delegateTypeName.StartsWith("System.Func"))
        {
            // Last type argument is the return type — all preceding ones are parameters.
            if (args.Count <= 1)
                return [];
            return args.Take(args.Count - 1).ToList();
        }

        if (delegateTypeName.StartsWith("System.Action"))
        {
            // All type arguments are parameters.
            return args;
        }

        // Unknown delegate type — fall back to empty (existing behavior).
        return [];
    }

    private static List<string> SplitTypeArguments(string inner)
    {
        var args = new List<string>();
        var depth = 0;
        var start = 0;
        for (var i = 0; i < inner.Length; i++)
        {
            var c = inner[i];
            if (c == '<')
                depth++;
            else if (c == '>')
                depth--;
            else if (c == ',' && depth == 0)
            {
                args.Add(inner.Substring(start, i - start).Trim());
                start = i + 1;
            }
        }
        args.Add(inner.Substring(start).Trim());
        return args;
    }

    // Resolves a module name (e.g. "stdlib/error") to its emitted C# class name,
    // namespace-qualified when the module came from a precompiled package built under a
    // different namespace (e.g. ZScheme.StdLib.Stdlib_ErrorModule). Source-imported
    // modules share the current compilation's namespace, so they stay unqualified.
    private string QualifiedModuleClass(string moduleName)
    {
        var className = NameConverter.ClassNameFromModuleName(moduleName);
        return
            precompiledModuleNamespaces is not null
            && precompiledModuleNamespaces.TryGetValue(moduleName, out var ns)
            && ns.Length > 0
            ? $"{ns}.{className}"
            : className;
    }

    private string EmitVar(IrNode.Var n)
    {
        var baseRef = EmitVarRef(n);

        // Named-function reference passed to a delegate-typed CLR parameter: wrap it in
        // an adapter lambda cast to the target delegate type. This both selects the
        // correct overload (e.g. RequestDelegate over the minimal-API Delegate overload)
        // and coerces the function value, which is not implicitly convertible. The
        // adapter arity comes from the function's own signature (which matches the
        // delegate's Invoke arity, since that is why this overload was chosen).
        if (n.ClrDelegateTypeName is null)
            return baseRef;

        var arity = n.Type is ZType.ZFuncType ft
            ? ft.Params.Count
            : ParseDelegateParameters(n.ClrDelegateTypeName).Count;
        var argNames = Enumerable.Range(0, arity).Select(i => $"arg{i}").ToList();
        var paramList = string.Join(", ", argNames);
        var callArgs = string.Join(", ", argNames);
        return $"(({n.ClrDelegateTypeName})(({paramList}) => {baseRef}({callArgs})))";
    }

    private string EmitVarRef(IrNode.Var n)
    {
        // Overload-resolved reference: route directly to the named module's
        // class, bypassing the bare-name lookup (which is last-write-wins
        // when multiple imported modules export the same function name).
        if (n.ModuleName is not null)
            return $"{QualifiedModuleClass(n.ModuleName)}.{SanitizeFunc(n.EmitName, n.Name)}";

        // A local binder that had to be renamed to avoid shadowing an enclosing local:
        // resolve in-scope references to the fresh identifier. Only renamed bindings are
        // present, so non-shadowing names fall through unchanged. Placed before
        // field/local lookups so the binding shadows them within its scope, mirroring the
        // language's lexical scoping.
        if (_localRenames.TryGetValue(n.Name, out var renamed))
            return renamed;

        // Local bindings (parameters and let-bound names) shadow class fields and
        // module-scope functions alike. This check must precede both so a local
        // named `length` is not rewritten to an imported `length` function's
        // qualified static reference, and a method parameter or `let` that shares a
        // name with a field of the enclosing class resolves to the local rather than
        // `this.<Field>` — ZScheme's innermost-binding-wins scoping, matching the
        // type inferer and the IL backend.
        if (_localBindings.Contains(n.Name))
            return SanitizeParam(n.Name);

        if (_currentClassFields is not null && _currentClassFields.Contains(n.Name))
            return $"this.{Sanitize(n.Name)}";

        // Self/sibling (and inherited) instance-method calls within the class or
        // object currently being emitted. Without this, the bare method name falls
        // through to the camelCase parameter fallback and emits e.g. `countdown`
        // instead of `this.Countdown` (CS0103).
        if (_currentClassMethods is not null && _currentClassMethods.Contains(n.Name))
            return $"this.{Sanitize(n.Name)}";

        if (_funcToModuleClass.TryGetValue(n.Name, out var modClass))
            return $"{modClass}.{SanitizeFunc(n.EmitName, n.Name)}";

        if (_currentModuleNames.Contains(n.Name))
            return _currentClassFields is not null
                ? $"{className}.{SanitizeFunc(n.EmitName, n.Name)}"
                : SanitizeFunc(n.EmitName, n.Name);

        return SanitizeParam(n.Name);
    }

    private string EmitClrCall(IrNode.ClrCall n)
    {
        Log.Debug(
            "CSharpEmitter: CLR call {TypeName}.{MethodName}, {ArgCount} args, hasOutParams={HasOut}, genericTypeArgs={HasGeneric}",
            n.QualifiedTypeName,
            n.MethodName,
            n.Args.Count,
            n.OutParams is { Count: > 0 },
            n.GenericTypeArgs is { Count: > 0 }
        );
        if (n.OutParams is { Count: > 0 })
            return EmitOutParamStaticCall(
                $"{n.QualifiedTypeName}.{n.MethodName}",
                n.Args,
                n.OutParams,
                n.Type
            );

        var args = string.Join(", ", n.Args.Select(EmitExpr));
        if (n.GenericTypeArgs is { Count: > 0 })
        {
            var typeArgs = string.Join(", ", n.GenericTypeArgs.Select(TypeToCs));
            return $"{n.QualifiedTypeName}.{n.MethodName}<{typeArgs}>({args})";
        }

        return $"{n.QualifiedTypeName}.{n.MethodName}({args})";
    }

    private string EmitClrNew(IrNode.ClrNew n)
    {
        var args = string.Join(", ", n.Args.Select(EmitExpr));
        var typeName = n.QualifiedTypeName;
        if (n.TypeArgs.Count > 0)
        {
            // Prefer the resolved type's type-args (post type-inference, with `^a`
            // annotations replaced by ZTypeVars that can be mapped to the enclosing
            // function's generic parameter names). The AST's literal n.TypeArgs still
            // carries `^a` strings, which would get sanitized to bogus identifiers.
            var typeArgsToEmit =
                n.Type is ZType.ZNamedType { TypeArgs.Count: > 0 } resolved
                && resolved.TypeArgs.Count == n.TypeArgs.Count
                    ? resolved.TypeArgs
                    : n.TypeArgs;
            typeName = $"{typeName}<{string.Join(", ", typeArgsToEmit.Select(TypeToCs))}>";
        }

        return $"new {typeName}({args})";
    }

    private string EmitOutParamMethodCall(
        string receiver,
        string methodName,
        IReadOnlyList<IrNode> visibleArgs,
        IReadOnlyList<ClrInterop.OutParamInfo> outParams,
        ZType returnType
    )
    {
        // Generate: ((System.Func<ReturnType>)(() => {
        //     var __out0 = default(T0); var __out1 = default(T1);
        //     var __ret = receiver.Method(arg0, out __out0, arg1, out __out1);
        //     return (__ret, __out0, __out1);
        // }))()
        var sb = new StringBuilder();
        sb.Append($"((System.Func<{TypeToCs(returnType)}>)(() => {{ ");

        var outParamCsTypes = ResolveOutParamCsTypes(outParams, returnType);
        // Declare out-param locals
        for (var i = 0; i < outParams.Count; i++)
            sb.Append($"{outParamCsTypes[i]} __out{i} = default; ");

        // Build the argument list interleaving visible args and out params
        var fullArgs = BuildOutParamArgList(visibleArgs, outParams);
        sb.Append($"var __ret = {receiver}.{methodName}({fullArgs}); ");
        sb.Append("return (__ret");
        for (var i = 0; i < outParams.Count; i++)
            sb.Append($", __out{i}");
        sb.Append("); }))()");
        return sb.ToString();
    }

    private string EmitOutParamStaticCall(
        string qualifiedCall,
        IReadOnlyList<IrNode> visibleArgs,
        IReadOnlyList<ClrInterop.OutParamInfo> outParams,
        ZType returnType
    )
    {
        var sb = new StringBuilder();
        sb.Append($"((System.Func<{TypeToCs(returnType)}>)(() => {{ ");

        var outParamCsTypes = ResolveOutParamCsTypes(outParams, returnType);
        for (var i = 0; i < outParams.Count; i++)
            sb.Append($"{outParamCsTypes[i]} __out{i} = default; ");

        var fullArgs = BuildOutParamArgList(visibleArgs, outParams);
        sb.Append($"var __ret = {qualifiedCall}({fullArgs}); ");
        sb.Append("return (__ret");
        for (var i = 0; i < outParams.Count; i++)
            sb.Append($", __out{i}");
        sb.Append("); }))()");
        return sb.ToString();
    }

    private string[] ResolveOutParamCsTypes(
        IReadOnlyList<ClrInterop.OutParamInfo> outParams,
        ZType returnType
    )
    {
        // OutParamInfo.ElementType comes from CLR reflection; for generic methods it
        // is the raw open generic parameter (e.g. ZNamedType("T")), which has no
        // mapping in the enclosing function's typeVarMap and would emit as a bogus
        // identifier. The call site's returnType is `(originalReturn, out0, out1, ...)`
        // built from the inferred types — preferring its tuple elements substitutes
        // those generic parameters with concrete or call-site type-vars correctly.
        var result = new string[outParams.Count];
        if (
            returnType is ZType.ZNamedType vt
            && _typeAliases.IsValueTupleName(vt.Name)
            && vt.TypeArgs.Count == outParams.Count + 1
        )
            for (var i = 0; i < outParams.Count; i++)
                result[i] = TypeToCs(vt.TypeArgs[i + 1]);
        else
            for (var i = 0; i < outParams.Count; i++)
                result[i] = TypeToCs(outParams[i].ElementType);
        return result;
    }

    private string EmitThrow(IrNode.Throw n)
    {
        return $"throw {EmitExpr(n.Expr)}";
    }

    private string EmitLambdaExpr(IrNode.FuncDef n)
    {
        Log.Debug(
            "CSharpEmitter: lambda expression, {ParamCount} params, returnType={ReturnType}",
            n.Params.Count,
            n.ReturnType
        );
        // A lambda body is a fresh declaration space: its params may legally shadow the
        // enclosing method's locals, but binders inside the body must not redeclare them.
        var savedSpace = BeginDeclarationSpace([]);
        var bindings = n.Params.Select(p => PushLocal(p.Name)).ToList();
        var body = EmitExpr(n.Body);
        PopLocals(bindings);
        EndDeclarationSpace(savedSpace);

        string parms;
        if (n.ClrDelegateTypeName is not null && n.Params.Count == 0)
        {
            // Lambda has no IR params but the delegate type expects parameters
            // (e.g. (lambda () : Int 42) cast to System.Func<int,int>).
            // Generate dummy parameters matching the delegate's signature so C# accepts it.
            var delegateParams = ParseDelegateParameters(n.ClrDelegateTypeName);
            parms =
                delegateParams.Count > 0
                    ? string.Join(", ", delegateParams.Select((t, i) => $"{t} arg{i}"))
                    : "";
        }
        else
        {
            parms = string.Join(
                ", ",
                n.Params.Select((p, i) => $"{TypeToCs(p.Type)} {bindings[i].EmittedName}")
            );
        }

        var lambdaExpr = n.ReturnType is ZType.ZPrimitiveType { Kind: PrimitiveKind.Unit }
            ? $"(({parms}) => {{ {DiscardStatement(n.Body, body)} }})"
            : $"(({parms}) => {body})";

        if (n.ClrDelegateTypeName is not null)
            return $"(({n.ClrDelegateTypeName}){lambdaExpr})";

        return lambdaExpr;
    }

    private string EmitRecordNew(IrNode.RecordNew n)
    {
        var args = string.Join(
            ", ",
            n.Fields.Select(f => $"{Sanitize(f.FieldName)}: {EmitExpr(f.Value)}")
        );
        // For generic records/structs, emit the closed type args so C# does not require
        // ctor-inference (which our named-args form blocks anyway).
        var typeName = n.Type is ZType.ZNamedType { TypeArgs.Count: > 0 } nt
            ? TypeToCs(nt)
            : QualifyType(n.TypeName);
        return $"new {typeName}({args})";
    }

    private string EmitRecordWith(IrNode.RecordWith n)
    {
        // `(p) with { ... }` does not parse in C# because `(p)` looks like a cast operator.
        // Emit the record expression without wrapping parens and wrap the whole `with`
        // expression so the result composes safely inside larger expressions.
        var setters = string.Join(
            ", ",
            n.Updates.Select(u => $"{Sanitize(u.FieldName)} = {EmitExpr(u.Value)}")
        );
        return $"({EmitExpr(n.Record)} with {{ {setters} }})";
    }

    private string EmitUnionCaseNew(IrNode.UnionCaseNew n)
    {
        // Extract type args from the node's type (the union's named type with type arguments)
        var typeArgStr = "";
        if (n.Type is ZType.ZNamedType { TypeArgs.Count: > 0 } nt)
            typeArgStr = $"<{string.Join(", ", FormatTypeArgs(nt.Name, nt.TypeArgs))}>";

        var args = string.Join(", ", n.Args.Select(EmitExpr));
        return n.Args.Count == 0
            ? $"new {QualifyType(n.CaseName)}{typeArgStr}()"
            : $"new {QualifyType(n.CaseName)}{typeArgStr}({args})";
    }

    private string EmitMatch(IrNode.Match n)
    {
        Log.Debug(
            "CSharpEmitter: emitting match, {ArmCount} arms, scrutinee type={ScrutineeType}",
            n.Arms.Count,
            n.Scrutinee.Type
        );
        var scrutineeType = n.Scrutinee.Type;
        var scrutinee = EmitScrutinee(n.Scrutinee, n.Arms.Select(a => a.Pattern).ToList());

        // Drop unreachable trailing arms so Roslyn doesn't warn:
        //  - arms after any irrefutable pattern (wildcard/variable)
        //  - arms after bool exhaustiveness (both true and false literal patterns seen)
        var usefulArms = PruneUnreachableArms(n.Arms, scrutineeType);

        var sb = new StringBuilder();
        sb.Append($"{scrutinee} switch {{ ");

        foreach (var arm in usefulArms)
        {
            // Scope this arm's pattern bindings: a bound name that shadows an enclosing
            // local is renamed by PushLocal, since C# rejects a switch-expression pattern
            // variable colliding with an in-scope local (CS0136). EmitPattern's
            // declaration site and EmitVarRef's reference site both resolve through
            // `_localRenames`, and the binding is popped after the arm so it stays scoped
            // to it.
            var bindings = arm.Pattern.BoundNames().Select(PushLocal).ToList();

            var body = EmitExpr(arm.Body);
            if (arm.Pattern is IrPattern.Literal { Value: global::ZScheme.Runtime.ZSymbol sym })
            {
                // A ZSymbol literal is not a C# constant, so it can't be a switch pattern. Bind the
                // scrutinee and guard on value equality — evaluated once by the switch, and matching
                // the IL backend's interned-reference comparison.
                var g = $"__sym{_localBindCounter++}";
                sb.Append(
                    $"var {g} when {g} == ZScheme.Runtime.ZSymbol.Intern(\"{EscapeString(sym.Name)}\") => {body}, "
                );
            }
            else
            {
                var pattern = EmitPattern(arm.Pattern, scrutineeType);
                sb.Append($"{pattern} => {body}, ");
            }

            PopLocals(bindings);
        }

        // Only add fallback if the last arm isn't already a catch-all
        // and the arms aren't known to be exhaustive (e.g. bool with both true/false covered).
        var lastPattern = usefulArms[^1].Pattern;
        if (
            lastPattern is not IrPattern.Wildcard and not IrPattern.Variable
            && !IsIrrefutableForType(lastPattern, scrutineeType)
            && !ArmsAreExhaustive(usefulArms, scrutineeType)
        )
            sb.Append(
                "_ => throw new System.InvalidOperationException(\"Non-exhaustive match\"), "
            );
        sb.Append('}');
        return sb.ToString();
    }

    private List<IrMatchArm> PruneUnreachableArms(
        IReadOnlyList<IrMatchArm> arms,
        ZType? scrutineeType
    )
    {
        var isBool = scrutineeType is ZType.ZPrimitiveType { Kind: PrimitiveKind.Bool };
        var sawTrue = false;
        var sawFalse = false;
        // Float literal patterns are compared by IEEE 754 equality, so -0.0 and
        // 0.0 are the *same* pattern. Emitting both to a C# switch expression
        // trips CS8510 ("pattern is unreachable") — see fuzzer seed 0xf0ab7e8f.
        // Drop any float-literal arm whose value equals a prior one under `==`.
        var seenFloats = new List<float>();
        var result = new List<IrMatchArm>(arms.Count);
        foreach (var arm in arms)
        {
            if (arm.Pattern is IrPattern.Literal { Value: float f })
            {
                if (seenFloats.Any(s => s == f))
                    continue;
                seenFloats.Add(f);
            }

            result.Add(arm);
            if (IsIrrefutableForType(arm.Pattern, scrutineeType))
                break;
            if (isBool && arm.Pattern is IrPattern.Literal { Value: bool b })
            {
                if (b)
                    sawTrue = true;
                else
                    sawFalse = true;
                if (sawTrue && sawFalse)
                    break;
            }
        }

        return result;
    }

    private static bool ArmsAreExhaustive(IReadOnlyList<IrMatchArm> arms, ZType? scrutineeType)
    {
        if (scrutineeType is ZType.ZPrimitiveType { Kind: PrimitiveKind.Bool })
        {
            var sawTrue = false;
            var sawFalse = false;
            foreach (var arm in arms)
                if (arm.Pattern is IrPattern.Literal { Value: bool b })
                {
                    if (b)
                        sawTrue = true;
                    else
                        sawFalse = true;
                }

            return sawTrue && sawFalse;
        }

        return false;
    }

    private static bool IsIrrefutablePattern(IrPattern p)
    {
        return p switch
        {
            IrPattern.Wildcard => true,
            IrPattern.Variable => true,
            IrPattern.Tuple t => t.Elements.All(IsIrrefutablePattern),
            _ => false,
        };
    }

    /// <summary>
    ///     Type-aware irrefutability check. A pattern is irrefutable when it must
    ///     match every value of the scrutinee type, in which case Roslyn rejects a
    ///     trailing `_ =>` fallback as CS8510 ("pattern is unreachable"). Beyond the
    ///     always-irrefutable wildcard and variable patterns, this covers:
    ///     * tuple destructuring of `ValueTuple` whose elements are irrefutable
    ///     against the corresponding type argument;
    ///     * constructor patterns over single-case record/struct types whose
    ///     sub-patterns are themselves irrefutable.
    ///     A constructor pattern over a *union case* is never irrefutable — sibling
    ///     cases of the same union remain unmatched, so the fallback is required.
    /// </summary>
    private bool IsIrrefutableForType(IrPattern p, ZType? scrutineeType)
    {
        return p switch
        {
            IrPattern.Wildcard => true,
            IrPattern.Variable => true,
            IrPattern.Tuple t
                when scrutineeType is ZType.ZNamedType tup
                    && _typeAliases.IsValueTupleName(tup.Name)
                    && tup.TypeArgs.Count == t.Elements.Count => t
                .Elements.Zip(tup.TypeArgs)
                .All(pair => IsIrrefutableForType(pair.First, pair.Second)),
            // Without type info, a tuple of irrefutable sub-patterns is still
            // irrefutable (vars/wildcards bind anything).
            IrPattern.Tuple t => t.Elements.All(e => IsIrrefutableForType(e, null)),
            IrPattern.Constructor c
                when scrutineeType is ZType.ZNamedType named
                    && _recordTypeNames.Contains(named.Name)
                    && c.Name == named.Name => c.Fields.All(f => IsIrrefutableForType(f, null)),
            _ => false,
        };
    }

    /// <summary>
    ///     Emits a match scrutinee, widening any sub-expression whose emitted C# type is
    ///     narrower than its declared IR type back up to that type. A union-case
    ///     constructor call emits as `new Some&lt;int&gt;(...)`, which C# types at the case
    ///     subtype rather than the union base, so a pattern testing a sibling case
    ///     (`None&lt;int&gt;`) is provably impossible and Roslyn rejects it with CS8121.
    ///     The cast is only inserted where some arm actually tests a case in that
    ///     position, which keeps the emitted source clean everywhere else.
    ///     <para>
    ///         Tuples are walked element-wise so a union value inside a `values`
    ///         scrutinee is widened just like a direct one; each element is paired with
    ///         the patterns that land in its position.
    ///     </para>
    /// </summary>
    private string EmitScrutinee(IrNode scrutinee, IReadOnlyList<IrPattern> positionPatterns)
    {
        if (scrutinee is IrNode.TupleNew tuple)
        {
            var tuplePatterns = positionPatterns.OfType<IrPattern.Tuple>().ToList();
            var parts = tuple.Elements.Select(
                (element, i) =>
                    EmitScrutinee(
                        element,
                        tuplePatterns
                            .Where(p => i < p.Elements.Count)
                            .Select(p => p.Elements[i])
                            .ToList()
                    )
            );
            return $"({string.Join(", ", parts)})";
        }

        if (
            scrutinee.Type is ZType.ZNamedType named
            && ScrutineeNarrowsBelowIrType(scrutinee)
            && positionPatterns.Any(TestsAUnionCase)
        )
            return $"(({TypeToCs(named)}){EmitExpr(scrutinee)})";

        return EmitExpr(scrutinee);
    }

    /// <summary>
    ///     True if the pattern tests against a union case (or record type) rather than
    ///     just binding or matching a primitive value — i.e. the pattern position needs
    ///     its scrutinee widened to the declared type. See <see cref="EmitScrutinee" />.
    /// </summary>
    private static bool TestsAUnionCase(IrPattern p) => p is IrPattern.Constructor;

    /// <summary>
    ///     True if the scrutinee's emitted C# expression has a narrower C# type than
    ///     its IR `Type`. Today this happens only for <c>UnionCaseNew</c>: the IR type
    ///     is the union base, but the emitted `new CaseName&lt;...&gt;(...)` expression
    ///     types at the case subtype. Variable references, let bindings, calls, and
    ///     other expressions carry the declared IR type in C# already, so no cast is
    ///     needed for them.
    /// </summary>
    private static bool ScrutineeNarrowsBelowIrType(IrNode scrutinee)
    {
        return scrutinee switch
        {
            IrNode.UnionCaseNew => true,
            _ => false,
        };
    }

    private string EmitPattern(IrPattern p, ZType? scrutineeType)
    {
        return p switch
        {
            IrPattern.Wildcard => "_",
            IrPattern.Variable v =>
                $"var {(_localRenames.TryGetValue(v.Name, out var r) ? r : SanitizeParam(v.Name))}",
            IrPattern.Literal { Value: int i } => FormatIntLiteral(i),
            IrPattern.Literal { Value: float f } => $"{f.ToString(CultureInfo.InvariantCulture)}f",
            IrPattern.Literal { Value: bool b } => b ? "true" : "false",
            IrPattern.Literal { Value: string s } => $"\"{EscapeString(s)}\"",
            IrPattern.Tuple t => EmitTuplePattern(t, scrutineeType),
            IrPattern.Constructor c => EmitConstructorPattern(c, scrutineeType),
            _ => WarnAndReturn(
                $"Unsupported pattern type for C# emission: {p.GetType().Name}",
                "_"
            ),
        };
    }

    private string EmitTuplePattern(IrPattern.Tuple t, ZType? scrutineeType)
    {
        var elemTypes =
            scrutineeType is ZType.ZNamedType nt
            && _typeAliases.IsValueTupleName(nt.Name)
            && nt.TypeArgs.Count == t.Elements.Count
                ? nt.TypeArgs
                : null;
        var parts = t.Elements.Select(
            (e, i) => EmitPattern(e, elemTypes is null ? null : elemTypes[i])
        );
        return $"({string.Join(", ", parts)})";
    }

    private string EmitConstructorPattern(IrPattern.Constructor c, ZType? scrutineeType)
    {
        var qualifiedName = ResolveConstructorName(c.Name, scrutineeType);

        if (c.Fields.Count == 0)
            return qualifiedName;

        var fields = string.Join(
            ", ",
            c.Fields.Select(
                (f, i) => EmitPattern(f, ComputeFieldScrutineeType(scrutineeType, c.Name, i))
            )
        );
        return $"{qualifiedName}({fields})";
    }

    // Given the scrutinee ZType a constructor pattern is matching against, return
    // the ZType each field pattern will see. The outer pattern's scrutinee carries
    // the concrete type arguments (e.g., Option<Result<Int, String>>); we look up
    // the union case's field templates (e.g., Some<T0> has field of type T0) and
    // substitute the outer type args to produce the field's concrete type
    // (Result<Int, String>), which nested constructor patterns then use to emit
    // their own generic type arguments.
    private ZType? ComputeFieldScrutineeType(ZType? scrutineeType, string caseName, int fieldIdx)
    {
        // Resolve the case's owning union, preferring the scrutinee's type name.
        var unionName = scrutineeType is ZType.ZNamedType named ? named.Name : null;
        var typeArgs = scrutineeType is ZType.ZNamedType nt ? nt.TypeArgs : [];

        if (unionName is null || !_unionCaseFieldTypes.ContainsKey($"{unionName}.{caseName}"))
            if (_caseToUnion.TryGetValue(caseName, out var foundUnion))
                unionName = foundUnion;

        if (unionName is null)
            return null;
        if (!_unionCaseFieldTypes.TryGetValue($"{unionName}.{caseName}", out var entry))
            return null;
        if (fieldIdx >= entry.FieldTypes.Count)
            return null;

        var fieldTemplate = entry.FieldTypes[fieldIdx];
        if (entry.TypeParams.Count == 0 || typeArgs.Count == 0)
            return fieldTemplate;

        var subst = new Dictionary<string, ZType>();
        for (var i = 0; i < entry.TypeParams.Count && i < typeArgs.Count; i++)
            subst[entry.TypeParams[i]] = typeArgs[i];
        return SubstituteTypeParams(fieldTemplate, subst);
    }

    private static ZType SubstituteTypeParams(ZType type, IReadOnlyDictionary<string, ZType> map)
    {
        return type switch
        {
            ZType.ZNamedType { TypeArgs.Count: 0 } nt
                when map.TryGetValue(nt.Name, out var mapped) => mapped,
            ZType.ZNamedType nt => new ZType.ZNamedType(
                nt.Name,
                nt.TypeArgs.Select(a => SubstituteTypeParams(a, map)).ToList()
            ),
            ZType.ZFuncType ft => new ZType.ZFuncType(
                ft.Params.Select(p => SubstituteTypeParams(p, map)).ToList(),
                SubstituteTypeParams(ft.Return, map),
                ft.IsVariadic
            ),
            ZType.ZNullableType nn => new ZType.ZNullableType(SubstituteTypeParams(nn.Inner, map)),
            _ => type,
        };
    }

    private string EmitMutableArrayNew(IrNode.MutableArrayNew n)
    {
        // For empty arrays, an unresolved type variable element (typically the
        // packed-args array of an empty variadic call like `(list)`) must
        // default to the same concrete type that InferCallTypeArgs picks at
        // the surrounding call site. Otherwise we emit
        // `Foo<int>(System.Array.Empty<object>())`, which Roslyn rejects with
        // a CS1503 conversion error.
        var elemType = n.ElementType;
        var csType = n.Elements.Count == 0 && IsFreeTypeVar(elemType) ? "int" : TypeToCs(elemType);
        if (n.Elements.Count == 0)
            return $"System.Array.Empty<{csType}>()";
        var elems = string.Join(", ", n.Elements.Select(EmitExpr));
        return $"new {csType}[] {{ {elems} }}";
    }

    private string EmitTcoJump(IrNode.TcoJump j)
    {
        // This is used in the tail-recursive loop rewrite
        var sb = new StringBuilder();
        sb.Append("{ ");
        for (var i = 0; i < j.NewArgs.Count; i++)
        {
            var tmpName = $"__tmp_{i}";
            sb.Append($"var {tmpName} = {EmitExpr(j.NewArgs[i])}; ");
        }

        for (var i = 0; i < j.NewArgs.Count; i++)
            sb.Append($"__{SanitizeParam(j.ParamNames[i])} = __tmp_{i}; ");
        sb.Append("continue; }");
        return sb.ToString();
    }

    private string EmitMethodCall(IrNode.MethodCall n)
    {
        Log.Debug(
            "CSharpEmitter: method call .{MethodName}, {ArgCount} args, isProperty={IsProperty}, isIndexer={IsIndexer}",
            n.MethodName,
            n.Args.Count,
            n.IsProperty,
            n.IsIndexer
        );
        var receiver = ParenthesizeReceiver(n.Receiver, EmitExpr(n.Receiver));
        var methodName = Sanitize(n.MethodName);
        if (n.IsPropertySet)
            return $"{receiver}.{n.MethodName} = {EmitExpr(n.Args[0])}";
        if (n.IsProperty)
            return $"{receiver}.{methodName}";
        if (n.IsIndexerSet)
            return $"{receiver}[{EmitExpr(n.Args[0])}] = {EmitExpr(n.Args[1])}";
        if (n.IsIndexer)
            return $"{receiver}[{EmitExpr(n.Args[0])}]";

        if (n.OutParams is { Count: > 0 })
            return EmitOutParamMethodCall(receiver, methodName, n.Args, n.OutParams, n.Type);

        var args = string.Join(", ", n.Args.Select(EmitExpr));
        return $"{receiver}.{methodName}({args})";
    }

    private string EmitWithHandlers(IrNode.WithHandlers n)
    {
        var resultType = TypeToCs(n.Type);
        var needsAsync = ContainsAwait(n.Body) || n.Handlers.Any(h => ContainsAwait(h.HandlerBody));
        var sb = new StringBuilder();

        // The try/catch sits inside an IIFE, whose body is a fresh declaration space:
        // catch variables and body locals may legally shadow the enclosing method's.
        var savedSpace = BeginDeclarationSpace([]);
        try
        {
            if (needsAsync)
            {
                // The body or a handler uses `await`. Emitting a sync `Func<T>` lambda
                // would put `await` inside a non-async lambda (CS4034). Emit an
                // `async () => Task<T>` lambda and await it so the awaits run inside
                // the enclosing async method.
                sb.Append(
                    $"(await ((System.Func<System.Threading.Tasks.Task<{resultType}>>)(async () => {{ try {{ return {EmitExpr(n.Body)}; }}"
                );
                foreach (var h in n.Handlers)
                    sb.Append(EmitCatchClause(h));

                sb.Append(" }))())");
                return sb.ToString();
            }

            sb.Append(
                $"((System.Func<{resultType}>)(() => {{ try {{ return {EmitExpr(n.Body)}; }}"
            );
            foreach (var h in n.Handlers)
                sb.Append(EmitCatchClause(h));

            sb.Append(" }))()");
            return sb.ToString();
        }
        finally
        {
            EndDeclarationSpace(savedSpace);
        }
    }

    /// Emits one `catch (Ex e) { return body; }` clause. The bound exception variable is
    /// pushed while the handler body is emitted, so a name shadowing an enclosing local
    /// is renamed rather than rejected by C# (CS0136).
    private string EmitCatchClause(IrHandlerClause h)
    {
        if (h.BindingVarName == "_")
            return $" catch ({h.ExceptionTypeName}) {{ return {EmitExpr(h.HandlerBody)}; }}";

        var binding = PushLocal(h.BindingVarName);
        var body = EmitExpr(h.HandlerBody);
        PopLocal(binding);
        return $" catch ({h.ExceptionTypeName} {binding.EmittedName}) {{ return {body}; }}";
    }

    /// Emits a <c>with-handlers</c> in statement position as a bare C# try/catch
    /// (each clause body recursed back through <paramref name="emitBody"/> so
    /// nested let/begin/if also flatten) instead of the immediately-invoked
    /// lambda <see cref="EmitWithHandlers"/> produces for expression position.
    /// The bound exception variable is registered in <see cref="_localBindings"/>
    /// while its handler body is emitted so nested references resolve to the
    /// catch variable rather than a same-named module export.
    private void EmitWithHandlersStmt(IrNode.WithHandlers n, Action<IrNode> emitBody)
    {
        EmitLine("try");
        EmitLine("{");
        _indent++;
        emitBody(n.Body);
        _indent--;
        EmitLine("}");
        foreach (var h in n.Handlers)
        {
            LocalBinding? binding = h.BindingVarName == "_" ? null : PushLocal(h.BindingVarName);
            EmitLine(
                binding is null
                    ? $"catch ({h.ExceptionTypeName})"
                    : $"catch ({h.ExceptionTypeName} {binding.Value.EmittedName})"
            );
            EmitLine("{");
            _indent++;
            emitBody(h.HandlerBody);
            _indent--;
            EmitLine("}");
            if (binding is not null)
                PopLocal(binding.Value);
        }
    }

    private void EmitAsyncStatementsBody(IrNode body, bool isVoidReturn)
    {
        switch (body)
        {
            case IrNode.Let let:
            {
                // A discarded (`_`) side-effect binding whose value is itself a
                // statement-form node (use/with-handlers) must be emitted in statement
                // form, not as an expression: an awaiting body in expression position
                // would wrap `await` in a non-async lambda (CS4034) or emit a
                // parenthesized await statement (CS0201). Emit the value for effect
                // (isVoidReturn:true discards its result), then continue the spine.
                LocalBinding? binding = null;
                if (let.VarName == "_" && let.Value is IrNode.Use useVal)
                    EmitUseStmt(useVal, b => EmitAsyncStatementsBody(b, true));
                else if (let.VarName == "_" && let.Value is IrNode.WithHandlers whVal)
                    EmitWithHandlersStmt(whVal, b => EmitAsyncStatementsBody(b, true));
                else
                    binding = EmitLetStmt(let);
                EmitAsyncStatementsBody(let.Body, isVoidReturn);
                if (binding is not null)
                    PopLocal(binding.Value);
                break;
            }
            case IrNode.Use use:
                EmitUseStmt(use, b => EmitAsyncStatementsBody(b, isVoidReturn));
                break;
            case IrNode.If @if:
                EmitLine($"if ({EmitExpr(@if.Condition)})");
                EmitLine("{");
                _indent++;
                EmitAsyncStatementsBody(@if.Then, isVoidReturn);
                _indent--;
                EmitLine("}");
                EmitLine("else");
                EmitLine("{");
                _indent++;
                EmitAsyncStatementsBody(@if.Else, isVoidReturn);
                _indent--;
                EmitLine("}");
                break;
            case IrNode.WithHandlers wh:
                EmitWithHandlersStmt(wh, b => EmitAsyncStatementsBody(b, isVoidReturn));
                break;
            case IrNode.Throw:
                EmitLine($"{EmitExpr(body)};");
                break;
            default:
                if (isVoidReturn)
                    EmitUnitStatement(body);
                else
                    EmitLine($"return {EmitExpr(body)};");
                break;
        }
    }

    /// Emits a `let` as a C# local declaration and returns the binding it introduced,
    /// which the caller must keep open while emitting the let's body and then hand to
    /// <see cref="PopLocal"/>. Returns null for a discarded (`_`) binding, which
    /// declares no local.
    private LocalBinding? EmitLetStmt(IrNode.Let let)
    {
        var valExpr = EmitExpr(let.Value);
        // `_` is the desugared binding name for `begin` side-effect positions
        // (see AstBuilder.BuildBegin). Multiple nested `var _ = ...;` statements
        // would collide with CS0128 ("_ already defined"). Emit a discard
        // assignment instead, which is legal to repeat and carries the same
        // "evaluate and throw away" meaning.
        if (let.VarName == "_")
        {
            // For Unit-typed values (which lower to `void` in C#) we cannot
            // write `_ = voidCall()` — that's CS8209. Emit the call as a
            // statement instead. EmitLetExpr handles the same case for
            // expression position.
            if (LetVarType(let) is ZType.ZPrimitiveType { Kind: PrimitiveKind.Unit })
                EmitUnitStatement(let.Value);
            else
                EmitLine($"_ = {valExpr};");
            return null;
        }

        var binding = PushLocal(let.VarName);
        var decl = let.VarType is not null ? TypeToCs(let.VarType) : "var";
        EmitLine($"{decl} {binding.EmittedName} = {valExpr};");
        return binding;
    }

    private void EmitStatementsBody(IrNode body, ZType funcReturnType)
    {
        switch (body)
        {
            case IrNode.Let let:
            {
                var binding = EmitLetStmt(let);
                EmitStatementsBody(let.Body, funcReturnType);
                if (binding is not null)
                    PopLocal(binding.Value);
                break;
            }
            case IrNode.Use use:
                EmitUseStmt(use, b => EmitStatementsBody(b, funcReturnType));
                break;
            case IrNode.If @if when WantsStatementForm(@if):
                EmitLine($"if ({EmitExpr(@if.Condition)})");
                EmitLine("{");
                _indent++;
                EmitStatementsBody(@if.Then, funcReturnType);
                _indent--;
                EmitLine("}");
                EmitLine("else");
                EmitLine("{");
                _indent++;
                EmitStatementsBody(@if.Else, funcReturnType);
                _indent--;
                EmitLine("}");
                break;
            case IrNode.WithHandlers wh:
                EmitWithHandlersStmt(wh, b => EmitStatementsBody(b, funcReturnType));
                break;
            case IrNode.Throw:
                EmitLine($"{EmitExpr(body)};");
                break;
            default:
                if (funcReturnType == ZType.Unit)
                    EmitUnitStatement(body);
                else
                    EmitLine($"return {EmitExpr(body)};");
                break;
        }
    }

    /// Emits a class/object instance-method body, flattening let-spine and
    /// if-with-let-branch bodies into plain locals / if-else blocks (mirroring
    /// <see cref="EmitFuncDef"/>) instead of an immediately-invoked lambda. Let
    /// bindings introduced by the statement form are scoped to this method —
    /// <see cref="_localBindings"/> is restored afterward so they don't leak into
    /// sibling methods' name resolution.
    private void EmitInstanceMethodBody(
        IrNode body,
        ZType returnType,
        IReadOnlyList<IrParam> methodParams,
        bool isAsync
    )
    {
        var savedLocals = new HashSet<string>(_localBindings);
        // Method parameters occupy C# identifiers that any binder inside the body must
        // not redeclare, so the body's declaration space is seeded with them.
        var savedSpace = BeginDeclarationSpace(methodParams);
        // Parameters are local bindings: they shadow a same-named field of the enclosing
        // class (and any same-named module function) during reference resolution.
        foreach (var p in methodParams)
            _localBindings.Add(p.Name);
        try
        {
            if (isAsync && ContainsAwait(body))
                EmitAsyncStatementsBody(body, returnType == ZType.Unit);
            else if (WantsStatementForm(body))
                EmitStatementsBody(body, returnType);
            else if (returnType == ZType.Unit)
                EmitLine($"{EmitExpr(body)};");
            else
                EmitLine($"return {EmitExpr(body)};");
        }
        finally
        {
            EndDeclarationSpace(savedSpace);
            _localBindings.Clear();
            _localBindings.UnionWith(savedLocals);
        }
    }

    private void EmitTypeDeclarationsInline(IrNode node)
    {
        // When in a module context, type declarations are emitted inside the module class
        if (isModule)
            return;

        if (node is not IrNode.Seq seq)
            return;
        foreach (var child in seq.Nodes)
            switch (child)
            {
                case IrNode.RecordDecl rec:
                    Log.Debug("CSharpEmitter: emitting record {RecordName}", rec.Name);
                    EmitLine(EmitRecordDecl(rec));
                    EmitLine();
                    break;
                case IrNode.UnionDecl union:
                    Log.Debug(
                        "CSharpEmitter: emitting union {UnionName} with {CaseCount} cases",
                        union.Name,
                        union.Cases.Count
                    );
                    EmitLine(EmitUnionDecl(union));
                    EmitLine();
                    break;
                case IrNode.ClassDecl classDecl:
                    EmitClassDecl(classDecl);
                    EmitLine();
                    break;
                case IrNode.InterfaceDecl ifaceDecl:
                    EmitInterfaceDecl(ifaceDecl);
                    EmitLine();
                    break;
            }
    }

    private string EmitRecordDecl(IrNode.RecordDecl rec)
    {
        _recordTypeNames.Add(rec.Name);
        if (rec.TypeParamConstraints is { Count: > 0 })
            _typeParamConstraints[rec.Name] = (rec.TypeParams, rec.TypeParamConstraints);
        var sb = new StringBuilder();
        if (rec.Attributes is { Count: > 0 })
            foreach (var attr in rec.Attributes)
                sb.AppendLine(FormatAttribute(attr));
        var typeParams = rec.TypeParams.Count > 0 ? $"<{string.Join(", ", rec.TypeParams)}>" : "";
        var fields = string.Join(
            ", ",
            rec.Fields.Select(f =>
            {
                var fieldAttrs = FormatFieldAttributes(f.Attributes);
                return $"{fieldAttrs}{TypeToCs(f.Type)} {Sanitize(f.Name)}";
            })
        );
        var whereClause = FormatWhereConstraints(rec.TypeParamConstraints);
        var typeName = SanitizeType(rec.EmitName, rec.Name);
        var header = rec.IsValueType
            ? $"public readonly record struct {typeName}{typeParams}({fields}){whereClause};"
            : $"public sealed record {typeName}{typeParams}({fields}){whereClause};";
        sb.Append(header);
        return sb.ToString();
    }

    private string EmitUnionDecl(IrNode.UnionDecl union)
    {
        if (union.TypeParamConstraints is { Count: > 0 })
            _typeParamConstraints[union.Name] = (union.TypeParams, union.TypeParamConstraints);
        var typeParams =
            union.TypeParams.Count > 0 ? $"<{string.Join(", ", union.TypeParams)}>" : "";
        var sb = new StringBuilder();
        if (union.Attributes is { Count: > 0 })
            foreach (var attr in union.Attributes)
                sb.AppendLine(FormatAttribute(attr));
        var whereClause = FormatWhereConstraints(union.TypeParamConstraints);
        var unionName = SanitizeType(union.EmitName, union.Name);
        sb.AppendLine($"public abstract record {unionName}{typeParams}{whereClause};");
        foreach (var c in union.Cases)
        {
            var fields =
                c.Fields.Count > 0
                    ? $"({string.Join(", ", c.Fields.Select(f => $"{TypeToCs(f.Type)} {Sanitize(f.Name)}"))})"
                    : "()";
            sb.AppendLine(
                $"public sealed record {SanitizeType(c.EmitName, c.Name)}{typeParams}{fields} : {unionName}{typeParams}{whereClause};"
            );
            _unionCaseFieldTypes[$"{union.Name}.{c.Name}"] = (
                union.TypeParams,
                c.Fields.Select(f => f.Type).ToList()
            );
            _caseToUnion[c.Name] = union.Name;
        }

        return sb.ToString();
    }

    private void EmitClassDecl(IrNode.ClassDecl classDecl)
    {
        if (classDecl.TypeParamConstraints is { Count: > 0 })
            _typeParamConstraints[classDecl.Name] = (
                classDecl.TypeParams,
                classDecl.TypeParamConstraints
            );
        Log.Debug("CSharpEmitter: emitting class declaration {ClassName}", classDecl.Name);
        _currentTypeParams = classDecl.TypeParams.Count > 0 ? [.. classDecl.TypeParams] : null;
        // Emitted type name (collision-disambiguated); the constructor name must match it.
        var typeName = SanitizeType(classDecl.EmitName, classDecl.Name);

        if (classDecl.Attributes is { Count: > 0 })
            foreach (var attr in classDecl.Attributes)
                EmitLine(FormatAttribute(attr));

        var typeParams =
            classDecl.TypeParams.Count > 0 ? $"<{string.Join(", ", classDecl.TypeParams)}>" : "";

        // Build inheritance list: base class first (if any), then interfaces
        var baseList = new List<string>();
        if (classDecl.BaseClassName is not null)
            baseList.Add(QualifyType(classDecl.BaseClassName));
        baseList.AddRange(classDecl.InterfaceNames.Select(QualifyType));
        var inheritance = baseList.Count > 0 ? $" : {string.Join(", ", baseList)}" : "";

        var sealedModifier = classDecl.IsOpen ? "" : "sealed ";
        var whereClause = FormatWhereConstraints(classDecl.TypeParamConstraints);
        EmitLine($"public {sealedModifier}class {typeName}{typeParams}{inheritance}{whereClause}");
        EmitLine("{");
        _indent++;

        // Collect inherited fields and method names for override detection
        var inheritedFields = GetEmittedInheritedFields(classDecl.BaseClassName);
        var inheritedMethodNames = GetEmittedInheritedMethodNames(classDecl.BaseClassName);

        // Properties — only own fields, not inherited
        foreach (var field in classDecl.Fields)
        {
            var accessors =
                field.IsMutable ? "{ get; set; }"
                : field.IsInit ? "{ get; init; }"
                : "{ get; }";
            EmitLine($"public {TypeToCs(field.Type)} {Sanitize(field.Name)} {accessors}");
        }

        EmitLine();

        // Constructor
        if (classDecl.Constructor is { } ctor)
        {
            // Explicit constructor
            var ctorParams = string.Join(
                ", ",
                ctor.Params.Select(p => $"{TypeToCs(p.Type)} {SanitizeParam(p.Name)}")
            );
            var baseCall = ctor.SuperArgs is not null
                ? $" : base({string.Join(", ", ctor.SuperArgs.Select(EmitExpr))})"
                : "";
            EmitLine($"public {typeName}({ctorParams}){baseCall}");
            EmitLine("{");
            _indent++;
            var savedCtorSpace = BeginDeclarationSpace(ctor.Params);
            foreach (var expr in ctor.BodyExprs)
                EmitLine($"{EmitExpr(expr)};");
            foreach (var (fieldName, value) in ctor.FieldSets)
                EmitLine($"this.{Sanitize(fieldName)} = {EmitExpr(value)};");
            EndDeclarationSpace(savedCtorSpace);
            _indent--;
            EmitLine("}");
        }
        else
        {
            // Auto-generated constructor
            var allParams = inheritedFields
                .Select(f => $"{TypeToCs(f.Type)} {Sanitize(f.Name)}")
                .ToList();
            allParams.AddRange(
                classDecl.Fields.Select(f => $"{TypeToCs(f.Type)} {Sanitize(f.Name)}")
            );
            var ctorParams = string.Join(", ", allParams);

            var baseCall =
                inheritedFields.Count > 0
                    ? $" : base({string.Join(", ", inheritedFields.Select(f => Sanitize(f.Name)))})"
                    : "";
            EmitLine($"public {typeName}({ctorParams}){baseCall}");
            EmitLine("{");
            _indent++;
            foreach (var field in classDecl.Fields)
                EmitLine($"this.{Sanitize(field.Name)} = {Sanitize(field.Name)};");
            _indent--;
            EmitLine("}");
        }

        // Methods
        _currentClassFields = new HashSet<string>(classDecl.Fields.Select(f => f.Name));
        // Include inherited fields so they resolve to this.FieldName. Skipped for
        // object-lifted classes: an `(object ...)` body does not bring the base
        // class's fields into bare-name scope (TypeInferer.InferObjectExpr), so a
        // bare name that collides with an inherited field is a module-level
        // function reference, not `this.<Field>` (which Roslyn rejects as CS1955
        // when the field is not invocable).
        if (!classDecl.IsObjectLifted)
            foreach (var f in inheritedFields)
                _currentClassFields.Add(f.Name);

        // Track method names (including inherited ones) so self/sibling calls
        // resolve to this.MethodName rather than the bare lowercase identifier.
        _currentClassMethods = new HashSet<string>(classDecl.Methods.Select(m => m.Name));
        foreach (var m in inheritedMethodNames)
            _currentClassMethods.Add(m);

        foreach (var method in classDecl.Methods)
        {
            EmitLine();
            if (method.Attributes is { Count: > 0 })
                foreach (var attr in method.Attributes)
                    EmitLine(FormatAttribute(attr));
            var retTypeStr = ReturnTypeToCs(method.ReturnType);
            var parms = string.Join(
                ", ",
                method.Params.Select(p => $"{TypeToCs(p.Type)} {SanitizeParam(p.Name)}")
            );

            // Determine virtual/override modifiers
            var isOverride = inheritedMethodNames.Contains(method.Name);
            var methodModifier =
                isOverride ? "override "
                : classDecl.IsOpen ? "virtual "
                : "";
            var asyncModifier = method.IsAsync ? "async " : "";

            EmitLine(
                $"public {asyncModifier}{methodModifier}{retTypeStr} {Sanitize(method.Name)}({parms})"
            );
            EmitLine("{");
            _indent++;
            EmitInstanceMethodBody(method.Body, method.ReturnType, method.Params, method.IsAsync);
            _indent--;
            EmitLine("}");
        }

        _currentClassFields = null;
        _currentClassMethods = null;

        _indent--;
        EmitLine("}");
        _currentTypeParams = null;

        // Store class info for future subclasses
        _emittedClassInfos[classDecl.Name] = new EmittedClassInfo(
            classDecl.IsOpen,
            classDecl.BaseClassName,
            classDecl.Fields,
            classDecl.Methods.Select(m => m.Name).ToList()
        );
    }

    private string EmitSuperMethodCall(IrNode.SuperMethodCall n)
    {
        var args = string.Join(", ", n.Args.Select(EmitExpr));
        return n.Args.Count > 0
            ? $"base.{Sanitize(n.MethodName)}({args})"
            : $"base.{Sanitize(n.MethodName)}()";
    }

    private void EmitInterfaceDecl(IrNode.InterfaceDecl ifaceDecl)
    {
        if (ifaceDecl.TypeParamConstraints is { Count: > 0 })
            _typeParamConstraints[ifaceDecl.Name] = (
                ifaceDecl.TypeParams,
                ifaceDecl.TypeParamConstraints
            );
        Log.Debug("CSharpEmitter: emitting interface {InterfaceName}", ifaceDecl.Name);
        _currentTypeParams =
            ifaceDecl.TypeParams.Count > 0 ? new HashSet<string>(ifaceDecl.TypeParams) : null;

        if (ifaceDecl.Attributes is { Count: > 0 })
            foreach (var attr in ifaceDecl.Attributes)
                EmitLine(FormatAttribute(attr));

        var typeParams =
            ifaceDecl.TypeParams.Count > 0 ? $"<{string.Join(", ", ifaceDecl.TypeParams)}>" : "";
        var baseInterfaces =
            ifaceDecl.BaseInterfaceNames.Count > 0
                ? $" : {string.Join(", ", ifaceDecl.BaseInterfaceNames.Select(QualifyType))}"
                : "";
        var whereClause = FormatWhereConstraints(ifaceDecl.TypeParamConstraints);
        EmitLine(
            $"public interface {SanitizeType(ifaceDecl.EmitName, ifaceDecl.Name)}{typeParams}{baseInterfaces}{whereClause}"
        );
        EmitLine("{");
        _indent++;

        foreach (var method in ifaceDecl.Methods)
        {
            var retTypeStr = ReturnTypeToCs(method.ReturnType);
            var parms = string.Join(
                ", ",
                method.Params.Select(p => $"{TypeToCs(p.Type)} {SanitizeParam(p.Name)}")
            );
            EmitLine($"{retTypeStr} {Sanitize(method.Name)}({parms});");
        }

        _indent--;
        EmitLine("}");
        _currentTypeParams = null;
    }

    private void EmitAttributes(IReadOnlyList<IrAttribute>? attrs)
    {
        if (attrs is null)
            return;
        foreach (var attr in attrs)
            EmitLine(FormatAttribute(attr));
    }

    private void EmitLine(string line = "")
    {
        if (string.IsNullOrEmpty(line))
        {
            _sb.AppendLine();
        }
        else
        {
            // Handle multiline strings by indenting each line
            var lines = line.Split('\n');
            foreach (var l in lines)
            {
                var trimmed = l.TrimEnd('\r');
                if (string.IsNullOrEmpty(trimmed))
                {
                    _sb.AppendLine();
                }
                else
                {
                    _sb.Append(new string(' ', _indent * 4));
                    _sb.AppendLine(trimmed);
                }
            }
        }
    }
}
