namespace ZScript.Compiler.Codegen;

using System.Text;
using ZScript.Compiler.Ir;
using ZScript.Compiler.Types;

public sealed class CSharpEmitter
{
    private readonly StringBuilder _sb = new();
    private int _indent;
    private readonly string _namespace;

    public CSharpEmitter(string ns = "ZScriptGenerated")
    {
        _namespace = ns;
    }

    public string Emit(IrNode node)
    {
        _sb.Clear();
        EmitLine("// <auto-generated by ZScript compiler>");
        EmitLine("#nullable enable");
        EmitLine();
        EmitLine($"namespace {_namespace};");
        EmitLine();
        EmitLine("public static class Program");
        EmitLine("{");
        _indent++;

        if (node is IrNode.Seq seq)
        {
            foreach (var child in seq.Nodes)
                EmitTopLevel(child);
        }
        else
        {
            EmitTopLevel(node);
        }

        _indent--;
        EmitLine("}");

        return _sb.ToString();
    }

    private void EmitTopLevel(IrNode node)
    {
        switch (node)
        {
            case IrNode.FuncDef func:
                EmitFuncDef(func);
                break;
            case IrNode.RecordDecl rec:
                // Records are emitted outside the Program class
                break;
            case IrNode.UnionDecl union:
                // Unions are emitted outside the Program class
                break;
            case IrNode.Let let:
                EmitLine($"public static {TypeToCs(let.Value.Type)} {Sanitize(let.VarName)} = {EmitExpr(let.Value)};");
                break;
            default:
                // Expression at top level — wrap in static field or ignore
                break;
        }
    }

    private void EmitFuncDef(IrNode.FuncDef func)
    {
        var retTypeStr = TypeToCs(func.ReturnType);
        var parms = string.Join(", ",
            func.Params.Select(p => $"{TypeToCs(p.Type)} {Sanitize(p.Name)}"));

        EmitLine($"public static {retTypeStr} {Sanitize(func.Name)}({parms})");
        EmitLine("{");
        _indent++;

        if (func.IsSelfRecursive && IsTailRecursive(func.Body, func.Name))
        {
            EmitTailRecursiveLoop(func);
        }
        else
        {
            EmitLine($"return {EmitExpr(func.Body)};");
        }

        _indent--;
        EmitLine("}");
        EmitLine();
    }

    private void EmitTailRecursiveLoop(IrNode.FuncDef func)
    {
        EmitLine("while (true)");
        EmitLine("{");
        _indent++;

        EmitTcoBody(func.Body, func.Name, func.Params);

        _indent--;
        EmitLine("}");
    }

    private void EmitTcoBody(IrNode body, string funcName, IReadOnlyList<IrParam> parms)
    {
        switch (body)
        {
            case IrNode.If @if:
                EmitLine($"if ({EmitExpr(@if.Condition)})");
                EmitLine("{");
                _indent++;
                EmitTcoBody(@if.Then, funcName, parms);
                _indent--;
                EmitLine("}");
                EmitLine("else");
                EmitLine("{");
                _indent++;
                EmitTcoBody(@if.Else, funcName, parms);
                _indent--;
                EmitLine("}");
                break;

            case IrNode.Let let:
                EmitLine($"var {Sanitize(let.VarName)} = {EmitExpr(let.Value)};");
                EmitTcoBody(let.Body, funcName, parms);
                break;

            case IrNode.Call { Function: IrNode.Var v } call when v.Name == funcName:
                // Tail recursive call — compute new args, then reassign params, then continue
                for (int i = 0; i < call.Args.Count && i < parms.Count; i++)
                {
                    EmitLine($"var __tmp_{i} = {EmitExpr(call.Args[i])};");
                }
                for (int i = 0; i < call.Args.Count && i < parms.Count; i++)
                {
                    EmitLine($"{Sanitize(parms[i].Name)} = __tmp_{i};");
                }
                EmitLine("continue;");
                break;

            default:
                EmitLine($"return {EmitExpr(body)};");
                break;
        }
    }

    private string EmitExpr(IrNode node) => node switch
    {
        IrNode.IntConst n => n.Value.ToString(),
        IrNode.FloatConst n => $"{n.Value.ToString(System.Globalization.CultureInfo.InvariantCulture)}f",
        IrNode.BoolConst n => n.Value ? "true" : "false",
        IrNode.StringConst n => $"\"{EscapeString(n.Value)}\"",
        IrNode.UnitConst => "ZScript.Runtime.ZsUnit.Value",
        IrNode.Var n => Sanitize(n.Name),
        IrNode.Let n => EmitLetExpr(n),
        IrNode.If n => EmitIfExpr(n),
        IrNode.BinOp n => EmitBinOp(n),
        IrNode.UnaryOp n => EmitUnaryOp(n),
        IrNode.Call n => EmitCall(n),
        IrNode.FuncDef n => EmitLambdaExpr(n),
        IrNode.RecordNew n => EmitRecordNew(n),
        IrNode.FieldGet n => $"{EmitExpr(n.Record)}.{Sanitize(n.FieldName)}",
        IrNode.UnionCaseNew n => EmitUnionCaseNew(n),
        IrNode.Match n => EmitMatch(n),
        IrNode.ListNew n => EmitListNew(n),
        IrNode.VectorNew n => EmitVectorNew(n),
        IrNode.MapNew n => EmitMapNew(n),
        IrNode.TcoJump j => EmitTcoJump(j),
        _ => "default"
    };

    private string EmitLetExpr(IrNode.Let n)
    {
        // Emit as a block expression using a method-local function
        var valExpr = EmitExpr(n.Value);
        var bodyExpr = EmitExpr(n.Body);
        // Use an immediately invoked lambda for let-in-expression
        return $"(({TypeToCs(n.Value.Type)} {Sanitize(n.VarName)}) => {bodyExpr})({valExpr})";
    }

    private string EmitIfExpr(IrNode.If n)
    {
        var cond = EmitExpr(n.Condition);
        var then = EmitExpr(n.Then);
        var @else = EmitExpr(n.Else);
        return $"({cond} ? {then} : {@else})";
    }

    private string EmitBinOp(IrNode.BinOp n)
    {
        var left = EmitExpr(n.Left);
        var right = EmitExpr(n.Right);
        var op = n.Op switch
        {
            "=" => "==",
            "!=" => "!=",
            "and" => "&&",
            "or" => "||",
            _ => n.Op
        };
        return $"({left} {op} {right})";
    }

    private string EmitUnaryOp(IrNode.UnaryOp n)
    {
        var operand = EmitExpr(n.Operand);
        var op = n.Op switch
        {
            "not" => "!",
            _ => n.Op
        };
        return $"({op}{operand})";
    }

    private string EmitCall(IrNode.Call n)
    {
        var func = EmitExpr(n.Function);
        var args = string.Join(", ", n.Args.Select(EmitExpr));
        return $"{func}({args})";
    }

    private string EmitLambdaExpr(IrNode.FuncDef n)
    {
        var parms = string.Join(", ",
            n.Params.Select(p => $"{TypeToCs(p.Type)} {Sanitize(p.Name)}"));
        var body = EmitExpr(n.Body);
        return $"(({parms}) => {body})";
    }

    private string EmitRecordNew(IrNode.RecordNew n)
    {
        var args = string.Join(", ", n.Fields.Select(f => $"{Sanitize(f.FieldName)}: {EmitExpr(f.Value)}"));
        return $"new {Sanitize(n.TypeName)}({args})";
    }

    private string EmitUnionCaseNew(IrNode.UnionCaseNew n)
    {
        if (n.Args.Count == 0)
            return $"new {Sanitize(n.UnionName)}.{Sanitize(n.CaseName)}()";
        var args = string.Join(", ", n.Args.Select(EmitExpr));
        return $"new {Sanitize(n.UnionName)}.{Sanitize(n.CaseName)}({args})";
    }

    private string EmitMatch(IrNode.Match n)
    {
        var scrutinee = EmitExpr(n.Scrutinee);
        var sb = new StringBuilder();
        sb.Append($"{scrutinee} switch {{ ");

        foreach (var arm in n.Arms)
        {
            var pattern = EmitPattern(arm.Pattern);
            var body = EmitExpr(arm.Body);
            sb.Append($"{pattern} => {body}, ");
        }

        sb.Append("_ => throw new System.InvalidOperationException(\"Non-exhaustive match\") }");
        return sb.ToString();
    }

    private string EmitPattern(IrPattern p) => p switch
    {
        IrPattern.Wildcard => "_",
        IrPattern.Variable v => $"var {Sanitize(v.Name)}",
        IrPattern.Literal { Value: int i } => i.ToString(),
        IrPattern.Literal { Value: float f } =>
            $"{f.ToString(System.Globalization.CultureInfo.InvariantCulture)}f",
        IrPattern.Literal { Value: bool b } => b ? "true" : "false",
        IrPattern.Literal { Value: string s } => $"\"{EscapeString(s)}\"",
        IrPattern.Constructor c => EmitConstructorPattern(c),
        _ => "_"
    };

    private string EmitConstructorPattern(IrPattern.Constructor c)
    {
        if (c.Fields.Count == 0)
            return c.Name;

        var fields = string.Join(", ", c.Fields.Select((f, i) => EmitPattern(f)));
        return $"{c.Name}({fields})";
    }

    private string EmitListNew(IrNode.ListNew n)
    {
        var elems = string.Join(", ", n.Elements.Select(EmitExpr));
        return $"ZScript.Runtime.ZsList.Of({elems})";
    }

    private string EmitVectorNew(IrNode.VectorNew n)
    {
        var elems = string.Join(", ", n.Elements.Select(EmitExpr));
        return $"ZScript.Runtime.ZsVector.Of({elems})";
    }

    private string EmitMapNew(IrNode.MapNew n)
    {
        var entries = string.Join(", ",
            n.Entries.Select(e => $"({EmitExpr(e.Key)}, {EmitExpr(e.Value)})"));
        return $"ZScript.Runtime.ZsMap.Of({entries})";
    }

    private string EmitTcoJump(IrNode.TcoJump j)
    {
        // This is used in the tail-recursive loop rewrite
        var sb = new StringBuilder();
        sb.Append("{ ");
        for (int i = 0; i < j.NewArgs.Count; i++)
        {
            var tmpName = $"__tmp_{i}";
            sb.Append($"var {tmpName} = {EmitExpr(j.NewArgs[i])}; ");
        }
        for (int i = 0; i < j.NewArgs.Count; i++)
        {
            sb.Append($"__{Sanitize(j.ParamNames[i])} = __tmp_{i}; ");
        }
        sb.Append("continue; }");
        return sb.ToString();
    }

    public string EmitTypeDeclarations(IrNode node)
    {
        var sb = new StringBuilder();
        if (node is IrNode.Seq seq)
        {
            foreach (var child in seq.Nodes)
            {
                if (child is IrNode.RecordDecl rec)
                    sb.AppendLine(EmitRecordDecl(rec));
                else if (child is IrNode.UnionDecl union)
                    sb.AppendLine(EmitUnionDecl(union));
            }
        }
        return sb.ToString();
    }

    private string EmitRecordDecl(IrNode.RecordDecl rec)
    {
        var typeParams = rec.TypeParams.Count > 0
            ? $"<{string.Join(", ", rec.TypeParams)}>"
            : "";
        var fields = string.Join(", ",
            rec.Fields.Select(f => $"{TypeToCs(f.Type)} {Sanitize(f.Name)}"));
        return $"public sealed record {Sanitize(rec.Name)}{typeParams}({fields});";
    }

    private string EmitUnionDecl(IrNode.UnionDecl union)
    {
        var typeParams = union.TypeParams.Count > 0
            ? $"<{string.Join(", ", union.TypeParams)}>"
            : "";
        var sb = new StringBuilder();
        sb.AppendLine($"public abstract record {Sanitize(union.Name)}{typeParams};");
        foreach (var c in union.Cases)
        {
            var fields = c.Fields.Count > 0
                ? $"({string.Join(", ", c.Fields.Select(f => $"{TypeToCs(f.Type)} {Sanitize(f.Name)}"))})"
                : "()";
            sb.AppendLine($"public sealed record {Sanitize(c.Name)}{fields} : {Sanitize(union.Name)}{typeParams};");
        }
        return sb.ToString();
    }

    private static string TypeToCs(ZType type) => type switch
    {
        ZType.ZPrimitiveType { Kind: PrimitiveKind.Int } => "int",
        ZType.ZPrimitiveType { Kind: PrimitiveKind.Long } => "long",
        ZType.ZPrimitiveType { Kind: PrimitiveKind.Float } => "float",
        ZType.ZPrimitiveType { Kind: PrimitiveKind.Double } => "double",
        ZType.ZPrimitiveType { Kind: PrimitiveKind.Byte } => "byte",
        ZType.ZPrimitiveType { Kind: PrimitiveKind.Char } => "char",
        ZType.ZPrimitiveType { Kind: PrimitiveKind.Bool } => "bool",
        ZType.ZPrimitiveType { Kind: PrimitiveKind.String } => "string",
        ZType.ZPrimitiveType { Kind: PrimitiveKind.Unit } => "ZScript.Runtime.ZsUnit",
        ZType.ZFuncType ft =>
            $"System.Func<{string.Join(", ", ft.Params.Select(TypeToCs).Append(TypeToCs(ft.Return)))}>",
        ZType.ZNamedType { Name: "List", TypeArgs: [var elem] } =>
            $"ZScript.Runtime.ZsList<{TypeToCs(elem)}>",
        ZType.ZNamedType { Name: "Vector", TypeArgs: [var elem] } =>
            $"ZScript.Runtime.ZsVector<{TypeToCs(elem)}>",
        ZType.ZNamedType { Name: "Map", TypeArgs: [var k, var v] } =>
            $"ZScript.Runtime.ZsMap<{TypeToCs(k)}, {TypeToCs(v)}>",
        ZType.ZNamedType { Name: "Option", TypeArgs: [var t] } =>
            $"ZScript.Runtime.ZsOption<{TypeToCs(t)}>",
        ZType.ZNamedType { Name: "Result", TypeArgs: [var t, var e] } =>
            $"ZScript.Runtime.ZsResult<{TypeToCs(t)}, {TypeToCs(e)}>",
        ZType.ZNamedType nt when nt.TypeArgs.Count > 0 =>
            $"{Sanitize(nt.Name)}<{string.Join(", ", nt.TypeArgs.Select(TypeToCs))}>",
        ZType.ZNamedType nt => Sanitize(nt.Name),
        ZType.ZTypeVar tv => "object", // fallback for unresolved type vars
        _ => "object"
    };

    private static string Sanitize(string name)
    {
        // Replace characters invalid in C# identifiers
        return name.Replace("-", "_").Replace("/", "_").Replace("?", "_q").Replace(">", "_gt").Replace("|", "_pipe");
    }

    private static string EscapeString(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r").Replace("\t", "\\t");

    private void EmitLine(string line = "")
    {
        if (string.IsNullOrEmpty(line))
        {
            _sb.AppendLine();
        }
        else
        {
            _sb.Append(new string(' ', _indent * 4));
            _sb.AppendLine(line);
        }
    }

    // --- Tail Call Optimization helpers ---

    private static bool IsTailRecursive(IrNode body, string funcName) => body switch
    {
        IrNode.If @if =>
            IsTailRecursive(@if.Then, funcName) || IsTailRecursive(@if.Else, funcName),
        IrNode.Let let => IsTailRecursive(let.Body, funcName),
        IrNode.Call { Function: IrNode.Var v } when v.Name == funcName => true,
        IrNode.BinOp { Op: var op, Left: IrNode.Call { Function: IrNode.Var v } }
            when v.Name == funcName => false, // not tail if result is used in binop
        _ => false
    };

    private IrNode RewriteTailCalls(IrNode body, string funcName, IReadOnlyList<IrParam> parms) =>
        body switch
        {
            IrNode.If @if => new IrNode.If(
                @if.Condition,
                RewriteTailCalls(@if.Then, funcName, parms),
                RewriteTailCalls(@if.Else, funcName, parms))
            { Type = @if.Type },
            IrNode.Let let => new IrNode.Let(
                let.VarName, let.Value,
                RewriteTailCalls(let.Body, funcName, parms))
            { Type = let.Type },
            IrNode.Call { Function: IrNode.Var v } call when v.Name == funcName =>
                new IrNode.TcoJump(parms.Select(p => p.Name).ToList(), call.Args.ToList())
                { Type = call.Type },
            _ => body
        };
}
