namespace ZScript.Compiler.Codegen;

using System.Text;
using ZScript.Compiler.Ir;
using ZScript.Compiler.Types;

public sealed class CSharpEmitter(string ns = "ZScriptGenerated", string className = "Program", IReadOnlyList<string>? clrUsings = null, IReadOnlyList<(string ClassName, IReadOnlyList<IrNode> Definitions)>? importedModules = null)
{
    private readonly StringBuilder _sb = new();
    private int _indent;
    private int _propagateCounter;
    private int _objectCounter;
    private readonly List<(string ClassName, IrNode.ObjectExpr Expr, List<string> CapturedVars)> _objectClasses = [];
    private HashSet<string>? _currentClassFields;
    private HashSet<string>? _currentClassLocals;
    private HashSet<string>? _currentTypeParams;
    private readonly List<(string ClassName, IrNode.ClassDecl Decl)> _classStaticWrappers = [];
    private readonly Dictionary<string, string> _funcToModuleClass = BuildFuncToModuleMap(importedModules);
    private IrNode.FuncDef? _userMainFunc;

    private static readonly HashSet<string> BuiltinCtorNames = ["Ok", "Err", "Some", "None"];

    private static Dictionary<string, string> BuildFuncToModuleMap(
        IReadOnlyList<(string ClassName, IReadOnlyList<IrNode> Definitions)>? modules)
    {
        var map = new Dictionary<string, string>();
        if (modules is null) return map;
        foreach (var (moduleClassName, defs) in modules)
        {
            foreach (var def in defs)
            {
                var name = def switch
                {
                    IrNode.FuncDef f => f.Name,
                    IrNode.Let l => l.VarName,
                    _ => null
                };
                if (name is not null)
                    map[name] = moduleClassName;
            }
        }
        return map;
    }

    public string Emit(IrNode node)
    {
        _sb.Clear();
        var mainStatements = new List<IrNode>();

        EmitLine("// <auto-generated by ZScript compiler>");
        EmitLine("#nullable enable");
        EmitLine();
        if (clrUsings is { Count: > 0 })
        {
            foreach (var usingNs in clrUsings)
                EmitLine($"using {usingNs};");
            EmitLine();
        }
        EmitLine($"namespace {ns};");
        EmitLine();
        EmitTypeDeclarationsInline(node);
        EmitLine($"public static class {className}");
        EmitLine("{");
        _indent++;

        if (node is IrNode.Seq seq)
        {
            foreach (var child in seq.Nodes)
                EmitTopLevel(child, mainStatements);
        }
        else
        {
            EmitTopLevel(node, mainStatements);
        }

        if (mainStatements.Count > 0)
        {
            EmitLine();
            EmitLine($"static {className}()");
            EmitLine("{");
            _indent++;
            foreach (var stmt in mainStatements)
                EmitLine($"{EmitExpr(stmt)};");
            _indent--;
            EmitLine("}");
        }

        if (_userMainFunc is not null)
        {
            EmitLine();
            EmitLine("public static int Main(string[] args)");
            EmitLine("{");
            _indent++;
            EmitLine("return main(ZScript.Runtime.ZsList<string>.FromItems(args));");
            _indent--;
            EmitLine("}");
        }

        // Emit nested classes for object expressions
        if (_objectClasses.Count > 0)
        {
            EmitLine();
            EmitObjectClasses();
        }

        _indent--;
        EmitLine("}");

        // Emit imported module classes
        if (importedModules is { Count: > 0 })
        {
            foreach (var (moduleClassName, defs) in importedModules)
            {
                EmitLine();
                EmitLine($"public static class {moduleClassName}");
                EmitLine("{");
                _indent++;
                var moduleInitStatements = new List<IrNode>();
                foreach (var def in defs)
                {
                    switch (def)
                    {
                        case IrNode.FuncDef func:
                            EmitFuncDef(func);
                            break;
                        case IrNode.Let let:
                            EmitLine($"public static {TypeToCs(let.Value.Type)} {Sanitize(let.VarName)} = {EmitExpr(let.Value)};");
                            if (let.Body is not IrNode.UnitConst)
                                moduleInitStatements.Add(let.Body);
                            break;
                        case IrNode.ClrCall:
                        case IrNode.Call:
                        case IrNode.Throw:
                        case IrNode.Await:
                            moduleInitStatements.Add(def);
                            break;
                    }
                }
                if (moduleInitStatements.Count > 0)
                {
                    EmitLine();
                    EmitLine($"static {moduleClassName}()");
                    EmitLine("{");
                    _indent++;
                    foreach (var stmt in moduleInitStatements)
                        EmitLine($"{EmitExpr(stmt)};");
                    _indent--;
                    EmitLine("}");
                }
                _indent--;
                EmitLine("}");
            }
        }

        return _sb.ToString();
    }

    private void EmitTopLevel(IrNode node, List<IrNode> mainStatements)
    {
        switch (node)
        {
            case IrNode.FuncDef func:
                if (func.Name == "main")
                    _userMainFunc = func;
                EmitFuncDef(func);
                break;
            case IrNode.RecordDecl rec:
                // Records are emitted outside the Program class
                break;
            case IrNode.UnionDecl union:
                // Unions are emitted outside the Program class
                break;
            case IrNode.ClassDecl classDecl:
                // Class is emitted outside the Program class; emit static wrappers here
                EmitClassStaticWrappers(classDecl);
                break;
            case IrNode.InterfaceDecl ifaceDecl:
                // Interface is emitted outside the Program class; emit static wrappers here
                EmitInterfaceStaticWrappers(ifaceDecl);
                break;
            case IrNode.Let let:
                EmitLine($"public static {TypeToCs(let.Value.Type)} {Sanitize(let.VarName)} = {EmitExpr(let.Value)};");
                if (let.Body is not IrNode.UnitConst)
                    EmitTopLevel(let.Body, mainStatements);
                break;
            case IrNode.ClrCall:
            case IrNode.Call:
            case IrNode.Throw:
            case IrNode.Await:
                mainStatements.Add(node);
                break;
        }
    }

    private void EmitFuncDef(IrNode.FuncDef func)
    {
        EmitAttributes(func.Attributes);
        var asyncPrefix = func.IsAsync ? "async " : "";
        var retTypeStr = func.IsAsync
            ? (func.ReturnType == ZType.Unit
                ? "System.Threading.Tasks.Task"
                : $"System.Threading.Tasks.Task<{TypeToCs(func.ReturnType)}>")
            : ReturnTypeToCs(func.ReturnType);
        var parms = string.Join(", ",
            func.Params.Select(FormatParam));

        EmitLine($"public static {asyncPrefix}{retTypeStr} {Sanitize(func.Name)}({parms})");
        EmitLine("{");
        _indent++;

        if (func.IsSelfRecursive && IsTailRecursive(func.Body, func.Name))
        {
            EmitTailRecursiveLoop(func);
        }
        else if (ContainsPropagate(func.Body))
        {
            EmitStatementsBody(func.Body, func.ReturnType);
        }
        else if (func.IsAsync && ContainsAwait(func.Body))
        {
            EmitAsyncStatementsBody(func.Body, func.ReturnType == ZType.Unit);
        }
        else if (func.Body is IrNode.Throw)
        {
            EmitLine($"{EmitExpr(func.Body)};");
        }
        else if (func.IsAsync && func.ReturnType == ZType.Unit)
        {
            EmitLine($"{EmitExpr(func.Body)};");
        }
        else if (func.ReturnType == ZType.Unit)
        {
            EmitLine($"{EmitExpr(func.Body)};");
        }
        else
        {
            EmitLine($"return {EmitExpr(func.Body)};");
        }

        _indent--;
        EmitLine("}");
        EmitLine();
    }

    private void EmitTailRecursiveLoop(IrNode.FuncDef func)
    {
        EmitLine("while (true)");
        EmitLine("{");
        _indent++;

        EmitTcoBody(func.Body, func.Name, func.Params, func.ReturnType);

        _indent--;
        EmitLine("}");
    }

    private void EmitTcoBody(IrNode body, string funcName, IReadOnlyList<IrParam> parms, ZType returnType)
    {
        switch (body)
        {
            case IrNode.If @if:
                EmitLine($"if ({EmitExpr(@if.Condition)})");
                EmitLine("{");
                _indent++;
                EmitTcoBody(@if.Then, funcName, parms, returnType);
                _indent--;
                EmitLine("}");
                EmitLine("else");
                EmitLine("{");
                _indent++;
                EmitTcoBody(@if.Else, funcName, parms, returnType);
                _indent--;
                EmitLine("}");
                break;

            case IrNode.Let let:
                EmitLine($"var {Sanitize(let.VarName)} = {EmitExpr(let.Value)};");
                EmitTcoBody(let.Body, funcName, parms, returnType);
                break;

            case IrNode.Call { Function: IrNode.Var v } call when v.Name == funcName:
                // Tail recursive call — compute new args, then reassign params, then continue
                for (int i = 0; i < call.Args.Count && i < parms.Count; i++)
                {
                    EmitLine($"var __tmp_{i} = {EmitExpr(call.Args[i])};");
                }
                for (int i = 0; i < call.Args.Count && i < parms.Count; i++)
                {
                    EmitLine($"{Sanitize(parms[i].Name)} = __tmp_{i};");
                }
                EmitLine("continue;");
                break;

            case IrNode.Throw:
                EmitLine($"{EmitExpr(body)};");
                break;

            case IrNode.Await:
                if (returnType == ZType.Unit)
                    EmitLine($"{EmitExpr(body)};");
                else
                    EmitLine($"return {EmitExpr(body)};");
                break;

            default:
                if (returnType == ZType.Unit)
                    EmitLine($"{EmitExpr(body)};");
                else
                    EmitLine($"return {EmitExpr(body)};");
                break;
        }
    }

    private string EmitExpr(IrNode node) => node switch
    {
        IrNode.IntConst n => n.Value.ToString(),
        IrNode.FloatConst n => $"{n.Value.ToString(System.Globalization.CultureInfo.InvariantCulture)}f",
        IrNode.BoolConst n => n.Value ? "true" : "false",
        IrNode.StringConst n => $"\"{EscapeString(n.Value)}\"",
        IrNode.UnitConst => "ZScript.Runtime.ZsUnit.Value",
        IrNode.Var n => EmitVar(n),
        IrNode.Let n => EmitLetExpr(n),
        IrNode.If n => EmitIfExpr(n),
        IrNode.BinOp n => EmitBinOp(n),
        IrNode.UnaryOp n => EmitUnaryOp(n),
        IrNode.Call n => EmitCall(n),
        IrNode.ClrCall n => EmitClrCall(n),
        IrNode.FuncDef n => EmitLambdaExpr(n),
        IrNode.RecordNew n => EmitRecordNew(n),
        IrNode.FieldGet n => $"{EmitExpr(n.Record)}.{Sanitize(n.FieldName)}",
        IrNode.UnionCaseNew n => EmitUnionCaseNew(n),
        IrNode.Match n => EmitMatch(n),
        IrNode.ListNew n => EmitListNew(n),
        IrNode.VectorNew n => EmitVectorNew(n),
        IrNode.MapNew n => EmitMapNew(n),
        IrNode.TcoJump j => EmitTcoJump(j),
        IrNode.BuiltinCtorCall n => EmitBuiltinCtorCall(n),
        IrNode.TryCatch n => EmitTryCatch(n),
        IrNode.MethodCall n => EmitMethodCall(n),
        IrNode.ObjectExpr n => EmitObjectExpr(n),
        IrNode.ClrNew n => EmitClrNew(n),
        IrNode.Throw n => EmitThrow(n),
        IrNode.Await n => $"await {EmitExpr(n.Expr)}",
        _ => "default"
    };

    private string EmitLetExpr(IrNode.Let n)
    {
        // Emit as a block expression using a method-local function
        var valExpr = EmitExpr(n.Value);
        var bodyExpr = EmitExpr(n.Body);
        // Use an immediately invoked lambda for let-in-expression, wrapped in Func<> delegate cast
        return $"((System.Func<{TypeToCs(n.Value.Type)}, {TypeToCs(n.Body.Type)}>)(({TypeToCs(n.Value.Type)} {Sanitize(n.VarName)}) => {bodyExpr}))({valExpr})";
    }

    private string EmitIfExpr(IrNode.If n)
    {
        var cond = EmitExpr(n.Condition);
        var then = EmitExpr(n.Then);
        var @else = EmitExpr(n.Else);
        return $"({cond} ? {then} : {@else})";
    }

    private string EmitBinOp(IrNode.BinOp n)
    {
        var left = EmitExpr(n.Left);
        var right = EmitExpr(n.Right);
        var op = n.Op switch
        {
            "=" => "==",
            "!=" => "!=",
            "and" => "&&",
            "or" => "||",
            _ => n.Op
        };
        return $"({left} {op} {right})";
    }

    private string EmitUnaryOp(IrNode.UnaryOp n)
    {
        var operand = EmitExpr(n.Operand);
        var op = n.Op switch
        {
            "not" => "!",
            _ => n.Op
        };
        return $"({op}{operand})";
    }

    private string EmitCall(IrNode.Call n)
    {
        var func = EmitExpr(n.Function);
        var args = string.Join(", ", n.Args.Select(EmitExpr));
        return $"{func}({args})";
    }

    private string EmitVar(IrNode.Var n)
    {
        if (_currentClassFields is not null)
        {
            if (_currentClassFields.Contains(n.Name))
                return $"this.{Sanitize(n.Name)}";
            if (_currentClassLocals is null || !_currentClassLocals.Contains(n.Name))
            {
                var qualifyingClass = _funcToModuleClass.TryGetValue(n.Name, out var moduleClass)
                    ? moduleClass
                    : className;
                return $"{qualifyingClass}.{Sanitize(n.Name)}";
            }
        }
        if (_funcToModuleClass.TryGetValue(n.Name, out var modClass))
            return $"{modClass}.{Sanitize(n.Name)}";
        return Sanitize(n.Name);
    }

    private string EmitClrCall(IrNode.ClrCall n)
    {
        var args = string.Join(", ", n.Args.Select(EmitExpr));
        return $"{n.QualifiedTypeName}.{n.MethodName}({args})";
    }

    private string EmitClrNew(IrNode.ClrNew n)
    {
        var args = string.Join(", ", n.Args.Select(EmitExpr));
        return $"new {n.QualifiedTypeName}({args})";
    }

    private string EmitThrow(IrNode.Throw n) => $"throw {EmitExpr(n.Expr)}";

    private string EmitLambdaExpr(IrNode.FuncDef n)
    {
        var parms = string.Join(", ",
            n.Params.Select(p => $"{TypeToCs(p.Type)} {Sanitize(p.Name)}"));
        var body = EmitExpr(n.Body);
        return $"(({parms}) => {body})";
    }

    private string EmitRecordNew(IrNode.RecordNew n)
    {
        var args = string.Join(", ", n.Fields.Select(f => $"{Sanitize(f.FieldName)}: {EmitExpr(f.Value)}"));
        return $"new {Sanitize(n.TypeName)}({args})";
    }

    private string EmitUnionCaseNew(IrNode.UnionCaseNew n)
    {
        if (n.Args.Count == 0)
            return $"new {Sanitize(n.UnionName)}.{Sanitize(n.CaseName)}()";
        var args = string.Join(", ", n.Args.Select(EmitExpr));
        return $"new {Sanitize(n.UnionName)}.{Sanitize(n.CaseName)}({args})";
    }

    private string EmitMatch(IrNode.Match n)
    {
        var scrutinee = EmitExpr(n.Scrutinee);
        var scrutineeType = n.Scrutinee.Type;
        var sb = new StringBuilder();
        sb.Append($"{scrutinee} switch {{ ");

        foreach (var arm in n.Arms)
        {
            var pattern = EmitPattern(arm.Pattern, scrutineeType);
            var body = EmitExpr(arm.Body);
            sb.Append($"{pattern} => {body}, ");
        }

        // Only add fallback if the last arm isn't already a catch-all
        var lastPattern = n.Arms[^1].Pattern;
        if (lastPattern is not IrPattern.Wildcard and not IrPattern.Variable)
        {
            sb.Append("_ => throw new System.InvalidOperationException(\"Non-exhaustive match\"), ");
        }
        sb.Append('}');
        return sb.ToString();
    }

    private string EmitPattern(IrPattern p, ZType? scrutineeType) => p switch
    {
        IrPattern.Wildcard => "_",
        IrPattern.Variable v => $"var {Sanitize(v.Name)}",
        IrPattern.Literal { Value: int i } => i.ToString(),
        IrPattern.Literal { Value: float f } =>
            $"{f.ToString(System.Globalization.CultureInfo.InvariantCulture)}f",
        IrPattern.Literal { Value: bool b } => b ? "true" : "false",
        IrPattern.Literal { Value: string s } => $"\"{EscapeString(s)}\"",
        IrPattern.Constructor c => EmitConstructorPattern(c, scrutineeType),
        _ => "_"
    };

    private string EmitConstructorPattern(IrPattern.Constructor c, ZType? scrutineeType)
    {
        var qualifiedName = ResolveConstructorName(c.Name, scrutineeType);

        if (c.Fields.Count == 0)
            return qualifiedName;

        var fields = string.Join(", ", c.Fields.Select((f, i) => EmitPattern(f, null)));
        return $"{qualifiedName}({fields})";
    }

    private string ResolveConstructorName(string ctorName, ZType? scrutineeType)
    {
        if (!BuiltinCtorNames.Contains(ctorName) || scrutineeType is null)
            return ctorName;

        var baseType = TypeToCs(scrutineeType);
        return $"{baseType}.{ctorName}";
    }

    private string EmitListNew(IrNode.ListNew n)
    {
        var elems = string.Join(", ", n.Elements.Select(EmitExpr));
        return $"ZScript.Runtime.ZsList.Of({elems})";
    }

    private string EmitVectorNew(IrNode.VectorNew n)
    {
        var elems = string.Join(", ", n.Elements.Select(EmitExpr));
        return $"ZScript.Runtime.ZsVector.Of({elems})";
    }

    private string EmitMapNew(IrNode.MapNew n)
    {
        var entries = string.Join(", ",
            n.Entries.Select(e => $"({EmitExpr(e.Key)}, {EmitExpr(e.Value)})"));
        return $"ZScript.Runtime.ZsMap.Of({entries})";
    }

    private string EmitTcoJump(IrNode.TcoJump j)
    {
        // This is used in the tail-recursive loop rewrite
        var sb = new StringBuilder();
        sb.Append("{ ");
        for (int i = 0; i < j.NewArgs.Count; i++)
        {
            var tmpName = $"__tmp_{i}";
            sb.Append($"var {tmpName} = {EmitExpr(j.NewArgs[i])}; ");
        }
        for (int i = 0; i < j.NewArgs.Count; i++)
        {
            sb.Append($"__{Sanitize(j.ParamNames[i])} = __tmp_{i}; ");
        }
        sb.Append("continue; }");
        return sb.ToString();
    }

    private string EmitBuiltinCtorCall(IrNode.BuiltinCtorCall n)
    {
        var typeArgsStr = n.TypeArgs.Count > 0
            ? $"<{string.Join(", ", n.TypeArgs.Select(TypeToCs))}>"
            : "";

        if (n.RuntimeTypeName == "ZsError")
        {
            // (Error "msg") → new ZScript.Runtime.ZsError("msg")
            var args = string.Join(", ", n.Args.Select(EmitExpr));
            return $"new ZScript.Runtime.ZsError({args})";
        }

        var qualifiedBase = $"ZScript.Runtime.{n.RuntimeTypeName}{typeArgsStr}";
        var caseName = n.CaseName ?? "";

        if (n.Args.Count == 0)
            return $"new {qualifiedBase}.{caseName}()";

        var argStr = string.Join(", ", n.Args.Select(EmitExpr));
        return $"new {qualifiedBase}.{caseName}({argStr})";
    }

    private string EmitMethodCall(IrNode.MethodCall n)
    {
        var receiver = EmitExpr(n.Receiver);
        if (n.IsProperty) return $"{receiver}.{n.MethodName}";
        if (n.IsIndexer) return $"{receiver}[{EmitExpr(n.Args[0])}]";
        var args = string.Join(", ", n.Args.Select(EmitExpr));
        return $"{receiver}.{n.MethodName}({args})";
    }

    private string EmitTryCatch(IrNode.TryCatch n)
    {
        // Extract the Ok/Err types from n.Type which should be Result<T, Error>
        var resultType = TypeToCs(n.Type);
        string okTypeStr, errTypeStr;
        if (n.Type is ZType.ZNamedType { Name: "Result", TypeArgs: [var okT, var errT] })
        {
            okTypeStr = TypeToCs(okT);
            errTypeStr = TypeToCs(errT);
        }
        else
        {
            okTypeStr = "object";
            errTypeStr = "ZScript.Runtime.ZsError";
        }

        var body = EmitExpr(n.Body);
        return $"((System.Func<{resultType}>)(() => {{ try {{ return new ZScript.Runtime.ZsResult<{okTypeStr}, {errTypeStr}>.Ok({body}); }} catch (System.Exception __ex) {{ return new ZScript.Runtime.ZsResult<{okTypeStr}, {errTypeStr}>.Err(new ZScript.Runtime.ZsError(__ex.Message)); }} }}))()";
    }

    private static bool ContainsPropagate(IrNode node) => node switch
    {
        IrNode.Propagate => true,
        IrNode.Let let => ContainsPropagate(let.Value) || ContainsPropagate(let.Body),
        IrNode.If @if => ContainsPropagate(@if.Then) || ContainsPropagate(@if.Else),
        IrNode.Match match => match.Arms.Any(a => ContainsPropagate(a.Body)),
        _ => false
    };

    private static bool ContainsAwait(IrNode node) => node switch
    {
        IrNode.Await => true,
        IrNode.Let let => ContainsAwait(let.Value) || ContainsAwait(let.Body),
        IrNode.If @if => ContainsAwait(@if.Condition) || ContainsAwait(@if.Then) || ContainsAwait(@if.Else),
        IrNode.Match match => ContainsAwait(match.Scrutinee) || match.Arms.Any(a => ContainsAwait(a.Body)),
        IrNode.Call call => ContainsAwait(call.Function) || call.Args.Any(ContainsAwait),
        _ => false
    };

    private void EmitAsyncStatementsBody(IrNode body, bool isVoidReturn)
    {
        switch (body)
        {
            case IrNode.Let let:
                EmitLine($"var {Sanitize(let.VarName)} = {EmitExpr(let.Value)};");
                EmitAsyncStatementsBody(let.Body, isVoidReturn);
                break;
            case IrNode.If @if:
                EmitLine($"if ({EmitExpr(@if.Condition)})");
                EmitLine("{");
                _indent++;
                EmitAsyncStatementsBody(@if.Then, isVoidReturn);
                _indent--;
                EmitLine("}");
                EmitLine("else");
                EmitLine("{");
                _indent++;
                EmitAsyncStatementsBody(@if.Else, isVoidReturn);
                _indent--;
                EmitLine("}");
                break;
            case IrNode.Throw:
                EmitLine($"{EmitExpr(body)};");
                break;
            default:
                if (isVoidReturn)
                    EmitLine($"{EmitExpr(body)};");
                else
                    EmitLine($"return {EmitExpr(body)};");
                break;
        }
    }

    private void EmitStatementsBody(IrNode body, ZType funcReturnType)
    {
        switch (body)
        {
            case IrNode.Let let when ContainsPropagate(let.Value):
            {
                // The value contains a propagate — emit it as statements
                if (let.Value is IrNode.Propagate prop)
                {
                    EmitPropagateBinding(prop, let.VarName, funcReturnType);
                }
                else
                {
                    EmitLine($"var {Sanitize(let.VarName)} = {EmitExpr(let.Value)};");
                }
                EmitStatementsBody(let.Body, funcReturnType);
                break;
            }
            case IrNode.Let let:
            {
                EmitLine($"var {Sanitize(let.VarName)} = {EmitExpr(let.Value)};");
                EmitStatementsBody(let.Body, funcReturnType);
                break;
            }
            case IrNode.If @if when ContainsPropagate(@if):
            {
                EmitLine($"if ({EmitExpr(@if.Condition)})");
                EmitLine("{");
                _indent++;
                EmitStatementsBody(@if.Then, funcReturnType);
                _indent--;
                EmitLine("}");
                EmitLine("else");
                EmitLine("{");
                _indent++;
                EmitStatementsBody(@if.Else, funcReturnType);
                _indent--;
                EmitLine("}");
                break;
            }
            case IrNode.Throw:
                EmitLine($"{EmitExpr(body)};");
                break;
            default:
                if (funcReturnType == ZType.Unit)
                    EmitLine($"{EmitExpr(body)};");
                else
                    EmitLine($"return {EmitExpr(body)};");
                break;
        }
    }

    private void EmitPropagateBinding(IrNode.Propagate prop, string varName, ZType funcReturnType)
    {
        var id = _propagateCounter++;
        var innerExpr = EmitExpr(prop.Expr);
        var resultType = prop.ResultType;

        // Get the result type string for pattern matching
        string resultTypeStr;
        if (resultType is ZType.ZNamedType { Name: "Result", TypeArgs: [var okT, var errT] })
        {
            resultTypeStr = TypeToCs(resultType);
            TypeToCs(errT);
        }
        else
        {
            resultTypeStr = TypeToCs(resultType);
        }

        // Get the function return type's error type for re-wrapping
        string funcResultStr;
        if (funcReturnType is ZType.ZNamedType { Name: "Result", TypeArgs: [var fOkT, var fErrT] })
        {
            funcResultStr = TypeToCs(funcReturnType);
        }
        else
        {
            funcResultStr = TypeToCs(funcReturnType);
        }

        EmitLine($"var __r{id} = {innerExpr};");
        EmitLine($"if (__r{id} is {resultTypeStr}.Err __err{id})");
        EmitLine($"    return new {funcResultStr}.Err(__err{id}.Error);");
        EmitLine($"var {Sanitize(varName)} = (({resultTypeStr}.Ok)__r{id}).Value;");
    }

    private void EmitTypeDeclarationsInline(IrNode node)
    {
        if (node is IrNode.Seq seq)
        {
            foreach (var child in seq.Nodes)
            {
                if (child is IrNode.RecordDecl rec)
                {
                    EmitLine(EmitRecordDecl(rec));
                    EmitLine();
                }
                else if (child is IrNode.UnionDecl union)
                {
                    EmitLine(EmitUnionDecl(union));
                    EmitLine();
                }
                else if (child is IrNode.ClassDecl classDecl)
                {
                    EmitClassDecl(classDecl);
                    EmitLine();
                }
                else if (child is IrNode.InterfaceDecl ifaceDecl)
                {
                    EmitInterfaceDecl(ifaceDecl);
                    EmitLine();
                }
            }
        }
    }

    private string EmitRecordDecl(IrNode.RecordDecl rec)
    {
        var sb = new StringBuilder();
        if (rec.Attributes is { Count: > 0 })
        {
            foreach (var attr in rec.Attributes)
                sb.AppendLine(FormatAttribute(attr));
        }
        var typeParams = rec.TypeParams.Count > 0
            ? $"<{string.Join(", ", rec.TypeParams)}>"
            : "";
        var fields = string.Join(", ",
            rec.Fields.Select(f =>
            {
                var fieldAttrs = FormatFieldAttributes(f.Attributes);
                return $"{fieldAttrs}{TypeToCs(f.Type)} {Sanitize(f.Name)}";
            }));
        sb.Append($"public sealed record {Sanitize(rec.Name)}{typeParams}({fields});");
        return sb.ToString();
    }

    private string EmitUnionDecl(IrNode.UnionDecl union)
    {
        var typeParams = union.TypeParams.Count > 0
            ? $"<{string.Join(", ", union.TypeParams)}>"
            : "";
        var sb = new StringBuilder();
        if (union.Attributes is { Count: > 0 })
        {
            foreach (var attr in union.Attributes)
                sb.AppendLine(FormatAttribute(attr));
        }
        sb.AppendLine($"public abstract record {Sanitize(union.Name)}{typeParams};");
        foreach (var c in union.Cases)
        {
            var fields = c.Fields.Count > 0
                ? $"({string.Join(", ", c.Fields.Select(f => $"{TypeToCs(f.Type)} {Sanitize(f.Name)}"))})"
                : "()";
            sb.AppendLine($"public sealed record {Sanitize(c.Name)}{fields} : {Sanitize(union.Name)}{typeParams};");
        }
        return sb.ToString();
    }

    private string EmitObjectExpr(IrNode.ObjectExpr n)
    {
        var className = $"__Object_{_objectCounter++}";

        // Find captured variables: vars referenced in method bodies that aren't method params
        var captured = new List<string>();
        foreach (var method in n.Methods)
        {
            var paramNames = new HashSet<string>(method.Params.Select(p => p.Name));
            CollectCapturedVars(method.Body, paramNames, captured);
        }
        captured = captured.Distinct().ToList();

        _objectClasses.Add((className, n, captured));

        if (captured.Count == 0)
            return $"new {className}()";

        var args = string.Join(", ", captured.Select(Sanitize));
        return $"new {className}({args})";
    }

    private static void CollectCapturedVars(IrNode node, HashSet<string> localNames, List<string> captured)
    {
        switch (node)
        {
            case IrNode.Var v:
                if (!localNames.Contains(v.Name))
                    captured.Add(v.Name);
                break;
            case IrNode.Let let:
                CollectCapturedVars(let.Value, localNames, captured);
                var withBinding = new HashSet<string>(localNames) { let.VarName };
                CollectCapturedVars(let.Body, withBinding, captured);
                break;
            case IrNode.If @if:
                CollectCapturedVars(@if.Condition, localNames, captured);
                CollectCapturedVars(@if.Then, localNames, captured);
                CollectCapturedVars(@if.Else, localNames, captured);
                break;
            case IrNode.BinOp bin:
                CollectCapturedVars(bin.Left, localNames, captured);
                CollectCapturedVars(bin.Right, localNames, captured);
                break;
            case IrNode.UnaryOp un:
                CollectCapturedVars(un.Operand, localNames, captured);
                break;
            case IrNode.Call call:
                CollectCapturedVars(call.Function, localNames, captured);
                foreach (var arg in call.Args)
                    CollectCapturedVars(arg, localNames, captured);
                break;
            case IrNode.ClrCall clr:
                foreach (var arg in clr.Args)
                    CollectCapturedVars(arg, localNames, captured);
                break;
            case IrNode.MethodCall mc:
                CollectCapturedVars(mc.Receiver, localNames, captured);
                foreach (var arg in mc.Args)
                    CollectCapturedVars(arg, localNames, captured);
                break;
        }
    }

    private void EmitClassDecl(IrNode.ClassDecl classDecl)
    {
        _currentTypeParams = classDecl.TypeParams.Count > 0
            ? new HashSet<string>(classDecl.TypeParams)
            : null;

        if (classDecl.Attributes is { Count: > 0 })
        {
            foreach (var attr in classDecl.Attributes)
                EmitLine(FormatAttribute(attr));
        }

        var typeParams = classDecl.TypeParams.Count > 0
            ? $"<{string.Join(", ", classDecl.TypeParams)}>"
            : "";
        var interfaces = classDecl.InterfaceNames.Count > 0
            ? $" : {string.Join(", ", classDecl.InterfaceNames)}"
            : "";
        EmitLine($"public sealed class {Sanitize(classDecl.Name)}{typeParams}{interfaces}");
        EmitLine("{");
        _indent++;

        // Properties (readonly)
        foreach (var field in classDecl.Fields)
            EmitLine($"public {TypeToCs(field.Type)} {Sanitize(field.Name)} {{ get; }}");

        EmitLine();

        // Constructor
        var ctorParams = string.Join(", ",
            classDecl.Fields.Select(f => $"{TypeToCs(f.Type)} {Sanitize(f.Name)}"));
        EmitLine($"public {Sanitize(classDecl.Name)}({ctorParams})");
        EmitLine("{");
        _indent++;
        foreach (var field in classDecl.Fields)
            EmitLine($"this.{Sanitize(field.Name)} = {Sanitize(field.Name)};");
        _indent--;
        EmitLine("}");

        // Methods
        _currentClassFields = new HashSet<string>(classDecl.Fields.Select(f => f.Name));
        foreach (var method in classDecl.Methods)
        {
            _currentClassLocals = new HashSet<string>(method.Params.Select(p => p.Name));
            EmitLine();
            if (method.Attributes is { Count: > 0 })
            {
                foreach (var attr in method.Attributes)
                    EmitLine(FormatAttribute(attr));
            }
            var retTypeStr = ReturnTypeToCs(method.ReturnType);
            var parms = string.Join(", ",
                method.Params.Select(p => $"{TypeToCs(p.Type)} {Sanitize(p.Name)}"));
            EmitLine($"public {retTypeStr} {Sanitize(method.Name)}({parms})");
            EmitLine("{");
            _indent++;
            if (method.ReturnType == ZType.Unit)
                EmitLine($"{EmitExpr(method.Body)};");
            else
                EmitLine($"return {EmitExpr(method.Body)};");
            _indent--;
            EmitLine("}");
            _currentClassLocals = null;
        }
        _currentClassFields = null;

        _indent--;
        EmitLine("}");
        _currentTypeParams = null;
    }

    private void EmitClassStaticWrappers(IrNode.ClassDecl classDecl)
    {
        var typeParams = classDecl.TypeParams.Count > 0
            ? $"<{string.Join(", ", classDecl.TypeParams)}>"
            : "";
        var classTypeStr = $"{Sanitize(classDecl.Name)}{typeParams}";

        // Field accessors: ClassName/fieldName : ClassName -> FieldType
        foreach (var field in classDecl.Fields)
        {
            var wrapperName = $"{Sanitize(classDecl.Name)}_{Sanitize(field.Name)}";
            EmitLine($"public static {TypeToCs(field.Type)} {wrapperName}({classTypeStr} self) => self.{Sanitize(field.Name)};");
        }

        // Method wrappers: ClassName/methodName : (ClassName, ParamTypes...) -> RetType
        foreach (var method in classDecl.Methods)
        {
            var wrapperName = $"{Sanitize(classDecl.Name)}_{Sanitize(method.Name)}";
            var parms = new List<string> { $"{classTypeStr} self" };
            parms.AddRange(method.Params.Select(p => $"{TypeToCs(p.Type)} {Sanitize(p.Name)}"));
            var args = string.Join(", ", method.Params.Select(p => Sanitize(p.Name)));
            var wrapperRetType = ReturnTypeToCs(method.ReturnType);
            var callExpr = $"self.{Sanitize(method.Name)}({args})";
            if (method.ReturnType == ZType.Unit)
                EmitLine($"public static {wrapperRetType} {wrapperName}({string.Join(", ", parms)}) {{ {callExpr}; }}");
            else
                EmitLine($"public static {wrapperRetType} {wrapperName}({string.Join(", ", parms)}) => {callExpr};");
        }

        EmitLine();
    }

    private void EmitInterfaceDecl(IrNode.InterfaceDecl ifaceDecl)
    {
        _currentTypeParams = ifaceDecl.TypeParams.Count > 0
            ? new HashSet<string>(ifaceDecl.TypeParams)
            : null;

        if (ifaceDecl.Attributes is { Count: > 0 })
        {
            foreach (var attr in ifaceDecl.Attributes)
                EmitLine(FormatAttribute(attr));
        }

        var typeParams = ifaceDecl.TypeParams.Count > 0
            ? $"<{string.Join(", ", ifaceDecl.TypeParams)}>"
            : "";
        var baseInterfaces = ifaceDecl.BaseInterfaceNames.Count > 0
            ? $" : {string.Join(", ", ifaceDecl.BaseInterfaceNames)}"
            : "";
        EmitLine($"public interface {Sanitize(ifaceDecl.Name)}{typeParams}{baseInterfaces}");
        EmitLine("{");
        _indent++;

        foreach (var method in ifaceDecl.Methods)
        {
            var retTypeStr = ReturnTypeToCs(method.ReturnType);
            var parms = string.Join(", ",
                method.Params.Select(p => $"{TypeToCs(p.Type)} {Sanitize(p.Name)}"));
            EmitLine($"{retTypeStr} {Sanitize(method.Name)}({parms});");
        }

        _indent--;
        EmitLine("}");
        _currentTypeParams = null;
    }

    private void EmitInterfaceStaticWrappers(IrNode.InterfaceDecl ifaceDecl)
    {
        var typeParams = ifaceDecl.TypeParams.Count > 0
            ? $"<{string.Join(", ", ifaceDecl.TypeParams)}>"
            : "";
        var ifaceTypeStr = $"{Sanitize(ifaceDecl.Name)}{typeParams}";

        foreach (var method in ifaceDecl.Methods)
        {
            var wrapperName = $"{Sanitize(ifaceDecl.Name)}_{Sanitize(method.Name)}";
            var parms = new List<string> { $"{ifaceTypeStr} self" };
            parms.AddRange(method.Params.Select(p => $"{TypeToCs(p.Type)} {Sanitize(p.Name)}"));
            var args = string.Join(", ", method.Params.Select(p => Sanitize(p.Name)));
            var wrapperRetType = ReturnTypeToCs(method.ReturnType);
            var callExpr = $"self.{Sanitize(method.Name)}({args})";
            if (method.ReturnType == ZType.Unit)
                EmitLine($"public static {wrapperRetType} {wrapperName}({string.Join(", ", parms)}) {{ {callExpr}; }}");
            else
                EmitLine($"public static {wrapperRetType} {wrapperName}({string.Join(", ", parms)}) => {callExpr};");
        }

        EmitLine();
    }

    private void EmitObjectClasses()
    {
        foreach (var (className, expr, captured) in _objectClasses)
        {
            var interfaces = string.Join(", ", expr.InterfaceNames);
            EmitLine($"private sealed class {className} : {interfaces}");
            EmitLine("{");
            _indent++;

            // Fields for captured variables
            foreach (var cap in captured)
            {
                EmitLine($"private readonly object {Sanitize(cap)}_field;");
            }

            // Constructor
            if (captured.Count > 0)
            {
                var ctorParams = string.Join(", ", captured.Select(c => $"object {Sanitize(c)}_param"));
                EmitLine($"public {className}({ctorParams})");
                EmitLine("{");
                _indent++;
                foreach (var cap in captured)
                    EmitLine($"this.{Sanitize(cap)}_field = {Sanitize(cap)}_param;");
                _indent--;
                EmitLine("}");
            }

            // Methods
            foreach (var method in expr.Methods)
            {
                var retTypeStr = TypeToCs(method.ReturnType);
                var parms = string.Join(", ",
                    method.Params.Select(p => $"{TypeToCs(p.Type)} {Sanitize(p.Name)}"));
                EmitLine($"public {retTypeStr} {Sanitize(method.Name)}({parms})");
                EmitLine("{");
                _indent++;
                EmitLine($"return {EmitExpr(method.Body)};");
                _indent--;
                EmitLine("}");
            }

            _indent--;
            EmitLine("}");
            EmitLine();
        }
    }

    private static string FormatAttribute(IrAttribute attr)
    {
        var args = new List<string>();
        foreach (var arg in attr.PositionalArgs)
            args.Add(FormatAttributeValue(arg));
        foreach (var (name, value) in attr.NamedArgs)
            args.Add($"{name} = {FormatAttributeValue(value)}");
        return args.Count > 0 ? $"[{attr.Name}({string.Join(", ", args)})]" : $"[{attr.Name}]";
    }

    private static string FormatAttributeValue(object value) => value switch
    {
        string s => $"\"{EscapeString(s)}\"",
        bool b => b ? "true" : "false",
        int i => i.ToString(),
        float f => $"{f.ToString(System.Globalization.CultureInfo.InvariantCulture)}f",
        _ => value.ToString() ?? ""
    };

    private void EmitAttributes(IReadOnlyList<IrAttribute>? attrs)
    {
        if (attrs is null) return;
        foreach (var attr in attrs)
            EmitLine(FormatAttribute(attr));
    }

    private static string FormatFieldAttributes(IReadOnlyList<IrAttribute>? attrs)
    {
        if (attrs is null or { Count: 0 }) return "";
        var parts = attrs.Select(a => FormatAttribute(a).Insert(1, "property: "));
        return string.Join(" ", parts) + " ";
    }

    private string FormatParam(IrParam p)
    {
        var prefix = "";
        if (p.Attributes is { Count: > 0 })
            prefix = string.Join(" ", p.Attributes.Select(FormatAttribute)) + " ";
        return $"{prefix}{TypeToCs(p.Type)} {Sanitize(p.Name)}";
    }

    private string ReturnTypeToCs(ZType type) =>
        type == ZType.Unit ? "void" : TypeToCs(type);

    private string TypeToCs(ZType type) => type switch
    {
        ZType.ZPrimitiveType { Kind: PrimitiveKind.Int } => "int",
        ZType.ZPrimitiveType { Kind: PrimitiveKind.Long } => "long",
        ZType.ZPrimitiveType { Kind: PrimitiveKind.Float } => "float",
        ZType.ZPrimitiveType { Kind: PrimitiveKind.Double } => "double",
        ZType.ZPrimitiveType { Kind: PrimitiveKind.Byte } => "byte",
        ZType.ZPrimitiveType { Kind: PrimitiveKind.Char } => "char",
        ZType.ZPrimitiveType { Kind: PrimitiveKind.Bool } => "bool",
        ZType.ZPrimitiveType { Kind: PrimitiveKind.String } => "string",
        ZType.ZPrimitiveType { Kind: PrimitiveKind.Unit } => "ZScript.Runtime.ZsUnit",
        ZType.ZFuncType ft =>
            $"System.Func<{string.Join(", ", ft.Params.Select(TypeToCs).Append(TypeToCs(ft.Return)))}>",
        ZType.ZNamedType { Name: "List", TypeArgs: [var elem] } =>
            $"ZScript.Runtime.ZsList<{TypeToCs(elem)}>",
        ZType.ZNamedType { Name: "Vector", TypeArgs: [var elem] } =>
            $"ZScript.Runtime.ZsVector<{TypeToCs(elem)}>",
        ZType.ZNamedType { Name: "Map", TypeArgs: [var k, var v] } =>
            $"ZScript.Runtime.ZsMap<{TypeToCs(k)}, {TypeToCs(v)}>",
        ZType.ZNamedType { Name: "Option", TypeArgs: [var t] } =>
            $"ZScript.Runtime.ZsOption<{TypeToCs(t)}>",
        ZType.ZNamedType { Name: "Result", TypeArgs: [var t, var e] } =>
            $"ZScript.Runtime.ZsResult<{TypeToCs(t)}, {TypeToCs(e)}>",
        ZType.ZNamedType { Name: "Error", TypeArgs: [] } => "ZScript.Runtime.ZsError",
        ZType.ZNamedType { Name: "Task", TypeArgs: [] } =>
            "System.Threading.Tasks.Task",
        ZType.ZNamedType { Name: "Task", TypeArgs: [var taskT] } =>
            $"System.Threading.Tasks.Task<{TypeToCs(taskT)}>",
        ZType.ZNamedType nt when nt.TypeArgs.Count > 0 =>
            $"{Sanitize(nt.Name)}<{string.Join(", ", nt.TypeArgs.Select(TypeToCs))}>",
        ZType.ZNamedType nt when IsUnresolvedTypeVariable(nt.Name) => "object", // unresolved type vars from annotations
        ZType.ZNamedType nt => Sanitize(nt.Name),
        ZType.ZTypeVar tv => "object", // fallback for unresolved type vars
        _ => "object"
    };

    private bool IsUnresolvedTypeVariable(string name) =>
        name.Length == 1 && char.IsLower(name[0])
        && (_currentTypeParams is null || !_currentTypeParams.Contains(name));

    private static readonly HashSet<string> CSharpKeywords =
    [
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
        "checked", "class", "const", "continue", "decimal", "default", "delegate",
        "do", "double", "else", "enum", "event", "explicit", "extern", "false",
        "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
        "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
        "new", "null", "object", "operator", "out", "override", "params", "private",
        "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
        "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
        "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
        "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"
    ];

    private static string Sanitize(string name)
    {
        // Replace characters invalid in C# identifiers
        var sanitized = name.Replace("-", "_").Replace("/", "_").Replace("?", "_q").Replace(">", "_gt").Replace("|", "_pipe");
        if (CSharpKeywords.Contains(sanitized))
            return $"@{sanitized}";
        return sanitized;
    }

    private static string EscapeString(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r").Replace("\t", "\\t");

    private void EmitLine(string line = "")
    {
        if (string.IsNullOrEmpty(line))
        {
            _sb.AppendLine();
        }
        else
        {
            _sb.Append(new string(' ', _indent * 4));
            _sb.AppendLine(line);
        }
    }

    // --- Tail Call Optimization helpers ---

    private static bool IsTailRecursive(IrNode body, string funcName) => body switch
    {
        IrNode.If @if =>
            IsTailRecursive(@if.Then, funcName) || IsTailRecursive(@if.Else, funcName),
        IrNode.Let let => IsTailRecursive(let.Body, funcName),
        IrNode.Call { Function: IrNode.Var v } when v.Name == funcName => true,
        IrNode.BinOp { Op: var op, Left: IrNode.Call { Function: IrNode.Var v } }
            when v.Name == funcName => false, // not tail if result is used in binop
        _ => false
    };
}
