using System.Text;
using Microsoft.CodeAnalysis;

namespace ZScript.Generators;

[Generator]
public sealed class BuiltinMethodRegistryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var compilationProvider = context.CompilationProvider;

        context.RegisterSourceOutput(compilationProvider, static (spc, compilation) =>
        {
            var attributeSymbol = compilation.GetTypeByMetadataName("ZScript.Runtime.ZsBuiltinAttribute");
            if (attributeSymbol is null)
                return;

            var typeNames = new[]
            {
                "ZScript.Runtime.ZsList`1",
                "ZScript.Runtime.ZsVector`1",
                "ZScript.Runtime.ZsMap`2",
            };

            var entries = new List<(string Key, string CSharpName, bool IsProperty, bool IsIndexer)>();

            foreach (var typeName in typeNames)
            {
                var typeSymbol = compilation.GetTypeByMetadataName(typeName);
                if (typeSymbol is null)
                    continue;

                foreach (var member in typeSymbol.GetMembers())
                {
                    if (member.DeclaredAccessibility != Accessibility.Public)
                        continue;

                    AttributeData? attr = null;
                    foreach (var a in member.GetAttributes())
                    {
                        if (SymbolEqualityComparer.Default.Equals(a.AttributeClass, attributeSymbol))
                        {
                            attr = a;
                            break;
                        }
                    }

                    if (attr is null)
                        continue;

                    var name = (string)attr.ConstructorArguments[0].Value!;
                    var isIndexer = false;
                    foreach (var namedArg in attr.NamedArguments)
                    {
                        if (namedArg.Key == "IsIndexer")
                        {
                            isIndexer = (bool)namedArg.Value.Value!;
                            break;
                        }
                    }

                    bool isProperty;
                    string csharpName;

                    if (member is IPropertySymbol prop)
                    {
                        isProperty = true;
                        csharpName = isIndexer ? "" : prop.Name;
                    }
                    else if (member is IMethodSymbol)
                    {
                        isProperty = false;
                        csharpName = member.Name;
                    }
                    else
                    {
                        continue;
                    }

                    entries.Add((name, csharpName, isProperty, isIndexer));
                }
            }

            if (entries.Count == 0)
                return;

            entries.Sort((a, b) => string.Compare(a.Key, b.Key, StringComparison.Ordinal));

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace ZScript.Compiler.Ir;");
            sb.AppendLine();
            sb.AppendLine("public static class BuiltinMethodRegistry");
            sb.AppendLine("{");
            sb.AppendLine("    public static IReadOnlyDictionary<string, CollectionMethodInfo> CollectionMethods { get; } =");
            sb.AppendLine("        new Dictionary<string, CollectionMethodInfo>");
            sb.AppendLine("        {");

            foreach (var (key, csharpName, isProperty, isIndexer) in entries)
            {
                var propStr = isProperty ? "true" : "false";
                var idxStr = isIndexer ? "true" : "false";
                sb.AppendLine($"            [\"{key}\"] = new(\"{csharpName}\", {propStr}, {idxStr}),");
            }

            sb.AppendLine("        };");
            sb.AppendLine("}");

            spc.AddSource("BuiltinMethodRegistry.g.cs", sb.ToString());
        });
    }
}
