<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\ZScript.Runtime\ZScript.Runtime.csproj" />
    <ProjectReference Include="..\ZScript.Generators\ZScript.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
