[package]
name = "zscheme"
description = "ZScheme language support for Zed"
version = "0.1.0"
authors = ["Zach Howe <zach@zachhowe.com>"]
schema_version = 1

[language_servers.zscheme-lsp]
name = "ZScheme Language Server"
languages = ["ZScheme"]

[[grammars]]
name = "zscheme"
repository = "https://github.com/zachhowe/tree-sitter-zscheme"
rev = "main"
