<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZScript.Compiler\ZScript.Compiler.csproj" />
    <ProjectReference Include="..\ZScript.Runtime\ZScript.Runtime.csproj" />
  </ItemGroup>
</Project>
