// <auto-generated by ZScript compiler 0.1.0+7183f05>
#nullable enable

namespace ZScriptGenerated;

public static class Program
{
    public static async System.Threading.Tasks.Task<int> compute_async(int x)
    {
        return (x + 1);
    }

    public static async System.Threading.Tasks.Task<int> fetch_and_add(int x)
    {
        var result = await compute_async(x);
        return (result + 10);
    }

    public static async System.Threading.Tasks.Task<int> double_compute(int x)
    {
        var a = await compute_async(x);
        var b = await compute_async(a);
        return (a + b);
    }

    public static async System.Threading.Tasks.Task do_work()
    {
        await compute_async(42);
    }

}
