// <auto-generated by ZScript compiler 0.1.0+7183f05>
#nullable enable

namespace ZScript.Examples;

public static class Boolean
{
    public static bool both_positive(int a, int b)
    {
        return ((a > 0) && (b > 0));
    }

    public static bool either_zero(int a, int b)
    {
        return ((a == 0) || (b == 0));
    }

    public static bool is_nonzero(int x)
    {
        return (!(x == 0));
    }

    public static bool in_range(int x, int lo, int hi)
    {
        return ((x >= lo) && (x <= hi));
    }

    public static int sign(int x)
    {
        return ((x < 0) ? -1 : ((x == 0) ? 0 : 1));
    }

    public static bool xor(bool a, bool b)
    {
        return ((a || b) && (!(a && b)));
    }

}
