// <auto-generated by ZScript compiler 0.1.0+b78848d>
#nullable enable

namespace ZScript.Examples;

public static class Program
{
    public static string x = "hello";
    public static int main(ZScript.Runtime.ZsList<string> args)
    {
        return 0;
    }


    static Program()
    {
        System.Console.WriteLine(x);
    }

    public static int Main(string[] args)
    {
        return main(ZScript.Runtime.ZsList<string>.FromItems(args));
    }
}
