// <auto-generated by ZScript compiler 0.1.0+f72469b>
#nullable enable

namespace ZScript.Examples;

public sealed record ZsUnit { public static readonly ZsUnit Value = new(); }

public static class ClrNewModule
{
    public static System.Object obj = new System.Object();
    public static System.Text.StringBuilder sb = new System.Text.StringBuilder("Hello, ZScript!");
    public static System.Collections.ArrayList lst = new System.Collections.ArrayList(16);
    public static int main(System.Collections.Immutable.ImmutableList<string> args)
    {
        return 0;
    }


    static ClrNewModule()
    {
        System.Console.WriteLine("constructed object");
        System.Console.WriteLine("constructed string builder");
        System.Console.WriteLine("constructed array list");
    }

    public static int Main(string[] args)
    {
        return main(System.Collections.Immutable.ImmutableList.Create(args));
    }
}
