// <auto-generated by ZScript compiler 0.1.0+0b415cb>
#nullable enable

using System.Collections.Immutable;
using ZScript.Runtime;

namespace ZScript.Examples;

public sealed record ZsUnit { public static readonly ZsUnit Value = new(); }

public static class Program
{
    public static string x = "hello";
    public static int main(System.Collections.Immutable.ImmutableList<string> args)
    {
        return 0;
    }


    static Program()
    {
        System.Console.WriteLine(x);
    }

    public static int Main(string[] args)
    {
        return main(System.Collections.Immutable.ImmutableList.Create(args));
    }
}

public abstract record Option<T0>;
public sealed record Some<T0>(T0 value) : Option<T0>;
public sealed record None<T0>() : Option<T0>;


public abstract record Result<T0, T1>;
public sealed record Ok<T0, T1>(T0 value) : Result<T0, T1>;
public sealed record Err<T0, T1>(T1 error) : Result<T0, T1>;


public sealed record ErrorInfo(string message, Option<ErrorInfo> cause);

public static class OptionModule
{
    public static T0 option_unwrap<T0>(Option<T0> opt)
    {
        return opt switch { Some<T0>(var v) => v, None<T0> => throw new System.Exception("Called unwrap on None"), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static T0 option_unwrap_or<T0>(Option<T0> opt, T0 @default)
    {
        return opt switch { Some<T0>(var v) => v, None<T0> => @default, _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static Option<T1> option_map<T0, T1>(Option<T0> opt, System.Func<T0, T1> f)
    {
        return opt switch { Some<T0>(var v) => new Some<T1>(f(v)), None<T0> => new None<T1>(), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static Option<T1> option_flat_map<T0, T1>(Option<T0> opt, System.Func<T0, Option<T1>> f)
    {
        return opt switch { Some<T0>(var v) => f(v), None<T0> => new None<T1>(), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static bool option_some_q<T0>(Option<T0> opt)
    {
        return opt switch { Some<T0>(_) => true, None<T0> => false, _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static bool option_none_q<T0>(Option<T0> opt)
    {
        return opt switch { Some<T0>(_) => false, None<T0> => true, _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

}

public static class ResultModule
{
    public static T1 result_unwrap<T0, T1>(Result<T1, T0> res)
    {
        return res switch { Ok<T1, T0>(var v) => v, Err<T1, T0>(_) => throw new System.Exception("Called unwrap on Err"), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static Result<T2, T1> result_map<T0, T1, T2>(Result<T0, T1> res, System.Func<T0, T2> f)
    {
        return res switch { Ok<T0, T1>(var v) => new Ok<T2, T1>(f(v)), Err<T0, T1>(var e) => new Err<T2, T1>(e), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static Result<T2, T1> result_flat_map<T0, T1, T2>(Result<T0, T1> res, System.Func<T0, Result<T2, T1>> f)
    {
        return res switch { Ok<T0, T1>(var v) => f(v), Err<T0, T1>(var e) => new Err<T2, T1>(e), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static bool result_ok_q<T0, T1>(Result<T0, T1> res)
    {
        return res switch { Ok<T0, T1>(_) => true, Err<T0, T1>(_) => false, _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static bool result_err_q<T0, T1>(Result<T0, T1> res)
    {
        return res switch { Ok<T0, T1>(_) => false, Err<T0, T1>(_) => true, _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

}

public static class ErrorModule
{
    public static ErrorInfo Error(string msg)
    {
        return new ErrorInfo(message: msg, cause: new None<ErrorInfo>());
    }

}

public static class CoreModule
{
    public static object id(object x)
    {
        return x;
    }

    public static object @const(object x, object y)
    {
        return x;
    }

    public static object compose(System.Func<object, object> f, System.Func<object, object> g, object x)
    {
        return f(g(x));
    }

    public static object flip(System.Func<object, object, object> f, object x, object y)
    {
        return f(y, x);
    }

}

public static class ListModule
{
    public static System.Collections.Immutable.ImmutableList<T1> list__map_loop<T0, T1>(System.Collections.Immutable.ImmutableList<T0> xs, System.Func<T0, T1> f, int len, int i, System.Collections.Immutable.ImmutableList<T1> acc)
    {
        while (true)
        {
            if ((i == len))
            {
                return acc;
            }
            else
            {
                var __tmp_0 = xs;
                var __tmp_1 = f;
                var __tmp_2 = len;
                var __tmp_3 = (i + 1);
                var __tmp_4 = acc.Add(f(xs[i]));
                xs = __tmp_0;
                f = __tmp_1;
                len = __tmp_2;
                i = __tmp_3;
                acc = __tmp_4;
                continue;
            }
        }
    }

    public static System.Collections.Immutable.ImmutableList<T0> list__filter_loop<T0>(System.Collections.Immutable.ImmutableList<T0> xs, System.Func<T0, bool> pred, int len, int i, System.Collections.Immutable.ImmutableList<T0> acc)
    {
        while (true)
        {
            if ((i == len))
            {
                return acc;
            }
            else
            {
                var item = xs[i];
                if (pred(item))
                {
                    var __tmp_0 = xs;
                    var __tmp_1 = pred;
                    var __tmp_2 = len;
                    var __tmp_3 = (i + 1);
                    var __tmp_4 = acc.Add(item);
                    xs = __tmp_0;
                    pred = __tmp_1;
                    len = __tmp_2;
                    i = __tmp_3;
                    acc = __tmp_4;
                    continue;
                }
                else
                {
                    var __tmp_0 = xs;
                    var __tmp_1 = pred;
                    var __tmp_2 = len;
                    var __tmp_3 = (i + 1);
                    var __tmp_4 = acc;
                    xs = __tmp_0;
                    pred = __tmp_1;
                    len = __tmp_2;
                    i = __tmp_3;
                    acc = __tmp_4;
                    continue;
                }
            }
        }
    }

    public static T1 list__fold_loop<T0, T1>(System.Collections.Immutable.ImmutableList<T0> xs, System.Func<T1, T0, T1> f, int len, int i, T1 acc)
    {
        while (true)
        {
            if ((i == len))
            {
                return acc;
            }
            else
            {
                var __tmp_0 = xs;
                var __tmp_1 = f;
                var __tmp_2 = len;
                var __tmp_3 = (i + 1);
                var __tmp_4 = f(acc, xs[i]);
                xs = __tmp_0;
                f = __tmp_1;
                len = __tmp_2;
                i = __tmp_3;
                acc = __tmp_4;
                continue;
            }
        }
    }

    public static int list_count<T0>(System.Collections.Immutable.ImmutableList<T0> xs)
    {
        return xs.Count;
    }

    public static T0 list_nth<T0>(System.Collections.Immutable.ImmutableList<T0> xs, int i)
    {
        return xs[i];
    }

    public static T0 list_head<T0>(System.Collections.Immutable.ImmutableList<T0> xs)
    {
        return xs[0];
    }

    public static System.Collections.Immutable.ImmutableList<T0> list_tail<T0>(System.Collections.Immutable.ImmutableList<T0> xs)
    {
        return xs.RemoveAt(0);
    }

    public static System.Collections.Immutable.ImmutableList<T0> list_cons<T0>(T0 x, System.Collections.Immutable.ImmutableList<T0> xs)
    {
        return xs.Insert(0, x);
    }

    public static System.Collections.Immutable.ImmutableList<T0> list_append<T0>(System.Collections.Immutable.ImmutableList<T0> xs, T0 x)
    {
        return xs.Add(x);
    }

    public static System.Collections.Immutable.ImmutableList<T0> list_concat<T0>(System.Collections.Immutable.ImmutableList<T0> xs, System.Collections.Immutable.ImmutableList<T0> ys)
    {
        return xs.AddRange(ys);
    }

    public static bool list_empty_q<T0>(System.Collections.Immutable.ImmutableList<T0> xs)
    {
        return (xs.Count == 0);
    }

    public static System.Collections.Immutable.ImmutableList<T1> list_map<T0, T1>(System.Collections.Immutable.ImmutableList<T0> xs, System.Func<T0, T1> f)
    {
        return ((System.Func<int, System.Collections.Immutable.ImmutableList<T1>>)((int len) => ListModule.list__map_loop(xs, f, len, 0, System.Collections.Immutable.ImmutableList<T1>.Empty)))(xs.Count);
    }

    public static System.Collections.Immutable.ImmutableList<T0> list_filter<T0>(System.Collections.Immutable.ImmutableList<T0> xs, System.Func<T0, bool> pred)
    {
        return ((System.Func<int, System.Collections.Immutable.ImmutableList<T0>>)((int len) => ListModule.list__filter_loop(xs, pred, len, 0, System.Collections.Immutable.ImmutableList<T0>.Empty)))(xs.Count);
    }

    public static T1 list_fold<T0, T1>(System.Collections.Immutable.ImmutableList<T0> xs, T1 init, System.Func<T1, T0, T1> f)
    {
        return ((System.Func<int, T1>)((int len) => ListModule.list__fold_loop(xs, f, len, 0, init)))(xs.Count);
    }

}

public static class VectorModule
{
    public static System.Collections.Immutable.ImmutableArray<T1> vector__map_loop<T0, T1>(System.Collections.Immutable.ImmutableArray<T0> xs, System.Func<T0, T1> f, int len, int i, System.Collections.Immutable.ImmutableArray<T1> acc)
    {
        while (true)
        {
            if ((i == len))
            {
                return acc;
            }
            else
            {
                var __tmp_0 = xs;
                var __tmp_1 = f;
                var __tmp_2 = len;
                var __tmp_3 = (i + 1);
                var __tmp_4 = acc.Add(f(xs[i]));
                xs = __tmp_0;
                f = __tmp_1;
                len = __tmp_2;
                i = __tmp_3;
                acc = __tmp_4;
                continue;
            }
        }
    }

    public static System.Collections.Immutable.ImmutableArray<T0> vector__filter_loop<T0>(System.Collections.Immutable.ImmutableArray<T0> xs, System.Func<T0, bool> pred, int len, int i, System.Collections.Immutable.ImmutableArray<T0> acc)
    {
        while (true)
        {
            if ((i == len))
            {
                return acc;
            }
            else
            {
                var item = xs[i];
                if (pred(item))
                {
                    var __tmp_0 = xs;
                    var __tmp_1 = pred;
                    var __tmp_2 = len;
                    var __tmp_3 = (i + 1);
                    var __tmp_4 = acc.Add(item);
                    xs = __tmp_0;
                    pred = __tmp_1;
                    len = __tmp_2;
                    i = __tmp_3;
                    acc = __tmp_4;
                    continue;
                }
                else
                {
                    var __tmp_0 = xs;
                    var __tmp_1 = pred;
                    var __tmp_2 = len;
                    var __tmp_3 = (i + 1);
                    var __tmp_4 = acc;
                    xs = __tmp_0;
                    pred = __tmp_1;
                    len = __tmp_2;
                    i = __tmp_3;
                    acc = __tmp_4;
                    continue;
                }
            }
        }
    }

    public static T1 vector__fold_loop<T0, T1>(System.Collections.Immutable.ImmutableArray<T0> xs, System.Func<T1, T0, T1> f, int len, int i, T1 acc)
    {
        while (true)
        {
            if ((i == len))
            {
                return acc;
            }
            else
            {
                var __tmp_0 = xs;
                var __tmp_1 = f;
                var __tmp_2 = len;
                var __tmp_3 = (i + 1);
                var __tmp_4 = f(acc, xs[i]);
                xs = __tmp_0;
                f = __tmp_1;
                len = __tmp_2;
                i = __tmp_3;
                acc = __tmp_4;
                continue;
            }
        }
    }

    public static int vector_count<T0>(System.Collections.Immutable.ImmutableArray<T0> xs)
    {
        return xs.Length;
    }

    public static T0 vector_nth<T0>(System.Collections.Immutable.ImmutableArray<T0> xs, int i)
    {
        return xs[i];
    }

    public static System.Collections.Immutable.ImmutableArray<T0> vector_append<T0>(System.Collections.Immutable.ImmutableArray<T0> xs, T0 x)
    {
        return xs.Add(x);
    }

    public static System.Collections.Immutable.ImmutableArray<T0> vector_set<T0>(System.Collections.Immutable.ImmutableArray<T0> xs, int i, T0 x)
    {
        return xs.SetItem(i, x);
    }

    public static bool vector_empty_q<T0>(System.Collections.Immutable.ImmutableArray<T0> xs)
    {
        return (xs.Length == 0);
    }

    public static System.Collections.Immutable.ImmutableArray<T1> vector_map<T0, T1>(System.Collections.Immutable.ImmutableArray<T0> xs, System.Func<T0, T1> f)
    {
        return ((System.Func<int, System.Collections.Immutable.ImmutableArray<T1>>)((int len) => VectorModule.vector__map_loop(xs, f, len, 0, System.Collections.Immutable.ImmutableArray<T1>.Empty)))(xs.Length);
    }

    public static System.Collections.Immutable.ImmutableArray<T0> vector_filter<T0>(System.Collections.Immutable.ImmutableArray<T0> xs, System.Func<T0, bool> pred)
    {
        return ((System.Func<int, System.Collections.Immutable.ImmutableArray<T0>>)((int len) => VectorModule.vector__filter_loop(xs, pred, len, 0, System.Collections.Immutable.ImmutableArray<T0>.Empty)))(xs.Length);
    }

    public static T1 vector_fold<T0, T1>(System.Collections.Immutable.ImmutableArray<T0> xs, T1 init, System.Func<T1, T0, T1> f)
    {
        return ((System.Func<int, T1>)((int len) => VectorModule.vector__fold_loop(xs, f, len, 0, init)))(xs.Length);
    }

}

public static class MapModule
{
    public static int map_count<T0, T1>(System.Collections.Immutable.ImmutableDictionary<T0, T1> m)
    {
        return m.Count;
    }

    public static System.Collections.Immutable.ImmutableDictionary<T0, T1> map_put<T0, T1>(System.Collections.Immutable.ImmutableDictionary<T0, T1> m, T0 key, T1 val)
    {
        return m.SetItem(key, val);
    }

    public static System.Collections.Immutable.ImmutableDictionary<T0, T1> map_remove<T0, T1>(System.Collections.Immutable.ImmutableDictionary<T0, T1> m, T0 key)
    {
        return m.Remove(key);
    }

    public static bool map_contains_key_q<T0, T1>(System.Collections.Immutable.ImmutableDictionary<T0, T1> m, T0 key)
    {
        return m.ContainsKey(key);
    }

    public static bool map_empty_q<T0, T1>(System.Collections.Immutable.ImmutableDictionary<T0, T1> m)
    {
        return (m.Count == 0);
    }

    public static Option<T1> map_get<T0, T1>(System.Collections.Immutable.ImmutableDictionary<T0, T1> m, T0 key)
    {
        return (m.ContainsKey(key) ? new Some<T1>(m[key]) : new None<T1>());
    }

    public static System.Collections.Immutable.ImmutableList<T0> map_keys<T0, T1>(System.Collections.Immutable.ImmutableDictionary<T0, T1> m)
    {
        return ZScript.Runtime.CollectionHelpers.MapKeys(m);
    }

    public static System.Collections.Immutable.ImmutableList<T1> map_values<T0, T1>(System.Collections.Immutable.ImmutableDictionary<T0, T1> m)
    {
        return ZScript.Runtime.CollectionHelpers.MapValues(m);
    }

}
