// <auto-generated by ZScript compiler 0.1.0+b78848d>
#nullable enable

namespace ZScript.Examples;

public static class ClrNew
{
    public static System.Object obj = new System.Object();
    public static System.Text.StringBuilder sb = new System.Text.StringBuilder("Hello, ZScript!");
    public static System.Collections.ArrayList lst = new System.Collections.ArrayList(16);
    public static int main(ZScript.Runtime.ZsList<string> args)
    {
        return 0;
    }


    static ClrNew()
    {
        System.Console.WriteLine("constructed object");
        System.Console.WriteLine("constructed string builder");
        System.Console.WriteLine("constructed array list");
    }

    public static int Main(string[] args)
    {
        return main(ZScript.Runtime.ZsList<string>.FromItems(args));
    }
}
