// <auto-generated by ZScript compiler 0.1.0+9c8023c>
#nullable enable

namespace ZScript.Examples;

public sealed record ZsUnit { public static readonly ZsUnit Value = new(); }

public static class CollectionsModule
{
    public static System.Collections.Immutable.ImmutableList<int> primes = System.Collections.Immutable.ImmutableList.Create(2, 3, 5, 7, 11);
    public static System.Collections.Immutable.ImmutableArray<int> coords = System.Collections.Immutable.ImmutableArray.Create(10, 20, 30);
    public static System.Collections.Immutable.ImmutableDictionary<string, int> scores = System.Collections.Immutable.ImmutableDictionary.CreateRange(new[] { new System.Collections.Generic.KeyValuePair<string, int>("alice", 95), new System.Collections.Generic.KeyValuePair<string, int>("bob", 87), new System.Collections.Generic.KeyValuePair<string, int>("carol", 92) });
    public static System.Collections.Immutable.ImmutableList<int> first_n_squares(int n)
    {
        return System.Collections.Immutable.ImmutableList.Create((1 * 1), (2 * 2), (3 * 3), (4 * 4));
    }

}
