// <auto-generated by ZScript compiler 0.1.0+d4ea328>
#nullable enable

using System.Collections.Immutable;
using ZScript.Runtime;

namespace ZScript.Examples;

public sealed record ZsUnit { public static readonly ZsUnit Value = new(); }

public static class CollectionsModule
{
    public static System.Collections.Immutable.ImmutableList<int> primes = System.Collections.Immutable.ImmutableList.Create(2, 3, 5, 7, 11);
    public static System.Collections.Immutable.ImmutableArray<int> coords = System.Collections.Immutable.ImmutableArray.Create(10, 20, 30);
    public static System.Collections.Immutable.ImmutableDictionary<string, int> scores = System.Collections.Immutable.ImmutableDictionary.CreateRange(new[] { new System.Collections.Generic.KeyValuePair<string, int>("alice", 95), new System.Collections.Generic.KeyValuePair<string, int>("bob", 87), new System.Collections.Generic.KeyValuePair<string, int>("carol", 92) });
    public static System.Collections.Immutable.ImmutableList<int> first_n_squares(int n)
    {
        return System.Collections.Immutable.ImmutableList.Create((1 * 1), (2 * 2), (3 * 3), (4 * 4));
    }

    public static System.Collections.Immutable.ImmutableList<int> doubled_primes = ListModule.list_map(primes, ((int x) => (x * 2)));
    public static System.Collections.Immutable.ImmutableList<int> big_primes = ListModule.list_filter(primes, ((int x) => (x > 5)));
    public static int prime_sum = ListModule.list_fold(primes, 0, ((int acc, int x) => (acc + x)));
    public static int vec_sum = VectorModule.vector_fold(coords, 0, ((int acc, int x) => (acc + x)));
    public static Option<int> lookup_score(string name)
    {
        return MapModule.map_get(scores, name);
    }

}

public abstract record Option<T0>;
public sealed record Some<T0>(T0 value) : Option<T0>;
public sealed record None<T0>() : Option<T0>;


public static class ListModule
{
    public static System.Collections.Immutable.ImmutableList<T1> list__map_loop<T0, T1>(System.Collections.Immutable.ImmutableList<T0> xs, System.Func<T0, T1> f, int len, int i, System.Collections.Immutable.ImmutableList<T1> acc)
    {
        while (true)
        {
            if ((i == len))
            {
                return acc;
            }
            else
            {
                var __tmp_0 = xs;
                var __tmp_1 = f;
                var __tmp_2 = len;
                var __tmp_3 = (i + 1);
                var __tmp_4 = acc.Add(f(xs[i]));
                xs = __tmp_0;
                f = __tmp_1;
                len = __tmp_2;
                i = __tmp_3;
                acc = __tmp_4;
                continue;
            }
        }
    }

    public static System.Collections.Immutable.ImmutableList<T0> list__filter_loop<T0>(System.Collections.Immutable.ImmutableList<T0> xs, System.Func<T0, bool> pred, int len, int i, System.Collections.Immutable.ImmutableList<T0> acc)
    {
        while (true)
        {
            if ((i == len))
            {
                return acc;
            }
            else
            {
                var item = xs[i];
                if (pred(item))
                {
                    var __tmp_0 = xs;
                    var __tmp_1 = pred;
                    var __tmp_2 = len;
                    var __tmp_3 = (i + 1);
                    var __tmp_4 = acc.Add(item);
                    xs = __tmp_0;
                    pred = __tmp_1;
                    len = __tmp_2;
                    i = __tmp_3;
                    acc = __tmp_4;
                    continue;
                }
                else
                {
                    var __tmp_0 = xs;
                    var __tmp_1 = pred;
                    var __tmp_2 = len;
                    var __tmp_3 = (i + 1);
                    var __tmp_4 = acc;
                    xs = __tmp_0;
                    pred = __tmp_1;
                    len = __tmp_2;
                    i = __tmp_3;
                    acc = __tmp_4;
                    continue;
                }
            }
        }
    }

    public static T1 list__fold_loop<T0, T1>(System.Collections.Immutable.ImmutableList<T0> xs, System.Func<T1, T0, T1> f, int len, int i, T1 acc)
    {
        while (true)
        {
            if ((i == len))
            {
                return acc;
            }
            else
            {
                var __tmp_0 = xs;
                var __tmp_1 = f;
                var __tmp_2 = len;
                var __tmp_3 = (i + 1);
                var __tmp_4 = f(acc, xs[i]);
                xs = __tmp_0;
                f = __tmp_1;
                len = __tmp_2;
                i = __tmp_3;
                acc = __tmp_4;
                continue;
            }
        }
    }

    public static int list_count<T0>(System.Collections.Immutable.ImmutableList<T0> xs)
    {
        return xs.Count;
    }

    public static T0 list_nth<T0>(System.Collections.Immutable.ImmutableList<T0> xs, int i)
    {
        return xs[i];
    }

    public static T0 list_head<T0>(System.Collections.Immutable.ImmutableList<T0> xs)
    {
        return xs[0];
    }

    public static System.Collections.Immutable.ImmutableList<T0> list_tail<T0>(System.Collections.Immutable.ImmutableList<T0> xs)
    {
        return xs.RemoveAt(0);
    }

    public static System.Collections.Immutable.ImmutableList<T0> list_cons<T0>(T0 x, System.Collections.Immutable.ImmutableList<T0> xs)
    {
        return xs.Insert(0, x);
    }

    public static System.Collections.Immutable.ImmutableList<T0> list_append<T0>(System.Collections.Immutable.ImmutableList<T0> xs, T0 x)
    {
        return xs.Add(x);
    }

    public static System.Collections.Immutable.ImmutableList<T0> list_concat<T0>(System.Collections.Immutable.ImmutableList<T0> xs, System.Collections.Immutable.ImmutableList<T0> ys)
    {
        return xs.AddRange(ys);
    }

    public static bool list_empty_q<T0>(System.Collections.Immutable.ImmutableList<T0> xs)
    {
        return (xs.Count == 0);
    }

    public static System.Collections.Immutable.ImmutableList<T1> list_map<T0, T1>(System.Collections.Immutable.ImmutableList<T0> xs, System.Func<T0, T1> f)
    {
        var len = xs.Count;
        return ListModule.list__map_loop(xs, f, len, 0, System.Collections.Immutable.ImmutableList<T1>.Empty);
    }

    public static System.Collections.Immutable.ImmutableList<T0> list_filter<T0>(System.Collections.Immutable.ImmutableList<T0> xs, System.Func<T0, bool> pred)
    {
        var len = xs.Count;
        return ListModule.list__filter_loop(xs, pred, len, 0, System.Collections.Immutable.ImmutableList<T0>.Empty);
    }

    public static T1 list_fold<T0, T1>(System.Collections.Immutable.ImmutableList<T0> xs, T1 init, System.Func<T1, T0, T1> f)
    {
        var len = xs.Count;
        return ListModule.list__fold_loop(xs, f, len, 0, init);
    }

}

public static class VectorModule
{
    public static System.Collections.Immutable.ImmutableArray<T1> vector__map_loop<T0, T1>(System.Collections.Immutable.ImmutableArray<T0> xs, System.Func<T0, T1> f, int len, int i, System.Collections.Immutable.ImmutableArray<T1> acc)
    {
        while (true)
        {
            if ((i == len))
            {
                return acc;
            }
            else
            {
                var __tmp_0 = xs;
                var __tmp_1 = f;
                var __tmp_2 = len;
                var __tmp_3 = (i + 1);
                var __tmp_4 = acc.Add(f(xs[i]));
                xs = __tmp_0;
                f = __tmp_1;
                len = __tmp_2;
                i = __tmp_3;
                acc = __tmp_4;
                continue;
            }
        }
    }

    public static System.Collections.Immutable.ImmutableArray<T0> vector__filter_loop<T0>(System.Collections.Immutable.ImmutableArray<T0> xs, System.Func<T0, bool> pred, int len, int i, System.Collections.Immutable.ImmutableArray<T0> acc)
    {
        while (true)
        {
            if ((i == len))
            {
                return acc;
            }
            else
            {
                var item = xs[i];
                if (pred(item))
                {
                    var __tmp_0 = xs;
                    var __tmp_1 = pred;
                    var __tmp_2 = len;
                    var __tmp_3 = (i + 1);
                    var __tmp_4 = acc.Add(item);
                    xs = __tmp_0;
                    pred = __tmp_1;
                    len = __tmp_2;
                    i = __tmp_3;
                    acc = __tmp_4;
                    continue;
                }
                else
                {
                    var __tmp_0 = xs;
                    var __tmp_1 = pred;
                    var __tmp_2 = len;
                    var __tmp_3 = (i + 1);
                    var __tmp_4 = acc;
                    xs = __tmp_0;
                    pred = __tmp_1;
                    len = __tmp_2;
                    i = __tmp_3;
                    acc = __tmp_4;
                    continue;
                }
            }
        }
    }

    public static T1 vector__fold_loop<T0, T1>(System.Collections.Immutable.ImmutableArray<T0> xs, System.Func<T1, T0, T1> f, int len, int i, T1 acc)
    {
        while (true)
        {
            if ((i == len))
            {
                return acc;
            }
            else
            {
                var __tmp_0 = xs;
                var __tmp_1 = f;
                var __tmp_2 = len;
                var __tmp_3 = (i + 1);
                var __tmp_4 = f(acc, xs[i]);
                xs = __tmp_0;
                f = __tmp_1;
                len = __tmp_2;
                i = __tmp_3;
                acc = __tmp_4;
                continue;
            }
        }
    }

    public static int vector_count<T0>(System.Collections.Immutable.ImmutableArray<T0> xs)
    {
        return xs.Length;
    }

    public static T0 vector_nth<T0>(System.Collections.Immutable.ImmutableArray<T0> xs, int i)
    {
        return xs[i];
    }

    public static System.Collections.Immutable.ImmutableArray<T0> vector_append<T0>(System.Collections.Immutable.ImmutableArray<T0> xs, T0 x)
    {
        return xs.Add(x);
    }

    public static System.Collections.Immutable.ImmutableArray<T0> vector_set<T0>(System.Collections.Immutable.ImmutableArray<T0> xs, int i, T0 x)
    {
        return xs.SetItem(i, x);
    }

    public static bool vector_empty_q<T0>(System.Collections.Immutable.ImmutableArray<T0> xs)
    {
        return (xs.Length == 0);
    }

    public static System.Collections.Immutable.ImmutableArray<T1> vector_map<T0, T1>(System.Collections.Immutable.ImmutableArray<T0> xs, System.Func<T0, T1> f)
    {
        var len = xs.Length;
        return VectorModule.vector__map_loop(xs, f, len, 0, System.Collections.Immutable.ImmutableArray<T1>.Empty);
    }

    public static System.Collections.Immutable.ImmutableArray<T0> vector_filter<T0>(System.Collections.Immutable.ImmutableArray<T0> xs, System.Func<T0, bool> pred)
    {
        var len = xs.Length;
        return VectorModule.vector__filter_loop(xs, pred, len, 0, System.Collections.Immutable.ImmutableArray<T0>.Empty);
    }

    public static T1 vector_fold<T0, T1>(System.Collections.Immutable.ImmutableArray<T0> xs, T1 init, System.Func<T1, T0, T1> f)
    {
        var len = xs.Length;
        return VectorModule.vector__fold_loop(xs, f, len, 0, init);
    }

}

public static class OptionModule
{
    public static T0 option_unwrap<T0>(Option<T0> opt)
    {
        return opt switch { Some<T0>(var v) => v, None<T0> => throw new System.Exception("Called unwrap on None"), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static T0 option_unwrap_or<T0>(Option<T0> opt, T0 @default)
    {
        return opt switch { Some<T0>(var v) => v, None<T0> => @default, _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static Option<T1> option_map<T0, T1>(Option<T0> opt, System.Func<T0, T1> f)
    {
        return opt switch { Some<T0>(var v) => new Some<T1>(f(v)), None<T0> => new None<T1>(), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static Option<T1> option_flat_map<T0, T1>(Option<T0> opt, System.Func<T0, Option<T1>> f)
    {
        return opt switch { Some<T0>(var v) => f(v), None<T0> => new None<T1>(), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static bool option_some_q<T0>(Option<T0> opt)
    {
        return opt switch { Some<T0>(_) => true, None<T0> => false, _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static bool option_none_q<T0>(Option<T0> opt)
    {
        return opt switch { Some<T0>(_) => false, None<T0> => true, _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

}

public static class MapModule
{
    public static int map_count<T0, T1>(System.Collections.Immutable.ImmutableDictionary<T0, T1> m) where T0 : notnull
    {
        return m.Count;
    }

    public static System.Collections.Immutable.ImmutableDictionary<T0, T1> map_put<T0, T1>(System.Collections.Immutable.ImmutableDictionary<T0, T1> m, T0 key, T1 val) where T0 : notnull
    {
        return m.SetItem(key, val);
    }

    public static System.Collections.Immutable.ImmutableDictionary<T0, T1> map_remove<T0, T1>(System.Collections.Immutable.ImmutableDictionary<T0, T1> m, T0 key) where T0 : notnull
    {
        return m.Remove(key);
    }

    public static bool map_contains_key_q<T0, T1>(System.Collections.Immutable.ImmutableDictionary<T0, T1> m, T0 key) where T0 : notnull
    {
        return m.ContainsKey(key);
    }

    public static bool map_empty_q<T0, T1>(System.Collections.Immutable.ImmutableDictionary<T0, T1> m) where T0 : notnull
    {
        return (m.Count == 0);
    }

    public static Option<T1> map_get<T0, T1>(System.Collections.Immutable.ImmutableDictionary<T0, T1> m, T0 key) where T0 : notnull
    {
        return (m.ContainsKey(key) ? new Some<T1>(m[key]) : new None<T1>());
    }

    public static System.Collections.Immutable.ImmutableList<T0> map_keys<T0, T1>(System.Collections.Immutable.ImmutableDictionary<T0, T1> m) where T0 : notnull
    {
        return ZScript.Runtime.CollectionHelpers.MapKeys(m);
    }

    public static System.Collections.Immutable.ImmutableList<T1> map_values<T0, T1>(System.Collections.Immutable.ImmutableDictionary<T0, T1> m) where T0 : notnull
    {
        return ZScript.Runtime.CollectionHelpers.MapValues(m);
    }

}
