// <auto-generated by ZScript compiler 0.1.0+b78848d>
#nullable enable

namespace ZScript.Examples;

public static class Collections
{
    public static ZScript.Runtime.ZsList<int> primes = ZScript.Runtime.ZsList.Of(2, 3, 5, 7, 11);
    public static ZScript.Runtime.ZsVector<int> coords = ZScript.Runtime.ZsVector.Of(10, 20, 30);
    public static ZScript.Runtime.ZsMap<string, int> scores = ZScript.Runtime.ZsMap.Of(("alice", 95), ("bob", 87), ("carol", 92));
    public static ZScript.Runtime.ZsList<int> first_n_squares(int n)
    {
        return ZScript.Runtime.ZsList.Of((1 * 1), (2 * 2), (3 * 3), (4 * 4));
    }

}
