// <auto-generated by ZScript compiler>
#nullable enable

namespace ZScriptGenerated;

public static class Program
{
    public static int gcd(int a, int b)
    {
        while (true)
        {
            if ((b == 0))
            {
                return a;
            }
            else
            {
                var __tmp_0 = b;
                var __tmp_1 = (a % b);
                a = __tmp_0;
                b = __tmp_1;
                continue;
            }
        }
    }

    public static int fib(int n, int a, int b)
    {
        while (true)
        {
            if ((n == 0))
            {
                return a;
            }
            else
            {
                var __tmp_0 = (n - 1);
                var __tmp_1 = b;
                var __tmp_2 = (a + b);
                n = __tmp_0;
                a = __tmp_1;
                b = __tmp_2;
                continue;
            }
        }
    }

    public static int square(int x)
    {
        return (x * x);
    }

    public static int compute(int x)
    {
        return ((int a) => ((int b) => (a + b))((a * 2)))((x + 1));
    }

}
