// <auto-generated by ZScript compiler 0.1.0+b3ce5b6>
#nullable enable

namespace ZScript.Examples;

public static class ErrorHandling
{
    public static ZScript.Runtime.ZsError simple_err()
    {
        return new ZScript.Runtime.ZsError("something went wrong");
    }

    public static ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError> require(ZScript.Runtime.ZsOption<int> opt, string msg)
    {
        return opt switch { ZScript.Runtime.ZsOption<int>.Some(var v) => new ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError>.Ok(v), ZScript.Runtime.ZsOption<int>.None => new ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError>.Err(new ZScript.Runtime.ZsError(msg)), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError> safe_parse(string s)
    {
        return ((System.Func<ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError>>)(() => { try { return new ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError>.Ok(System.Int32.Parse(s)); } catch (System.Exception __ex) { return new ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError>.Err(new ZScript.Runtime.ZsError(__ex.Message)); } }))();
    }

    public static ZScript.Runtime.ZsOption<int> find_user(string name)
    {
        return name switch { "alice" => new ZScript.Runtime.ZsOption<int>.Some(42), "bob" => new ZScript.Runtime.ZsOption<int>.Some(7), _ => new ZScript.Runtime.ZsOption<int>.None(), };
    }

    public static ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError> safe_div(int a, int b)
    {
        return ((b == 0) ? new ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError>.Err(new ZScript.Runtime.ZsError("division by zero")) : new ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError>.Ok((a / b)));
    }

    public static ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError> user_score(string name)
    {
        var __r0 = require(find_user(name), "user not found");
        if (__r0 is ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError>.Err __err0)
            return new ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError>.Err(__err0.Error);
        var id = ((ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError>.Ok)__r0).Value;
        var __r1 = safe_div((id * 100), (id + 1));
        if (__r1 is ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError>.Err __err1)
            return new ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError>.Err(__err1.Error);
        var score = ((ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError>.Ok)__r1).Value;
        return new ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError>.Ok(score);
    }

}
