// <auto-generated by ZScript compiler 0.1.0+b3ce5b6>
#nullable enable

namespace ZScriptGenerated;

public static class Program
{
    public static int divide(int a, int b)
    {
        return ((b == 0) ? throw new System.ArgumentException("divisor cannot be zero") : (a / b));
    }

    public static ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError> safe_divide(int a, int b)
    {
        return ((System.Func<ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError>>)(() => { try { return new ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError>.Ok(divide(a, b)); } catch (System.Exception __ex) { return new ZScript.Runtime.ZsResult<int, ZScript.Runtime.ZsError>.Err(new ZScript.Runtime.ZsError(__ex.Message)); } }))();
    }

    public static int positive_or_throw(int x)
    {
        return ((x > 0) ? x : throw new System.InvalidOperationException("expected positive number"));
    }

}
