// <auto-generated by ZScript compiler 0.1.0+9c8023c>
#nullable enable

namespace ZScript.Examples;

public sealed record ZsUnit { public static readonly ZsUnit Value = new(); }

public static class FactorialModule
{
    public static int factorial(int n, int acc)
    {
        while (true)
        {
            if ((n == 0))
            {
                return acc;
            }
            else
            {
                var __tmp_0 = (n - 1);
                var __tmp_1 = (n * acc);
                n = __tmp_0;
                acc = __tmp_1;
                continue;
            }
        }
    }

}
