// <auto-generated by ZScript compiler 0.1.0+70ffece>
#nullable enable

namespace ZScript.Examples;

public sealed record ZsUnit { public static readonly ZsUnit Value = new(); }

public static class GenericsModule
{
    public static T0 id<T0>(T0 x)
    {
        return x;
    }

    public static T0 @const<T0, T1>(T0 x, T1 y)
    {
        return x;
    }

    public static T1 apply<T0, T1>(System.Func<T0, T1> f, T0 x)
    {
        return f(x);
    }

    public static System.Collections.Immutable.ImmutableList<T0> wrap<T0>(T0 x)
    {
        return System.Collections.Immutable.ImmutableList.Create(x);
    }

    public static System.Func<T0, T2> compose<T0, T1, T2>(System.Func<T1, T2> f, System.Func<T0, T1> g)
    {
        return ((T0 x) => f(g(x)));
    }

}
