// <auto-generated by ZScript compiler 0.1.0+d4ea328>
#nullable enable

namespace ZScript.Examples;

public sealed record ZsUnit { public static readonly ZsUnit Value = new(); }

public static class HigherOrderModule
{
    public static int apply_twice(System.Func<int, int> f, int x)
    {
        return f(f(x));
    }

    public static System.Func<int, int> make_adder(int n)
    {
        return ((int x) => (n + x));
    }

    public static System.Func<int, int> compose(System.Func<int, int> f, System.Func<int, int> g)
    {
        return ((int x) => f(g(x)));
    }

    public static int inc(int x)
    {
        return (x + 1);
    }

    public static int @double(int x)
    {
        return (x * 2);
    }

}
