// <auto-generated by ZScript compiler 0.1.0+d4ea328>
#nullable enable

namespace ZScript.Examples;

public sealed record ZsUnit { public static readonly ZsUnit Value = new(); }

public static class ImportingStdlibModule
{
    public static double sqrt2(double a)
    {
        return System.Math.Sqrt(a);
    }

}
