// <auto-generated by ZScript compiler 0.1.0+7183f05>
#nullable enable

namespace ZScript.Examples;

public static class ImportingStdlib
{
    public static double sqrt2(double a)
    {
        return System.Math.Sqrt(a);
    }

}
