// <auto-generated by ZScript compiler>
#nullable enable

namespace ZScript.Examples;

public interface IGreeter
{
    string Greet();
}

public sealed class HelloGreeter : IGreeter
{
    public string name { get; }

    public HelloGreeter(string name)
    {
        this.name = name;
    }

    public string Greet()
    {
        return this.name;
    }
}

public interface ICalculator
{
    int Add(int a, int b);
    int Negate(int x);
}

public sealed class SimpleCalculator : ICalculator
{

    public SimpleCalculator()
    {
    }

    public int Add(int a, int b)
    {
        return (a + b);
    }

    public int Negate(int x)
    {
        return (0 - x);
    }
}

public interface IAdvancedCalculator : ICalculator
{
    int Multiply(int a, int b);
}

public static class Program
{
    public static string IGreeter_Greet(IGreeter self) => self.Greet();

    public static string HelloGreeter_name(HelloGreeter self) => self.name;
    public static string HelloGreeter_Greet(HelloGreeter self) => self.Greet();

    public static int ICalculator_Add(ICalculator self, int a, int b) => self.Add(a, b);
    public static int ICalculator_Negate(ICalculator self, int x) => self.Negate(x);

    public static int SimpleCalculator_Add(SimpleCalculator self, int a, int b) => self.Add(a, b);
    public static int SimpleCalculator_Negate(SimpleCalculator self, int x) => self.Negate(x);

    public static int IAdvancedCalculator_Multiply(IAdvancedCalculator self, int a, int b) => self.Multiply(a, b);

}
