// <auto-generated by ZScript compiler 0.1.0+9c8023c>
#nullable enable

namespace ZScript.Examples;

public interface IGreeter
{
    string Greet();
}

public sealed class HelloGreeter : IGreeter
{
    public string name { get; }

    public HelloGreeter(string name)
    {
        this.name = name;
    }

    public string Greet()
    {
        return this.name;
    }
}

public interface ICalculator
{
    int Add(int a, int b);
    int Negate(int x);
}

public sealed class SimpleCalculator : ICalculator
{

    public SimpleCalculator()
    {
    }

    public int Add(int a, int b)
    {
        return (a + b);
    }

    public int Negate(int x)
    {
        return (0 - x);
    }
}

public interface IAdvancedCalculator : ICalculator
{
    int Multiply(int a, int b);
}

public sealed record ZsUnit { public static readonly ZsUnit Value = new(); }


public abstract record Option<T0>;
public sealed record Some<T0>(T0 value) : Option<T0>;
public sealed record None<T0>() : Option<T0>;


public abstract record Result<T0, T1>;
public sealed record Ok<T0, T1>(T0 value) : Result<T0, T1>;
public sealed record Err<T0, T1>(T1 error) : Result<T0, T1>;


public sealed record ErrorInfo(string message, Option<ErrorInfo> cause);

public static class OptionModule
{
    public static T0 option_unwrap<T0>(Option<T0> opt)
    {
        return opt switch { Some<T0>(var v) => v, None<T0> => throw new System.Exception("Called unwrap on None"), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static T0 option_unwrap_or<T0>(Option<T0> opt, T0 @default)
    {
        return opt switch { Some<T0>(var v) => v, None<T0> => @default, _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static Option<T1> option_map<T0, T1>(Option<T0> opt, System.Func<T0, T1> f)
    {
        return opt switch { Some<T0>(var v) => new Some<T1>(f(v)), None<T0> => new None<T1>(), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static Option<T1> option_flat_map<T0, T1>(Option<T0> opt, System.Func<T0, Option<T1>> f)
    {
        return opt switch { Some<T0>(var v) => f(v), None<T0> => new None<T1>(), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static bool option_some_q<T0>(Option<T0> opt)
    {
        return opt switch { Some<T0>(_) => true, None<T0> => false, _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static bool option_none_q<T0>(Option<T0> opt)
    {
        return opt switch { Some<T0>(_) => false, None<T0> => true, _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

}

public static class ResultModule
{
    public static T1 result_unwrap<T0, T1>(Result<T1, T0> res)
    {
        return res switch { Ok<T1, T0>(var v) => v, Err<T1, T0>(_) => throw new System.Exception("Called unwrap on Err"), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static Result<T2, T1> result_map<T0, T1, T2>(Result<T0, T1> res, System.Func<T0, T2> f)
    {
        return res switch { Ok<T0, T1>(var v) => new Ok<T2, T1>(f(v)), Err<T0, T1>(var e) => new Err<T2, T1>(e), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static Result<T2, T1> result_flat_map<T0, T1, T2>(Result<T0, T1> res, System.Func<T0, Result<T2, T1>> f)
    {
        return res switch { Ok<T0, T1>(var v) => f(v), Err<T0, T1>(var e) => new Err<T2, T1>(e), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static bool result_ok_q<T0, T1>(Result<T0, T1> res)
    {
        return res switch { Ok<T0, T1>(_) => true, Err<T0, T1>(_) => false, _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static bool result_err_q<T0, T1>(Result<T0, T1> res)
    {
        return res switch { Ok<T0, T1>(_) => false, Err<T0, T1>(_) => true, _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

}

public static class ErrorModule
{
    public static ErrorInfo Error(string msg)
    {
        return new ErrorInfo(message: msg, cause: new None<ErrorInfo>());
    }

}

public static class CoreModule
{
    public static object id(object x)
    {
        return x;
    }

    public static object @const(object x, object y)
    {
        return x;
    }

    public static object compose(System.Func<object, object> f, System.Func<object, object> g, object x)
    {
        return f(g(x));
    }

    public static object flip(System.Func<object, object, object> f, object x, object y)
    {
        return f(y, x);
    }

}
