// <auto-generated by ZScript compiler 0.1.0+b78848d>
#nullable enable

namespace ZScript.Examples;

public interface IGreeter
{
    string Greet();
}

public sealed class HelloGreeter : IGreeter
{
    public string name { get; }

    public HelloGreeter(string name)
    {
        this.name = name;
    }

    public string Greet()
    {
        return this.name;
    }
}

public interface ICalculator
{
    int Add(int a, int b);
    int Negate(int x);
}

public sealed class SimpleCalculator : ICalculator
{

    public SimpleCalculator()
    {
    }

    public int Add(int a, int b)
    {
        return (a + b);
    }

    public int Negate(int x)
    {
        return (0 - x);
    }
}

public interface IAdvancedCalculator : ICalculator
{
    int Multiply(int a, int b);
}

