// <auto-generated by ZScript compiler 0.1.0+a68cc64>
#nullable enable

using System.Text.Json.Serialization;

namespace ZScript.Examples;

public sealed record Point([property: JsonPropertyName("x_coord")] int x, [property: JsonPropertyName("y_coord")] int y);

public sealed record ZsUnit { public static readonly ZsUnit Value = new(); }

