// <auto-generated by ZScript compiler>
#nullable enable

using System.Text.Json.Serialization;

namespace ZScript.Examples;

public sealed record Point([property: JsonPropertyName("x_coord")] int x, [property: JsonPropertyName("y_coord")] int y);

public static class Json
{
}
