// <auto-generated by ZScript compiler 0.1.0+164e302>
#nullable enable

namespace ZScript.Examples;

public sealed record ZsUnit { public static readonly ZsUnit Value = new(); }

public static class LetStarModule
{
    public static int quadratic(int a, int b, int c, int x)
    {
        var x2 = (x * x);
        var ax2 = (a * x2);
        var bx = (b * x);
        return ((ax2 + bx) + c);
    }

    public static int transform(int n)
    {
        var doubled = (n * 2);
        var incremented = (doubled + 1);
        var squared = (incremented * incremented);
        return squared;
    }

    public static int accumulate(int x)
    {
        return ((System.Func<int, int>)((int x) => ((System.Func<int, int>)((int x) => ((System.Func<int, int>)((int x) => x))((x + 10))))((x * 2))))((x + 1));
    }

}
