// <auto-generated by ZScript compiler 0.1.0+b3ce5b6>
#nullable enable

namespace ZScript.Examples;

public static class LetStar
{
    public static int quadratic(int a, int b, int c, int x)
    {
        return ((System.Func<int, int>)((int x2) => ((System.Func<int, int>)((int ax2) => ((System.Func<int, int>)((int bx) => ((ax2 + bx) + c)))((b * x))))((a * x2))))((x * x));
    }

    public static int transform(int n)
    {
        return ((System.Func<int, int>)((int doubled) => ((System.Func<int, int>)((int incremented) => ((System.Func<int, int>)((int squared) => squared))((incremented * incremented))))((doubled + 1))))((n * 2));
    }

    public static int accumulate(int x)
    {
        return ((System.Func<int, int>)((int x) => ((System.Func<int, int>)((int x) => ((System.Func<int, int>)((int x) => x))((x + 10))))((x * 2))))((x + 1));
    }

}
