// <auto-generated by ZScript compiler 0.1.0+b3ce5b6>
#nullable enable

namespace ZScript.Examples;

public static class MathUtils
{
    public static int abs(int x)
    {
        return ((x < 0) ? (0 - x) : x);
    }

    public static int max(int a, int b)
    {
        return ((a > b) ? a : b);
    }

    public static int min(int a, int b)
    {
        return ((a < b) ? a : b);
    }

}
