// <auto-generated by ZScript compiler 0.1.0+a1d5829>
#nullable enable

namespace ZScript.Examples;

public sealed record ZsUnit { public static readonly ZsUnit Value = new(); }

public static class MathUtilsModule
{
    public static int abs(int x)
    {
        return ((x < 0) ? (0 - x) : x);
    }

    public static int max(int a, int b)
    {
        return ((a > b) ? a : b);
    }

    public static int min(int a, int b)
    {
        return ((a < b) ? a : b);
    }

}
