// <auto-generated by ZScript compiler 0.1.0+b3ce5b6>
#nullable enable

namespace ZScript.Examples;

public static class Options
{
    public static ZScript.Runtime.ZsOption<int> find_positive(int x)
    {
        return ((x > 0) ? new ZScript.Runtime.ZsOption<int>.Some(x) : new ZScript.Runtime.ZsOption<int>.None());
    }

    public static ZScript.Runtime.ZsOption<string> day_of_week(int n)
    {
        return n switch { 1 => new ZScript.Runtime.ZsOption<string>.Some("Monday"), 2 => new ZScript.Runtime.ZsOption<string>.Some("Tuesday"), 3 => new ZScript.Runtime.ZsOption<string>.Some("Wednesday"), 4 => new ZScript.Runtime.ZsOption<string>.Some("Thursday"), 5 => new ZScript.Runtime.ZsOption<string>.Some("Friday"), 6 => new ZScript.Runtime.ZsOption<string>.Some("Saturday"), 7 => new ZScript.Runtime.ZsOption<string>.Some("Sunday"), _ => new ZScript.Runtime.ZsOption<string>.None(), };
    }

    public static string describe_option(ZScript.Runtime.ZsOption<int> opt)
    {
        return opt switch { ZScript.Runtime.ZsOption<int>.Some(var v) => ("Got: " + v.ToString()), ZScript.Runtime.ZsOption<int>.None => "Nothing here", _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static int or_else(ZScript.Runtime.ZsOption<int> opt, int @default)
    {
        return opt switch { ZScript.Runtime.ZsOption<int>.Some(var v) => v, ZScript.Runtime.ZsOption<int>.None => @default, _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

}
