// <auto-generated by ZScript compiler 0.1.0+d83f4da>
#nullable enable

namespace ZScript.Examples;

public sealed record ZsUnit { public static readonly ZsUnit Value = new(); }

public static class OptionsModule
{
    public static Option<int> find_positive(int x)
    {
        return ((x > 0) ? new Some<int>(x) : new None<int>());
    }

    public static Option<string> day_of_week(int n)
    {
        return n switch { 1 => new Some<string>("Monday"), 2 => new Some<string>("Tuesday"), 3 => new Some<string>("Wednesday"), 4 => new Some<string>("Thursday"), 5 => new Some<string>("Friday"), 6 => new Some<string>("Saturday"), 7 => new Some<string>("Sunday"), _ => new None<string>(), };
    }

    public static string describe_option(Option<int> opt)
    {
        return opt switch { Some<int>(var v) => ("Got: " + v.ToString()), None<int> => "Nothing here", _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static int or_else(Option<int> opt, int @default)
    {
        return opt switch { Some<int>(var v) => v, None<int> => @default, _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

}

public abstract record Option<T0>;
public sealed record Some<T0>(T0 value) : Option<T0>;
public sealed record None<T0>() : Option<T0>;


public static class OptionModule
{
    public static T0 option_unwrap<T0>(Option<T0> opt)
    {
        return opt switch { Some<T0>(var v) => v, None<T0> => throw new System.Exception("Called unwrap on None"), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static T0 option_unwrap_or<T0>(Option<T0> opt, T0 @default)
    {
        return opt switch { Some<T0>(var v) => v, None<T0> => @default, _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static Option<T1> option_map<T0, T1>(Option<T0> opt, System.Func<T0, T1> f)
    {
        return opt switch { Some<T0>(var v) => new Some<T1>(f(v)), None<T0> => new None<T1>(), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static Option<T1> option_flat_map<T0, T1>(Option<T0> opt, System.Func<T0, Option<T1>> f)
    {
        return opt switch { Some<T0>(var v) => f(v), None<T0> => new None<T1>(), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static bool option_some_q<T0>(Option<T0> opt)
    {
        return opt switch { Some<T0>(_) => true, None<T0> => false, _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static bool option_none_q<T0>(Option<T0> opt)
    {
        return opt switch { Some<T0>(_) => false, None<T0> => true, _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

}
