// <auto-generated by ZScript compiler 0.1.0+d83f4da>
#nullable enable

namespace ZScript.Examples;

public sealed record ZsUnit { public static readonly ZsUnit Value = new(); }

public static class PipesModule
{
    public static int add(int a, int b)
    {
        return (a + b);
    }

    public static int mul(int a, int b)
    {
        return (a * b);
    }

    public static int sub(int a, int b)
    {
        return (a - b);
    }

    public static int pipeline_demo(int x)
    {
        return sub(mul(add(x, 1), 3), 2);
    }

    public static System.Func<int, int> add5 = ((int __p0) => add(5, __p0));
    public static System.Func<int, int> @double = ((int __p0) => mul(2, __p0));
    public static int transform(int x)
    {
        return @double(add5(x));
    }

}
