// <auto-generated by ZScript compiler 0.1.0+164e302>
#nullable enable

namespace ZScript.Examples;

public sealed record Point(int x, int y);

public abstract record Shape;
public sealed record Circle(int radius) : Shape;
public sealed record Rect(int w, int h) : Shape;


public sealed record ZsUnit { public static readonly ZsUnit Value = new(); }

public static class ShapesModule
{
    public static int area(Shape s)
    {
        return s switch { Circle(var r) => (r * r), Rect(var w, var h) => (w * h), _ => throw new System.InvalidOperationException("Non-exhaustive match"), };
    }

    public static string describe(int n)
    {
        return n switch { 0 => "zero", 1 => "one", _ => "other", };
    }

    public static Point offset(int dx, int dy)
    {
        return new Point(x: dx, y: dy);
    }

}
