// <auto-generated by ZScript compiler 0.1.0+9c8023c>
#nullable enable

namespace ZScript.Examples;

public sealed record ZsUnit { public static readonly ZsUnit Value = new(); }

public static class StringsModule
{
    public static string full_name(string first, string last)
    {
        return ((first + " ") + last);
    }

    public static string label(string prefix, int n)
    {
        return (prefix + n.ToString());
    }

    public static string greeting_with_count(string name, int count)
    {
        return (("Hello, " + name) + ("! Visit #" + count.ToString()));
    }

}
