// <auto-generated by ZScript compiler 0.1.0+7183f05>
#nullable enable

using Xunit;

namespace ZScriptGenerated;

public sealed class math
{

    public math()
    {
    }

    [Xunit.FactAttribute]
    public void addition()
    {
        Zunit.check_equal_int_q((1 + 2), 3);
    }

    [Xunit.FactAttribute]
    public void subtraction()
    {
        Zunit.check_equal_int_q((3 - 1), 2);
    }
}


public static class Zunit
{
    public static void check_equal_q(System.Object expected, System.Object actual)
    {
        ZScript.ZUnit.ZsAssert.EqualObj(expected, actual);
    }

    public static void check_not_equal_q(System.Object expected, System.Object actual)
    {
        ZScript.ZUnit.ZsAssert.NotEqualObj(expected, actual);
    }

    public static void check_equal_int_q(int expected, int actual)
    {
        ZScript.ZUnit.ZsAssert.EqualInt(expected, actual);
    }

    public static void check_true(bool v)
    {
        ZScript.ZUnit.ZsAssert.IsTrue(v);
    }

    public static void check_false(bool v)
    {
        ZScript.ZUnit.ZsAssert.IsFalse(v);
    }

    public static void check_not_false(bool v)
    {
        ZScript.ZUnit.ZsAssert.IsTrue(v);
    }

    public static void check_pred(System.Func<object, bool> pred, object v)
    {
        ZScript.ZUnit.ZsAssert.IsTrue(pred(v));
    }

    public static void fail(string msg)
    {
        ZScript.ZUnit.ZsAssert.Fail(msg);
    }

}
