// <auto-generated by ZScript compiler 0.1.0+604cce7>
#nullable enable

using Xunit;

namespace ZScriptGenerated;

public sealed class math
{

    public math()
    {
    }

    [Xunit.FactAttribute]
    public void addition()
    {
        Zunit.check_equal_q((1 + 2), 3);
    }

    [Xunit.FactAttribute]
    public void subtraction()
    {
        Zunit.check_equal_q((3 - 1), 2);
    }
}


public static class Zunit
{
    public static void check_equal_q<T0>(T0 expected, T0 actual)
    {
        Xunit.Assert.Equal(expected, actual);
    }

    public static void check_not_equal_q<T0>(T0 expected, T0 actual)
    {
        Xunit.Assert.NotEqual(expected, actual);
    }

    public static void check_true(bool v)
    {
        Xunit.Assert.True(v);
    }

    public static void check_false(bool v)
    {
        Xunit.Assert.False(v);
    }

    public static void check_not_false(bool v)
    {
        Xunit.Assert.True(v);
    }

    public static void check_pred<T0>(System.Func<T0, bool> pred, T0 v)
    {
        Xunit.Assert.True(pred(v));
    }

    public static void fail(string msg)
    {
        Xunit.Assert.Fail(msg);
    }

}
