<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>zs</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZScheme.Compiler\ZScheme.Compiler.csproj" />
    <ProjectReference Include="..\ZScheme.Runtime\ZScheme.Runtime.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>
</Project>
