<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZScheme.Compiler\ZScheme.Compiler.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OmniSharp.Extensions.LanguageServer" Version="0.19.9" />
  </ItemGroup>
</Project>
