<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>zs-lsp</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ZScheme.LanguageServer.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZScheme.Compiler\ZScheme.Compiler.csproj" />
    <ProjectReference Include="..\ZScheme.Formatter\ZScheme.Formatter.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OmniSharp.Extensions.LanguageServer" Version="0.19.9" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>
</Project>
