name = "ZScheme"
grammar = "zscheme"
path_suffixes = ["zs", "zspkg"]
line_comments = ["; "]
block_comment = []

[brackets]
'(' = ')'
'[' = ']'
'"' = '"'

[autoclose]
'(' = ')'
'[' = ']'
'"' = '"'

[word_characters]
custom = ['_', '-', '?', '!', '>', '+', '*', '/', '=', '<', '&', '|', '%', '^', '~', '#', '@']
