/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 28
#define LARGE_STATE_COUNT 24
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_symbol = 1,
  sym_comment = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK = 6,
  sym_number = 7,
  sym_float = 8,
  anon_sym_DQUOTE = 9,
  aux_sym_string_token1 = 10,
  sym_escape_sequence = 11,
  sym_boolean = 12,
  sym_flag_keyword = 13,
  sym_clr_qualifier = 14,
  sym_type_variable = 15,
  sym_wildcard = 16,
  sym_ellipsis = 17,
  sym_colon = 18,
  anon_sym_SQUOTE = 19,
  anon_sym_BQUOTE = 20,
  anon_sym_COMMA_AT = 21,
  anon_sym_COMMA = 22,
  sym_source_file = 23,
  sym__form = 24,
  sym_list = 25,
  sym_bracket_list = 26,
  sym_string = 27,
  sym_quote = 28,
  sym_quasiquote = 29,
  sym_unquote_splicing = 30,
  sym_unquote = 31,
  aux_sym_source_file_repeat1 = 32,
  aux_sym_string_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_symbol] = "symbol",
  [sym_comment] = "comment",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_number] = "number",
  [sym_float] = "float",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym_boolean] = "boolean",
  [sym_flag_keyword] = "flag_keyword",
  [sym_clr_qualifier] = "clr_qualifier",
  [sym_type_variable] = "type_variable",
  [sym_wildcard] = "wildcard",
  [sym_ellipsis] = "ellipsis",
  [sym_colon] = "colon",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_COMMA_AT] = ",@",
  [anon_sym_COMMA] = ",",
  [sym_source_file] = "source_file",
  [sym__form] = "_form",
  [sym_list] = "list",
  [sym_bracket_list] = "bracket_list",
  [sym_string] = "string",
  [sym_quote] = "quote",
  [sym_quasiquote] = "quasiquote",
  [sym_unquote_splicing] = "unquote_splicing",
  [sym_unquote] = "unquote",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_symbol] = sym_symbol,
  [sym_comment] = sym_comment,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_number] = sym_number,
  [sym_float] = sym_float,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_boolean] = sym_boolean,
  [sym_flag_keyword] = sym_flag_keyword,
  [sym_clr_qualifier] = sym_clr_qualifier,
  [sym_type_variable] = sym_type_variable,
  [sym_wildcard] = sym_wildcard,
  [sym_ellipsis] = sym_ellipsis,
  [sym_colon] = sym_colon,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_COMMA_AT] = anon_sym_COMMA_AT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_source_file] = sym_source_file,
  [sym__form] = sym__form,
  [sym_list] = sym_list,
  [sym_bracket_list] = sym_bracket_list,
  [sym_string] = sym_string,
  [sym_quote] = sym_quote,
  [sym_quasiquote] = sym_quasiquote,
  [sym_unquote_splicing] = sym_unquote_splicing,
  [sym_unquote] = sym_unquote,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_flag_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_clr_qualifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_wildcard] = {
    .visible = true,
    .named = true,
  },
  [sym_ellipsis] = {
    .visible = true,
    .named = true,
  },
  [sym_colon] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__form] = {
    .visible = false,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_bracket_list] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quote] = {
    .visible = true,
    .named = true,
  },
  [sym_quasiquote] = {
    .visible = true,
    .named = true,
  },
  [sym_unquote_splicing] = {
    .visible = true,
    .named = true,
  },
  [sym_unquote] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_head = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_head] = "head",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_head, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
};

static const TSCharacterRange sym_type_variable_character_set_1[] = {
  {'!', '!'}, {'#', '#'}, {'%', '&'}, {'*', '+'}, {'-', '9'}, {'<', 'Z'}, {'^', '_'}, {'a', 'z'},
  {'|', '|'}, {'~', '~'},
};

static const TSCharacterRange sym_symbol_character_set_1[] = {
  {'!', '!'}, {'#', '#'}, {'%', '&'}, {'*', '+'}, {'-', '-'}, {'/', '/'}, {'<', 'Z'}, {'^', '_'},
  {'a', 'z'}, {'|', '|'}, {'~', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(45);
      ADVANCE_MAP(
        '"', 59,
        '#', 68,
        '\'', 75,
        '(', 48,
        ')', 49,
        ',', 78,
        '-', 69,
        '.', 2,
        ':', 74,
        ';', 47,
        '[', 50,
        '\\', 42,
        ']', 51,
        '^', 71,
        '`', 76,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (lookahead == '!' ||
          ('%' <= lookahead && lookahead <= 'z') ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(72);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(59);
      if (lookahead == ';') ADVANCE(46);
      if (lookahead == '\\') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 2:
      if (lookahead == '.') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(73);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(25);
      END_STATE();
    case 6:
      if (lookahead == 'b') ADVANCE(21);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 17:
      if (lookahead == 'h') ADVANCE(9);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(23);
      if (lookahead == 'm') ADVANCE(39);
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(36);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(26);
      if (lookahead == 'p') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(64);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(29);
      END_STATE();
    case 28:
      if (lookahead == 'p') ADVANCE(14);
      END_STATE();
    case 29:
      if (lookahead == 'p') ADVANCE(15);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(65);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 34:
      if (lookahead == 's') ADVANCE(38);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(4);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(64);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(5);
      END_STATE();
    case 39:
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 40:
      if (lookahead == 'x') ADVANCE(16);
      END_STATE();
    case 41:
      if (lookahead == 'y') ADVANCE(65);
      END_STATE();
    case 42:
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(62);
      END_STATE();
    case 43:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 44:
      if (eof) ADVANCE(45);
      ADVANCE_MAP(
        '"', 59,
        '#', 68,
        '\'', 75,
        '(', 48,
        ')', 49,
        ',', 78,
        '-', 69,
        '.', 2,
        ':', 74,
        ';', 47,
        '[', 50,
        ']', 51,
        '^', 71,
        '`', 76,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (lookahead == '!' ||
          ('%' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z') ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(72);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(61);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(47);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(43);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      if (set_contains(sym_symbol_character_set_1, 11, lookahead)) ADVANCE(72);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_float);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (set_contains(sym_type_variable_character_set_1, 10, lookahead)) ADVANCE(72);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_float);
      if (set_contains(sym_type_variable_character_set_1, 10, lookahead)) ADVANCE(72);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == ';') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(61);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_boolean);
      if (set_contains(sym_type_variable_character_set_1, 10, lookahead)) ADVANCE(72);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_flag_keyword);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_clr_qualifier);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_clr_qualifier);
      if (lookahead == '-') ADVANCE(20);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_type_variable);
      if (set_contains(sym_type_variable_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == 'f' ||
          lookahead == 't') ADVANCE(63);
      if (set_contains(sym_type_variable_character_set_1, 10, lookahead)) ADVANCE(72);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      if (set_contains(sym_type_variable_character_set_1, 10, lookahead)) ADVANCE(72);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (set_contains(sym_type_variable_character_set_1, 10, lookahead)) ADVANCE(72);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_symbol);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      if (set_contains(sym_type_variable_character_set_1, 10, lookahead)) ADVANCE(72);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_symbol);
      if (set_contains(sym_type_variable_character_set_1, 10, lookahead)) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_ellipsis);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_colon);
      if (lookahead == 'i') ADVANCE(22);
      if (lookahead == 'w') ADVANCE(17);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_COMMA_AT);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_COMMA);
      if (lookahead == '@') ADVANCE(77);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == '_') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(sym_wildcard);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [sym_flag_keyword] = ACTIONS(1),
    [sym_clr_qualifier] = ACTIONS(1),
    [sym_type_variable] = ACTIONS(1),
    [sym_wildcard] = ACTIONS(1),
    [sym_ellipsis] = ACTIONS(1),
    [sym_colon] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_COMMA_AT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(27),
    [sym__form] = STATE(5),
    [sym_list] = STATE(5),
    [sym_bracket_list] = STATE(5),
    [sym_string] = STATE(5),
    [sym_quote] = STATE(5),
    [sym_quasiquote] = STATE(5),
    [sym_unquote_splicing] = STATE(5),
    [sym_unquote] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_symbol] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [sym_number] = ACTIONS(7),
    [sym_float] = ACTIONS(7),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_boolean] = ACTIONS(7),
    [sym_flag_keyword] = ACTIONS(15),
    [sym_clr_qualifier] = ACTIONS(15),
    [sym_type_variable] = ACTIONS(15),
    [sym_wildcard] = ACTIONS(7),
    [sym_ellipsis] = ACTIONS(15),
    [sym_colon] = ACTIONS(7),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [anon_sym_BQUOTE] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
  },
  [STATE(2)] = {
    [sym__form] = STATE(2),
    [sym_list] = STATE(2),
    [sym_bracket_list] = STATE(2),
    [sym_string] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_quasiquote] = STATE(2),
    [sym_unquote_splicing] = STATE(2),
    [sym_unquote] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_symbol] = ACTIONS(27),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(30),
    [anon_sym_RPAREN] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_RBRACK] = ACTIONS(25),
    [sym_number] = ACTIONS(27),
    [sym_float] = ACTIONS(27),
    [anon_sym_DQUOTE] = ACTIONS(36),
    [sym_boolean] = ACTIONS(27),
    [sym_flag_keyword] = ACTIONS(39),
    [sym_clr_qualifier] = ACTIONS(39),
    [sym_type_variable] = ACTIONS(39),
    [sym_wildcard] = ACTIONS(27),
    [sym_ellipsis] = ACTIONS(39),
    [sym_colon] = ACTIONS(27),
    [anon_sym_SQUOTE] = ACTIONS(42),
    [anon_sym_BQUOTE] = ACTIONS(45),
    [anon_sym_COMMA_AT] = ACTIONS(48),
    [anon_sym_COMMA] = ACTIONS(51),
  },
  [STATE(3)] = {
    [sym__form] = STATE(6),
    [sym_list] = STATE(6),
    [sym_bracket_list] = STATE(6),
    [sym_string] = STATE(6),
    [sym_quote] = STATE(6),
    [sym_quasiquote] = STATE(6),
    [sym_unquote_splicing] = STATE(6),
    [sym_unquote] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [sym_symbol] = ACTIONS(54),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(56),
    [sym_number] = ACTIONS(54),
    [sym_float] = ACTIONS(54),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_boolean] = ACTIONS(54),
    [sym_flag_keyword] = ACTIONS(58),
    [sym_clr_qualifier] = ACTIONS(58),
    [sym_type_variable] = ACTIONS(58),
    [sym_wildcard] = ACTIONS(54),
    [sym_ellipsis] = ACTIONS(58),
    [sym_colon] = ACTIONS(54),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [anon_sym_BQUOTE] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
  },
  [STATE(4)] = {
    [sym__form] = STATE(7),
    [sym_list] = STATE(7),
    [sym_bracket_list] = STATE(7),
    [sym_string] = STATE(7),
    [sym_quote] = STATE(7),
    [sym_quasiquote] = STATE(7),
    [sym_unquote_splicing] = STATE(7),
    [sym_unquote] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [sym_symbol] = ACTIONS(60),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(62),
    [anon_sym_LBRACK] = ACTIONS(11),
    [sym_number] = ACTIONS(60),
    [sym_float] = ACTIONS(60),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_boolean] = ACTIONS(60),
    [sym_flag_keyword] = ACTIONS(64),
    [sym_clr_qualifier] = ACTIONS(64),
    [sym_type_variable] = ACTIONS(64),
    [sym_wildcard] = ACTIONS(60),
    [sym_ellipsis] = ACTIONS(64),
    [sym_colon] = ACTIONS(60),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [anon_sym_BQUOTE] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
  },
  [STATE(5)] = {
    [sym__form] = STATE(2),
    [sym_list] = STATE(2),
    [sym_bracket_list] = STATE(2),
    [sym_string] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_quasiquote] = STATE(2),
    [sym_unquote_splicing] = STATE(2),
    [sym_unquote] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(66),
    [sym_symbol] = ACTIONS(68),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [sym_number] = ACTIONS(68),
    [sym_float] = ACTIONS(68),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_boolean] = ACTIONS(68),
    [sym_flag_keyword] = ACTIONS(70),
    [sym_clr_qualifier] = ACTIONS(70),
    [sym_type_variable] = ACTIONS(70),
    [sym_wildcard] = ACTIONS(68),
    [sym_ellipsis] = ACTIONS(70),
    [sym_colon] = ACTIONS(68),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [anon_sym_BQUOTE] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
  },
  [STATE(6)] = {
    [sym__form] = STATE(2),
    [sym_list] = STATE(2),
    [sym_bracket_list] = STATE(2),
    [sym_string] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_quasiquote] = STATE(2),
    [sym_unquote_splicing] = STATE(2),
    [sym_unquote] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(68),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(72),
    [sym_number] = ACTIONS(68),
    [sym_float] = ACTIONS(68),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_boolean] = ACTIONS(68),
    [sym_flag_keyword] = ACTIONS(70),
    [sym_clr_qualifier] = ACTIONS(70),
    [sym_type_variable] = ACTIONS(70),
    [sym_wildcard] = ACTIONS(68),
    [sym_ellipsis] = ACTIONS(70),
    [sym_colon] = ACTIONS(68),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [anon_sym_BQUOTE] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
  },
  [STATE(7)] = {
    [sym__form] = STATE(2),
    [sym_list] = STATE(2),
    [sym_bracket_list] = STATE(2),
    [sym_string] = STATE(2),
    [sym_quote] = STATE(2),
    [sym_quasiquote] = STATE(2),
    [sym_unquote_splicing] = STATE(2),
    [sym_unquote] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_symbol] = ACTIONS(68),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(74),
    [anon_sym_LBRACK] = ACTIONS(11),
    [sym_number] = ACTIONS(68),
    [sym_float] = ACTIONS(68),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_boolean] = ACTIONS(68),
    [sym_flag_keyword] = ACTIONS(70),
    [sym_clr_qualifier] = ACTIONS(70),
    [sym_type_variable] = ACTIONS(70),
    [sym_wildcard] = ACTIONS(68),
    [sym_ellipsis] = ACTIONS(70),
    [sym_colon] = ACTIONS(68),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [anon_sym_BQUOTE] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
  },
  [STATE(8)] = {
    [sym__form] = STATE(4),
    [sym_list] = STATE(4),
    [sym_bracket_list] = STATE(4),
    [sym_string] = STATE(4),
    [sym_quote] = STATE(4),
    [sym_quasiquote] = STATE(4),
    [sym_unquote_splicing] = STATE(4),
    [sym_unquote] = STATE(4),
    [sym_symbol] = ACTIONS(76),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(78),
    [anon_sym_LBRACK] = ACTIONS(11),
    [sym_number] = ACTIONS(76),
    [sym_float] = ACTIONS(76),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_boolean] = ACTIONS(76),
    [sym_flag_keyword] = ACTIONS(80),
    [sym_clr_qualifier] = ACTIONS(80),
    [sym_type_variable] = ACTIONS(80),
    [sym_wildcard] = ACTIONS(76),
    [sym_ellipsis] = ACTIONS(80),
    [sym_colon] = ACTIONS(76),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [anon_sym_BQUOTE] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
  },
  [STATE(9)] = {
    [sym__form] = STATE(17),
    [sym_list] = STATE(17),
    [sym_bracket_list] = STATE(17),
    [sym_string] = STATE(17),
    [sym_quote] = STATE(17),
    [sym_quasiquote] = STATE(17),
    [sym_unquote_splicing] = STATE(17),
    [sym_unquote] = STATE(17),
    [sym_symbol] = ACTIONS(82),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [sym_number] = ACTIONS(82),
    [sym_float] = ACTIONS(82),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_boolean] = ACTIONS(82),
    [sym_flag_keyword] = ACTIONS(84),
    [sym_clr_qualifier] = ACTIONS(84),
    [sym_type_variable] = ACTIONS(84),
    [sym_wildcard] = ACTIONS(82),
    [sym_ellipsis] = ACTIONS(84),
    [sym_colon] = ACTIONS(82),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [anon_sym_BQUOTE] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
  },
  [STATE(10)] = {
    [sym__form] = STATE(19),
    [sym_list] = STATE(19),
    [sym_bracket_list] = STATE(19),
    [sym_string] = STATE(19),
    [sym_quote] = STATE(19),
    [sym_quasiquote] = STATE(19),
    [sym_unquote_splicing] = STATE(19),
    [sym_unquote] = STATE(19),
    [sym_symbol] = ACTIONS(86),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [sym_number] = ACTIONS(86),
    [sym_float] = ACTIONS(86),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_boolean] = ACTIONS(86),
    [sym_flag_keyword] = ACTIONS(88),
    [sym_clr_qualifier] = ACTIONS(88),
    [sym_type_variable] = ACTIONS(88),
    [sym_wildcard] = ACTIONS(86),
    [sym_ellipsis] = ACTIONS(88),
    [sym_colon] = ACTIONS(86),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [anon_sym_BQUOTE] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
  },
  [STATE(11)] = {
    [sym__form] = STATE(16),
    [sym_list] = STATE(16),
    [sym_bracket_list] = STATE(16),
    [sym_string] = STATE(16),
    [sym_quote] = STATE(16),
    [sym_quasiquote] = STATE(16),
    [sym_unquote_splicing] = STATE(16),
    [sym_unquote] = STATE(16),
    [sym_symbol] = ACTIONS(90),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [sym_number] = ACTIONS(90),
    [sym_float] = ACTIONS(90),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_boolean] = ACTIONS(90),
    [sym_flag_keyword] = ACTIONS(92),
    [sym_clr_qualifier] = ACTIONS(92),
    [sym_type_variable] = ACTIONS(92),
    [sym_wildcard] = ACTIONS(90),
    [sym_ellipsis] = ACTIONS(92),
    [sym_colon] = ACTIONS(90),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [anon_sym_BQUOTE] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
  },
  [STATE(12)] = {
    [sym__form] = STATE(18),
    [sym_list] = STATE(18),
    [sym_bracket_list] = STATE(18),
    [sym_string] = STATE(18),
    [sym_quote] = STATE(18),
    [sym_quasiquote] = STATE(18),
    [sym_unquote_splicing] = STATE(18),
    [sym_unquote] = STATE(18),
    [sym_symbol] = ACTIONS(94),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [sym_number] = ACTIONS(94),
    [sym_float] = ACTIONS(94),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_boolean] = ACTIONS(94),
    [sym_flag_keyword] = ACTIONS(96),
    [sym_clr_qualifier] = ACTIONS(96),
    [sym_type_variable] = ACTIONS(96),
    [sym_wildcard] = ACTIONS(94),
    [sym_ellipsis] = ACTIONS(96),
    [sym_colon] = ACTIONS(94),
    [anon_sym_SQUOTE] = ACTIONS(17),
    [anon_sym_BQUOTE] = ACTIONS(19),
    [anon_sym_COMMA_AT] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(23),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(98),
    [sym_symbol] = ACTIONS(100),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(98),
    [anon_sym_RPAREN] = ACTIONS(98),
    [anon_sym_LBRACK] = ACTIONS(98),
    [anon_sym_RBRACK] = ACTIONS(98),
    [sym_number] = ACTIONS(100),
    [sym_float] = ACTIONS(100),
    [anon_sym_DQUOTE] = ACTIONS(98),
    [sym_boolean] = ACTIONS(100),
    [sym_flag_keyword] = ACTIONS(98),
    [sym_clr_qualifier] = ACTIONS(98),
    [sym_type_variable] = ACTIONS(98),
    [sym_wildcard] = ACTIONS(100),
    [sym_ellipsis] = ACTIONS(98),
    [sym_colon] = ACTIONS(100),
    [anon_sym_SQUOTE] = ACTIONS(98),
    [anon_sym_BQUOTE] = ACTIONS(98),
    [anon_sym_COMMA_AT] = ACTIONS(98),
    [anon_sym_COMMA] = ACTIONS(100),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(102),
    [sym_symbol] = ACTIONS(104),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(102),
    [anon_sym_RPAREN] = ACTIONS(102),
    [anon_sym_LBRACK] = ACTIONS(102),
    [anon_sym_RBRACK] = ACTIONS(102),
    [sym_number] = ACTIONS(104),
    [sym_float] = ACTIONS(104),
    [anon_sym_DQUOTE] = ACTIONS(102),
    [sym_boolean] = ACTIONS(104),
    [sym_flag_keyword] = ACTIONS(102),
    [sym_clr_qualifier] = ACTIONS(102),
    [sym_type_variable] = ACTIONS(102),
    [sym_wildcard] = ACTIONS(104),
    [sym_ellipsis] = ACTIONS(102),
    [sym_colon] = ACTIONS(104),
    [anon_sym_SQUOTE] = ACTIONS(102),
    [anon_sym_BQUOTE] = ACTIONS(102),
    [anon_sym_COMMA_AT] = ACTIONS(102),
    [anon_sym_COMMA] = ACTIONS(104),
  },
  [STATE(15)] = {
    [ts_builtin_sym_end] = ACTIONS(106),
    [sym_symbol] = ACTIONS(108),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(106),
    [anon_sym_RPAREN] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_RBRACK] = ACTIONS(106),
    [sym_number] = ACTIONS(108),
    [sym_float] = ACTIONS(108),
    [anon_sym_DQUOTE] = ACTIONS(106),
    [sym_boolean] = ACTIONS(108),
    [sym_flag_keyword] = ACTIONS(106),
    [sym_clr_qualifier] = ACTIONS(106),
    [sym_type_variable] = ACTIONS(106),
    [sym_wildcard] = ACTIONS(108),
    [sym_ellipsis] = ACTIONS(106),
    [sym_colon] = ACTIONS(108),
    [anon_sym_SQUOTE] = ACTIONS(106),
    [anon_sym_BQUOTE] = ACTIONS(106),
    [anon_sym_COMMA_AT] = ACTIONS(106),
    [anon_sym_COMMA] = ACTIONS(108),
  },
  [STATE(16)] = {
    [ts_builtin_sym_end] = ACTIONS(110),
    [sym_symbol] = ACTIONS(112),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(110),
    [anon_sym_RPAREN] = ACTIONS(110),
    [anon_sym_LBRACK] = ACTIONS(110),
    [anon_sym_RBRACK] = ACTIONS(110),
    [sym_number] = ACTIONS(112),
    [sym_float] = ACTIONS(112),
    [anon_sym_DQUOTE] = ACTIONS(110),
    [sym_boolean] = ACTIONS(112),
    [sym_flag_keyword] = ACTIONS(110),
    [sym_clr_qualifier] = ACTIONS(110),
    [sym_type_variable] = ACTIONS(110),
    [sym_wildcard] = ACTIONS(112),
    [sym_ellipsis] = ACTIONS(110),
    [sym_colon] = ACTIONS(112),
    [anon_sym_SQUOTE] = ACTIONS(110),
    [anon_sym_BQUOTE] = ACTIONS(110),
    [anon_sym_COMMA_AT] = ACTIONS(110),
    [anon_sym_COMMA] = ACTIONS(112),
  },
  [STATE(17)] = {
    [ts_builtin_sym_end] = ACTIONS(114),
    [sym_symbol] = ACTIONS(116),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(114),
    [anon_sym_RPAREN] = ACTIONS(114),
    [anon_sym_LBRACK] = ACTIONS(114),
    [anon_sym_RBRACK] = ACTIONS(114),
    [sym_number] = ACTIONS(116),
    [sym_float] = ACTIONS(116),
    [anon_sym_DQUOTE] = ACTIONS(114),
    [sym_boolean] = ACTIONS(116),
    [sym_flag_keyword] = ACTIONS(114),
    [sym_clr_qualifier] = ACTIONS(114),
    [sym_type_variable] = ACTIONS(114),
    [sym_wildcard] = ACTIONS(116),
    [sym_ellipsis] = ACTIONS(114),
    [sym_colon] = ACTIONS(116),
    [anon_sym_SQUOTE] = ACTIONS(114),
    [anon_sym_BQUOTE] = ACTIONS(114),
    [anon_sym_COMMA_AT] = ACTIONS(114),
    [anon_sym_COMMA] = ACTIONS(116),
  },
  [STATE(18)] = {
    [ts_builtin_sym_end] = ACTIONS(118),
    [sym_symbol] = ACTIONS(120),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(118),
    [anon_sym_RPAREN] = ACTIONS(118),
    [anon_sym_LBRACK] = ACTIONS(118),
    [anon_sym_RBRACK] = ACTIONS(118),
    [sym_number] = ACTIONS(120),
    [sym_float] = ACTIONS(120),
    [anon_sym_DQUOTE] = ACTIONS(118),
    [sym_boolean] = ACTIONS(120),
    [sym_flag_keyword] = ACTIONS(118),
    [sym_clr_qualifier] = ACTIONS(118),
    [sym_type_variable] = ACTIONS(118),
    [sym_wildcard] = ACTIONS(120),
    [sym_ellipsis] = ACTIONS(118),
    [sym_colon] = ACTIONS(120),
    [anon_sym_SQUOTE] = ACTIONS(118),
    [anon_sym_BQUOTE] = ACTIONS(118),
    [anon_sym_COMMA_AT] = ACTIONS(118),
    [anon_sym_COMMA] = ACTIONS(120),
  },
  [STATE(19)] = {
    [ts_builtin_sym_end] = ACTIONS(122),
    [sym_symbol] = ACTIONS(124),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(122),
    [anon_sym_RPAREN] = ACTIONS(122),
    [anon_sym_LBRACK] = ACTIONS(122),
    [anon_sym_RBRACK] = ACTIONS(122),
    [sym_number] = ACTIONS(124),
    [sym_float] = ACTIONS(124),
    [anon_sym_DQUOTE] = ACTIONS(122),
    [sym_boolean] = ACTIONS(124),
    [sym_flag_keyword] = ACTIONS(122),
    [sym_clr_qualifier] = ACTIONS(122),
    [sym_type_variable] = ACTIONS(122),
    [sym_wildcard] = ACTIONS(124),
    [sym_ellipsis] = ACTIONS(122),
    [sym_colon] = ACTIONS(124),
    [anon_sym_SQUOTE] = ACTIONS(122),
    [anon_sym_BQUOTE] = ACTIONS(122),
    [anon_sym_COMMA_AT] = ACTIONS(122),
    [anon_sym_COMMA] = ACTIONS(124),
  },
  [STATE(20)] = {
    [ts_builtin_sym_end] = ACTIONS(126),
    [sym_symbol] = ACTIONS(128),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(126),
    [anon_sym_RPAREN] = ACTIONS(126),
    [anon_sym_LBRACK] = ACTIONS(126),
    [anon_sym_RBRACK] = ACTIONS(126),
    [sym_number] = ACTIONS(128),
    [sym_float] = ACTIONS(128),
    [anon_sym_DQUOTE] = ACTIONS(126),
    [sym_boolean] = ACTIONS(128),
    [sym_flag_keyword] = ACTIONS(126),
    [sym_clr_qualifier] = ACTIONS(126),
    [sym_type_variable] = ACTIONS(126),
    [sym_wildcard] = ACTIONS(128),
    [sym_ellipsis] = ACTIONS(126),
    [sym_colon] = ACTIONS(128),
    [anon_sym_SQUOTE] = ACTIONS(126),
    [anon_sym_BQUOTE] = ACTIONS(126),
    [anon_sym_COMMA_AT] = ACTIONS(126),
    [anon_sym_COMMA] = ACTIONS(128),
  },
  [STATE(21)] = {
    [ts_builtin_sym_end] = ACTIONS(130),
    [sym_symbol] = ACTIONS(132),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(130),
    [anon_sym_RPAREN] = ACTIONS(130),
    [anon_sym_LBRACK] = ACTIONS(130),
    [anon_sym_RBRACK] = ACTIONS(130),
    [sym_number] = ACTIONS(132),
    [sym_float] = ACTIONS(132),
    [anon_sym_DQUOTE] = ACTIONS(130),
    [sym_boolean] = ACTIONS(132),
    [sym_flag_keyword] = ACTIONS(130),
    [sym_clr_qualifier] = ACTIONS(130),
    [sym_type_variable] = ACTIONS(130),
    [sym_wildcard] = ACTIONS(132),
    [sym_ellipsis] = ACTIONS(130),
    [sym_colon] = ACTIONS(132),
    [anon_sym_SQUOTE] = ACTIONS(130),
    [anon_sym_BQUOTE] = ACTIONS(130),
    [anon_sym_COMMA_AT] = ACTIONS(130),
    [anon_sym_COMMA] = ACTIONS(132),
  },
  [STATE(22)] = {
    [ts_builtin_sym_end] = ACTIONS(134),
    [sym_symbol] = ACTIONS(136),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(134),
    [anon_sym_RPAREN] = ACTIONS(134),
    [anon_sym_LBRACK] = ACTIONS(134),
    [anon_sym_RBRACK] = ACTIONS(134),
    [sym_number] = ACTIONS(136),
    [sym_float] = ACTIONS(136),
    [anon_sym_DQUOTE] = ACTIONS(134),
    [sym_boolean] = ACTIONS(136),
    [sym_flag_keyword] = ACTIONS(134),
    [sym_clr_qualifier] = ACTIONS(134),
    [sym_type_variable] = ACTIONS(134),
    [sym_wildcard] = ACTIONS(136),
    [sym_ellipsis] = ACTIONS(134),
    [sym_colon] = ACTIONS(136),
    [anon_sym_SQUOTE] = ACTIONS(134),
    [anon_sym_BQUOTE] = ACTIONS(134),
    [anon_sym_COMMA_AT] = ACTIONS(134),
    [anon_sym_COMMA] = ACTIONS(136),
  },
  [STATE(23)] = {
    [ts_builtin_sym_end] = ACTIONS(138),
    [sym_symbol] = ACTIONS(140),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(138),
    [anon_sym_RPAREN] = ACTIONS(138),
    [anon_sym_LBRACK] = ACTIONS(138),
    [anon_sym_RBRACK] = ACTIONS(138),
    [sym_number] = ACTIONS(140),
    [sym_float] = ACTIONS(140),
    [anon_sym_DQUOTE] = ACTIONS(138),
    [sym_boolean] = ACTIONS(140),
    [sym_flag_keyword] = ACTIONS(138),
    [sym_clr_qualifier] = ACTIONS(138),
    [sym_type_variable] = ACTIONS(138),
    [sym_wildcard] = ACTIONS(140),
    [sym_ellipsis] = ACTIONS(138),
    [sym_colon] = ACTIONS(140),
    [anon_sym_SQUOTE] = ACTIONS(138),
    [anon_sym_BQUOTE] = ACTIONS(138),
    [anon_sym_COMMA_AT] = ACTIONS(138),
    [anon_sym_COMMA] = ACTIONS(140),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(142), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_DQUOTE,
    ACTIONS(146), 1,
      aux_sym_string_token1,
    ACTIONS(148), 1,
      sym_escape_sequence,
    STATE(25), 1,
      aux_sym_string_repeat1,
  [16] = 5,
    ACTIONS(142), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_DQUOTE,
    ACTIONS(152), 1,
      aux_sym_string_token1,
    ACTIONS(154), 1,
      sym_escape_sequence,
    STATE(26), 1,
      aux_sym_string_repeat1,
  [32] = 5,
    ACTIONS(142), 1,
      sym_comment,
    ACTIONS(156), 1,
      anon_sym_DQUOTE,
    ACTIONS(158), 1,
      aux_sym_string_token1,
    ACTIONS(161), 1,
      sym_escape_sequence,
    STATE(26), 1,
      aux_sym_string_repeat1,
  [48] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(24)] = 0,
  [SMALL_STATE(25)] = 16,
  [SMALL_STATE(26)] = 32,
  [SMALL_STATE(27)] = 48,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_list, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_list, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quasiquote, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quasiquote, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unquote_splicing, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unquote_splicing, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unquote, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unquote, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 1),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 1),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_list, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_list, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, 0, 1),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4, 0, 1),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [146] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [158] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [164] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_zscheme(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_symbol,
    .primary_state_ids = ts_primary_state_ids,
    .name = "zscheme",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
